-- Durable non-PTS online delivery queue.
--
-- This table is intentionally separate from user_update_events/dispatch_outbox:
-- profile/name/color refresh updates do not carry nor consume Telegram PTS, but
-- Core still must not push them through Edge directly. Egress claims these
-- opaque TL update bytes with the same attempt fencing and client-ACK recovery
-- model used by the PTS dispatch outbox.

CREATE TABLE edge_delivery_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    payload bytea NOT NULL CHECK (octet_length(payload) > 0),
    exclude_session_id bigint DEFAULT 0 NOT NULL,
    exclude_auth_key_id bigint DEFAULT 0 NOT NULL,
    status varchar(16) DEFAULT 'pending' NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    logical_shard smallint GENERATED ALWAYS AS (
        mod(abs(target_user_id), 256)
    ) STORED,
    next_attempt_at timestamp with time zone DEFAULT now() NOT NULL,
    sent_sessions integer DEFAULT 0 NOT NULL,
    last_error text DEFAULT '' NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT edge_delivery_outbox_status_check
        CHECK (status IN ('pending', 'dispatching', 'awaiting_ack', 'failed')),
    CONSTRAINT edge_delivery_outbox_attempts_check
        CHECK (attempts >= 0),
    CONSTRAINT edge_delivery_outbox_sent_sessions_check
        CHECK (sent_sessions >= 0),
    CONSTRAINT edge_delivery_outbox_logical_shard_check
        CHECK (logical_shard >= 0 AND logical_shard < 256),
    CONSTRAINT edge_delivery_outbox_exclusion_pair_check
        CHECK (
            ((exclude_auth_key_id = 0) AND (exclude_session_id = 0))
            OR
            ((exclude_auth_key_id <> 0) AND (exclude_session_id <> 0))
        )
);

CREATE UNIQUE INDEX edge_delivery_outbox_target_user_id_id_key
    ON edge_delivery_outbox (target_user_id, id);

CREATE INDEX edge_delivery_outbox_pending_shard_idx
    ON edge_delivery_outbox (
        logical_shard ASC,
        next_attempt_at ASC,
        target_user_id ASC,
        id ASC
    )
    WHERE status = 'pending';

CREATE INDEX edge_delivery_outbox_dispatching_stale_idx
    ON edge_delivery_outbox (
        updated_at ASC,
        logical_shard ASC,
        target_user_id ASC,
        id ASC
    )
    WHERE status = 'dispatching';

CREATE INDEX edge_delivery_outbox_awaiting_ack_stale_idx
    ON edge_delivery_outbox (
        updated_at ASC,
        logical_shard ASC,
        target_user_id ASC,
        id ASC
    )
    WHERE status = 'awaiting_ack';

CREATE INDEX edge_delivery_outbox_failed_cleanup_idx
    ON edge_delivery_outbox (
        updated_at ASC,
        target_user_id ASC,
        id ASC
    )
    WHERE status = 'failed';

CREATE FUNCTION edge_delivery_outbox_notify_ready()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    ready_shard smallint;
BEGIN
    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        FOR ready_shard IN
            SELECT DISTINCT d.logical_shard
            FROM new_rows d
            WHERE d.status = 'pending'
              AND d.next_attempt_at <= now()
              AND NOT EXISTS (
                  SELECT 1
                  FROM edge_delivery_outbox earlier
                  WHERE earlier.target_user_id = d.target_user_id
                    AND earlier.id < d.id
              )
        LOOP
            PERFORM pg_notify('telesrv_edge_delivery_outbox_ready', ready_shard::text);
        END LOOP;
        RETURN NULL;
    END IF;

    FOR ready_shard IN
        SELECT DISTINCT d.logical_shard
        FROM old_rows r
        JOIN edge_delivery_outbox d
          ON d.target_user_id = r.target_user_id
        WHERE d.status = 'pending'
          AND d.next_attempt_at <= now()
          AND NOT EXISTS (
              SELECT 1
              FROM edge_delivery_outbox earlier
              WHERE earlier.target_user_id = d.target_user_id
                AND earlier.id < d.id
          )
    LOOP
        PERFORM pg_notify('telesrv_edge_delivery_outbox_ready', ready_shard::text);
    END LOOP;
    RETURN NULL;
END;
$$;

CREATE TRIGGER edge_delivery_outbox_insert_ready_notify
AFTER INSERT ON edge_delivery_outbox
REFERENCING NEW TABLE AS new_rows
FOR EACH STATEMENT
EXECUTE FUNCTION edge_delivery_outbox_notify_ready();

CREATE TRIGGER edge_delivery_outbox_update_ready_notify
AFTER UPDATE ON edge_delivery_outbox
REFERENCING NEW TABLE AS new_rows
FOR EACH STATEMENT
EXECUTE FUNCTION edge_delivery_outbox_notify_ready();

CREATE TRIGGER edge_delivery_outbox_delete_ready_notify
AFTER DELETE ON edge_delivery_outbox
REFERENCING OLD TABLE AS old_rows
FOR EACH STATEMENT
EXECUTE FUNCTION edge_delivery_outbox_notify_ready();
