-- Durable TON Star Gift export/claim state. Existing local withdrawal rows are
-- intentionally not migrated: they are not evidence of an on-chain asset.

ALTER TABLE public.unique_star_gifts
    ADD COLUMN externalization_pending boolean DEFAULT false NOT NULL,
    ADD CONSTRAINT unique_star_gifts_externalization_check CHECK (
        NOT externalization_pending OR
        (NOT burned AND owner_address='' AND gift_address='')
    );

CREATE TABLE public.star_gift_ton_collection_cursors (
    network text NOT NULL,
    collection_address text NOT NULL,
    next_item_index numeric(20,0) NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    PRIMARY KEY (network, collection_address),
    CONSTRAINT star_gift_ton_collection_cursors_shape_check CHECK (
        network IN ('mainnet','testnet') AND collection_address<>'' AND
        next_item_index>=0 AND next_item_index<=18446744073709551615
    )
);

CREATE TABLE public.star_gift_ton_exports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unique_gift_id bigint NOT NULL REFERENCES public.unique_star_gifts(id) ON DELETE RESTRICT,
    owner_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    token_digest bytea NOT NULL,
    network text NOT NULL,
    collection_address text NOT NULL,
    item_index text NOT NULL,
    expected_item_address text DEFAULT '' NOT NULL,
    metadata_uri text NOT NULL,
    metadata_hash bytea NOT NULL,
    metadata_json bytea NOT NULL,
    wallet_address text DEFAULT '' NOT NULL,
    wallet_state_init_hash bytea,
    wallet_public_key bytea,
    proof_hash bytea,
    status text DEFAULT 'resolving_item' NOT NULL,
    created_at integer NOT NULL,
    expires_at integer NOT NULL,
    proof_verified_at integer DEFAULT 0 NOT NULL,
    submitted_at integer DEFAULT 0 NOT NULL,
    confirmed_at integer DEFAULT 0 NOT NULL,
    finalized_at integer DEFAULT 0 NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    last_error text DEFAULT '' NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT star_gift_ton_exports_unique_gift_uniq UNIQUE (unique_gift_id),
    CONSTRAINT star_gift_ton_exports_token_uniq UNIQUE (token_digest),
    CONSTRAINT star_gift_ton_exports_index_uniq UNIQUE (network, collection_address, item_index),
    CONSTRAINT star_gift_ton_exports_shape_check CHECK (
        owner_user_id>0 AND octet_length(token_digest)=32 AND
        network IN ('mainnet','testnet') AND collection_address<>'' AND item_index ~ '^[0-9]{1,20}$' AND
        metadata_uri<>'' AND octet_length(metadata_hash)=32 AND octet_length(metadata_json) BETWEEN 2 AND 65536 AND
        status IN ('resolving_item','awaiting_wallet','proof_verified','mint_queued','prepared','submitted','confirmed','finalized','failed','quarantined') AND
        created_at>0 AND expires_at>created_at AND proof_verified_at>=0 AND submitted_at>=0 AND
        confirmed_at>=0 AND finalized_at>=0 AND version>0 AND
        (wallet_state_init_hash IS NULL OR octet_length(wallet_state_init_hash)=32) AND
        (wallet_public_key IS NULL OR octet_length(wallet_public_key)=32) AND
        (proof_hash IS NULL OR octet_length(proof_hash)=32) AND
        ((status IN ('resolving_item','awaiting_wallet') AND wallet_address='' AND proof_hash IS NULL) OR
         (status='failed' AND ((wallet_address='' AND proof_hash IS NULL) OR
                               (wallet_address<>'' AND proof_verified_at>0 AND proof_hash IS NOT NULL))) OR
         (status NOT IN ('resolving_item','awaiting_wallet','failed') AND wallet_address<>'' AND proof_verified_at>0 AND proof_hash IS NOT NULL)) AND
        ((status='resolving_item' AND expected_item_address='') OR
         (status NOT IN ('resolving_item','failed') AND expected_item_address<>'') OR
         status='failed') AND
        (status NOT IN ('submitted','confirmed','finalized','quarantined') OR submitted_at>0) AND
        (status NOT IN ('confirmed','finalized') OR confirmed_at>=submitted_at) AND
        (status<>'finalized' OR finalized_at>=confirmed_at)
    )
);

CREATE INDEX star_gift_ton_exports_status_idx
    ON public.star_gift_ton_exports(status, updated_at, id);
CREATE INDEX star_gift_ton_exports_owner_idx
    ON public.star_gift_ton_exports(owner_user_id, id DESC);
CREATE UNIQUE INDEX star_gift_ton_exports_item_uniq
    ON public.star_gift_ton_exports(network, expected_item_address)
    WHERE expected_item_address<>'';

CREATE TABLE public.star_gift_ton_assets (
    export_id bigint PRIMARY KEY REFERENCES public.star_gift_ton_exports(id) ON DELETE RESTRICT,
    network text NOT NULL,
    collection_address text NOT NULL,
    item_address text NOT NULL,
    owner_address text DEFAULT '' NOT NULL,
    metadata_hash bytea NOT NULL,
    submission_hash bytea NOT NULL,
    submission_boc bytea NOT NULL,
    mint_tx_hash bytea,
    mint_tx_lt text DEFAULT '' NOT NULL,
    mint_block_seqno bigint DEFAULT 0 NOT NULL,
    finality_depth integer DEFAULT 0 NOT NULL,
    prepared_at integer NOT NULL,
    valid_until integer NOT NULL,
    submitted_at integer DEFAULT 0 NOT NULL,
    confirmed_at integer DEFAULT 0 NOT NULL,
    owner_observed_lt text DEFAULT '' NOT NULL,
    owner_observed_at integer DEFAULT 0 NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT star_gift_ton_assets_item_uniq UNIQUE (network, item_address),
    CONSTRAINT star_gift_ton_assets_submission_uniq UNIQUE (network, submission_hash),
    CONSTRAINT star_gift_ton_assets_tx_uniq UNIQUE (network, mint_tx_hash),
    CONSTRAINT star_gift_ton_assets_shape_check CHECK (
        network IN ('mainnet','testnet') AND collection_address<>'' AND item_address<>'' AND
        octet_length(metadata_hash)=32 AND octet_length(submission_hash)=32 AND
        octet_length(submission_boc) BETWEEN 1 AND 65536 AND
        (mint_tx_hash IS NULL OR octet_length(mint_tx_hash)=32) AND
        (mint_tx_lt='' OR mint_tx_lt ~ '^[0-9]{1,20}$') AND mint_block_seqno>=0 AND finality_depth>=0 AND
        prepared_at>0 AND valid_until>prepared_at AND submitted_at>=0 AND confirmed_at>=0 AND owner_observed_at>=0 AND
        (owner_observed_lt='' OR owner_observed_lt ~ '^[0-9]{1,20}$') AND
        ((submitted_at=0 AND mint_tx_hash IS NULL AND mint_tx_lt='' AND mint_block_seqno=0) OR submitted_at>=prepared_at) AND
        ((confirmed_at=0 AND owner_address='') OR
         (confirmed_at>=submitted_at AND owner_address<>'' AND mint_tx_hash IS NOT NULL AND mint_tx_lt<>''))
    )
);

CREATE TABLE public.star_gift_ton_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_id bigint NOT NULL REFERENCES public.star_gift_ton_exports(id) ON DELETE RESTRICT,
    job_key text NOT NULL,
    kind text NOT NULL,
    status text DEFAULT 'pending' NOT NULL,
    available_at integer NOT NULL,
    lease_owner text DEFAULT '' NOT NULL,
    lease_expires_at integer DEFAULT 0 NOT NULL,
    fencing_token bigint DEFAULT 0 NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 20 NOT NULL,
    last_error text DEFAULT '' NOT NULL,
    created_at integer NOT NULL,
    completed_at integer DEFAULT 0 NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT star_gift_ton_jobs_key_uniq UNIQUE (job_key),
    CONSTRAINT star_gift_ton_jobs_shape_check CHECK (
        job_key<>'' AND kind IN ('resolve_item','mint','confirm','reconcile_owner','finalize','sync_owner') AND
        status IN ('pending','leased','completed','failed') AND available_at>0 AND
        lease_expires_at>=0 AND fencing_token>=0 AND attempts>=0 AND max_attempts BETWEEN 1 AND 1000 AND
        created_at>0 AND completed_at>=0 AND
        ((status='leased' AND lease_owner<>'' AND lease_expires_at>0) OR
         (status<>'leased' AND lease_owner='' AND lease_expires_at=0)) AND
        ((status='completed' AND completed_at>=created_at) OR (status<>'completed' AND completed_at=0))
    )
);

CREATE INDEX star_gift_ton_jobs_claim_idx
    ON public.star_gift_ton_jobs(available_at, id)
    WHERE status IN ('pending','leased');
CREATE INDEX star_gift_ton_jobs_export_idx
    ON public.star_gift_ton_jobs(export_id, id);

CREATE TABLE public.star_gift_ton_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_digest bytea NOT NULL,
    purpose text NOT NULL,
    export_id bigint NOT NULL REFERENCES public.star_gift_ton_exports(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    auth_context_hash bytea NOT NULL,
    network text NOT NULL,
    proof_domain text NOT NULL,
    proof_payload_hash bytea NOT NULL,
    wallet_address text DEFAULT '' NOT NULL,
    wallet_state_init_hash bytea,
    wallet_public_key bytea,
    proof_hash bytea,
    status text DEFAULT 'pending' NOT NULL,
    created_at integer NOT NULL,
    expires_at integer NOT NULL,
    verified_at integer DEFAULT 0 NOT NULL,
    consumed_at integer DEFAULT 0 NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT star_gift_ton_claims_challenge_uniq UNIQUE (challenge_digest),
    CONSTRAINT star_gift_ton_claims_shape_check CHECK (
        octet_length(challenge_digest)=32 AND purpose IN ('export','claim') AND
        user_id>0 AND octet_length(auth_context_hash)=32 AND
        network IN ('mainnet','testnet') AND proof_domain<>'' AND
        octet_length(proof_payload_hash)=32 AND status IN ('pending','verified','consumed','expired') AND
        created_at>0 AND expires_at>created_at AND verified_at>=0 AND consumed_at>=0 AND
        (wallet_state_init_hash IS NULL OR octet_length(wallet_state_init_hash)=32) AND
        (wallet_public_key IS NULL OR octet_length(wallet_public_key)=32) AND
        (proof_hash IS NULL OR octet_length(proof_hash)=32) AND
        ((status IN ('pending','expired') AND wallet_address='' AND proof_hash IS NULL) OR
         (status IN ('verified','consumed') AND wallet_address<>'' AND proof_hash IS NOT NULL AND verified_at>0)) AND
        (status<>'consumed' OR consumed_at>=verified_at)
    )
);

CREATE INDEX star_gift_ton_claims_expiry_idx
    ON public.star_gift_ton_claims(expires_at, id)
    WHERE status='pending';
CREATE INDEX star_gift_ton_claims_export_idx
    ON public.star_gift_ton_claims(export_id, id DESC)
    WHERE purpose='export';
CREATE INDEX star_gift_ton_claims_wallet_idx
    ON public.star_gift_ton_claims(network, wallet_address, id DESC)
    WHERE status IN ('verified','consumed');

-- Hosted presentation is deliberately separate from peer_star_gifts. The
-- latter remains the immutable Telegram receipt/source row, while this table
-- owns profile visibility after the NFT has moved to the chain.
CREATE TABLE public.star_gift_ton_profile_links (
    export_id bigint PRIMARY KEY REFERENCES public.star_gift_ton_exports(id) ON DELETE RESTRICT,
    unique_gift_id bigint NOT NULL UNIQUE REFERENCES public.unique_star_gifts(id) ON DELETE RESTRICT,
    host_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    unsaved boolean DEFAULT false NOT NULL,
    pinned_order integer DEFAULT 0 NOT NULL,
    linked_at integer NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT star_gift_ton_profile_links_shape_check CHECK (
        host_user_id>0 AND pinned_order BETWEEN 0 AND 6 AND linked_at>0 AND
        (NOT unsaved OR pinned_order=0)
    )
);
CREATE INDEX star_gift_ton_profile_links_host_idx
    ON public.star_gift_ton_profile_links(host_user_id, unsaved, unique_gift_id DESC);
CREATE UNIQUE INDEX star_gift_ton_profile_links_host_pin_uniq
    ON public.star_gift_ton_profile_links(host_user_id, pinned_order)
    WHERE pinned_order>0;

CREATE FUNCTION public.telesrv_guard_star_gift_externalization() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    export_status text;
BEGIN
    IF NOT OLD.externalization_pending AND NEW.externalization_pending THEN
        SELECT status INTO export_status FROM public.star_gift_ton_exports WHERE unique_gift_id=NEW.id;
        IF export_status IS NULL OR export_status NOT IN ('resolving_item','awaiting_wallet','proof_verified','mint_queued','prepared') THEN
            RAISE EXCEPTION 'star gift externalization lock missing active TON export';
        END IF;
    ELSIF OLD.externalization_pending AND NOT NEW.externalization_pending THEN
        SELECT status INTO export_status FROM public.star_gift_ton_exports WHERE unique_gift_id=NEW.id;
        IF export_status IS NULL OR export_status NOT IN ('failed','confirmed','finalized') THEN
            RAISE EXCEPTION 'star gift externalization lock cannot be cleared in state %', COALESCE(export_status,'missing');
        END IF;
    ELSIF OLD.externalization_pending AND NEW.externalization_pending AND (
        NEW.owner_peer_type IS DISTINCT FROM OLD.owner_peer_type OR
        NEW.owner_peer_id IS DISTINCT FROM OLD.owner_peer_id OR
        NEW.owner_address IS DISTINCT FROM OLD.owner_address OR
        NEW.gift_address IS DISTINCT FROM OLD.gift_address OR
        NEW.burned IS DISTINCT FROM OLD.burned OR
        NEW.crafted IS DISTINCT FROM OLD.crafted OR
        NEW.model_attribute_id IS DISTINCT FROM OLD.model_attribute_id OR
        NEW.pattern_attribute_id IS DISTINCT FROM OLD.pattern_attribute_id OR
        NEW.backdrop_attribute_id IS DISTINCT FROM OLD.backdrop_attribute_id OR
        NEW.keep_original_details IS DISTINCT FROM OLD.keep_original_details OR
        NEW.last_sale_date IS DISTINCT FROM OLD.last_sale_date OR
        NEW.last_sale_currency IS DISTINCT FROM OLD.last_sale_currency OR
        NEW.last_sale_amount IS DISTINCT FROM OLD.last_sale_amount
    ) THEN
        RAISE EXCEPTION 'externalizing star gift lifecycle is locked';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER unique_star_gifts_externalization_guard
    BEFORE UPDATE ON public.unique_star_gifts
    FOR EACH ROW EXECUTE FUNCTION public.telesrv_guard_star_gift_externalization();

CREATE OR REPLACE FUNCTION public.telesrv_guard_star_gift_listing() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    gift_owner_type text;
    gift_owner_id bigint;
    gift_burned boolean;
    gift_externalizing boolean;
BEGIN
    SELECT owner_peer_type, owner_peer_id, burned, externalization_pending
      INTO gift_owner_type, gift_owner_id, gift_burned, gift_externalizing
      FROM public.unique_star_gifts WHERE id=NEW.unique_gift_id FOR SHARE;
    IF gift_burned OR gift_externalizing OR
       gift_owner_type IS DISTINCT FROM NEW.seller_peer_type OR gift_owner_id IS DISTINCT FROM NEW.seller_peer_id THEN
        RAISE EXCEPTION 'star gift listing owner/state mismatch';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.telesrv_guard_star_gift_offer_externalization() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    gift_externalizing boolean;
BEGIN
    IF NEW.status='pending' THEN
        SELECT externalization_pending INTO gift_externalizing
          FROM public.unique_star_gifts WHERE id=NEW.unique_gift_id FOR SHARE;
        IF gift_externalizing THEN
            RAISE EXCEPTION 'externalizing star gift cannot accept offers';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER star_gift_offer_externalization_guard
    BEFORE INSERT OR UPDATE ON public.star_gift_offers
    FOR EACH ROW EXECUTE FUNCTION public.telesrv_guard_star_gift_offer_externalization();
