-- Pin the collection-specific mint ABI and preserve every operator-approved
-- recovery of a quarantined export.

ALTER TABLE public.star_gift_ton_exports
    ADD COLUMN mint_abi text;
UPDATE public.star_gift_ton_exports SET mint_abi='basic-collection-v1' WHERE mint_abi IS NULL;
ALTER TABLE public.star_gift_ton_exports
    ALTER COLUMN mint_abi SET NOT NULL,
    ADD CONSTRAINT star_gift_ton_exports_mint_abi_check CHECK (mint_abi='basic-collection-v1');

ALTER TABLE public.star_gift_ton_admissions
    ADD COLUMN mint_abi text;
UPDATE public.star_gift_ton_admissions SET mint_abi='basic-collection-v1' WHERE mint_abi IS NULL;
ALTER TABLE public.star_gift_ton_admissions
    ALTER COLUMN mint_abi SET NOT NULL,
    ADD CONSTRAINT star_gift_ton_admissions_mint_abi_check CHECK (mint_abi='basic-collection-v1');

CREATE TABLE public.star_gift_ton_recoveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_id bigint NOT NULL REFERENCES public.star_gift_ton_exports(id) ON DELETE RESTRICT,
    job_id bigint NOT NULL REFERENCES public.star_gift_ton_jobs(id) ON DELETE RESTRICT,
    actor text NOT NULL,
    reason text NOT NULL,
    previous_export_status text NOT NULL,
    previous_job_status text NOT NULL,
    previous_job_kind text NOT NULL,
    previous_error text NOT NULL,
    recovered_at integer NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT star_gift_ton_recoveries_shape_check CHECK (
        length(actor) BETWEEN 1 AND 128 AND length(reason) BETWEEN 1 AND 500 AND
        previous_export_status='quarantined' AND previous_job_status='failed' AND
        previous_job_kind IN ('resolve_item','mint','confirm') AND
        recovered_at>0
    )
);

CREATE INDEX star_gift_ton_recoveries_export_idx
    ON public.star_gift_ton_recoveries(export_id, id DESC);
