-- Durable channel/supergroup delivery accelerator.
--
-- One immutable signal represents one channel PTS event/range.  Lanes are
-- keyed only by channel_id; audience expansion belongs to Egress/Edge and is
-- deliberately absent from this schema.
CREATE SEQUENCE public.channel_delivery_lease_fence_seq
    AS bigint
    MINVALUE 1
    MAXVALUE 9223372036854775807
    -- Edge rejects fences below the domain high-water mark. Backend-local
    -- sequence caches would make legitimate cross-connection claims reorder.
    CACHE 1
    NO CYCLE;

CREATE FUNCTION public.channel_delivery_valid_user_ids(ids bigint[])
RETURNS boolean
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT COALESCE(bool_and(id > 0), true)
       AND ids = COALESCE(array_agg(DISTINCT id ORDER BY id), '{}'::bigint[])
    FROM unnest(ids) AS id
$$;

CREATE TABLE public.channel_delivery_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id bigint NOT NULL REFERENCES public.channels(id) ON DELETE CASCADE,
    min_pts integer NOT NULL,
    max_pts integer NOT NULL,
    projection_kind varchar(64) NOT NULL,
    audience_kind varchar(32) NOT NULL,
    audience_user_ids bigint[] NOT NULL DEFAULT '{}'::bigint[],
    affected_user_ids bigint[] NOT NULL DEFAULT '{}'::bigint[],
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT channel_delivery_events_pts_check CHECK (
        min_pts > 0 AND max_pts >= min_pts
    ),
    CONSTRAINT channel_delivery_events_projection_check CHECK (
        length(projection_kind) > 0
    ),
    CONSTRAINT channel_delivery_events_audience_check CHECK (
        (audience_kind = 'members' AND cardinality(audience_user_ids) = 0)
        OR (audience_kind = 'message_box' AND cardinality(audience_user_ids) BETWEEN 1 AND 1000)
        OR (audience_kind = 'monoforum_admins' AND cardinality(audience_user_ids) BETWEEN 1 AND 1000)
    ),
    CONSTRAINT channel_delivery_events_audience_users_check CHECK (
        channel_delivery_valid_user_ids(audience_user_ids)
    ),
    CONSTRAINT channel_delivery_events_affected_users_check CHECK (
        cardinality(affected_user_ids) <= 1000
        AND channel_delivery_valid_user_ids(affected_user_ids)
    ),
    CONSTRAINT channel_delivery_events_channel_pts_key UNIQUE (channel_id, max_pts),
    CONSTRAINT channel_delivery_events_channel_range_key UNIQUE (channel_id, min_pts, max_pts),
    CONSTRAINT channel_delivery_events_channel_item_key UNIQUE (channel_id, id)
);

CREATE INDEX channel_delivery_events_successor_idx
    ON public.channel_delivery_events (channel_id, min_pts, id);

CREATE FUNCTION public.reject_channel_delivery_event_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'channel_delivery_events are immutable';
END;
$$;

CREATE TRIGGER channel_delivery_events_immutable
BEFORE UPDATE ON public.channel_delivery_events
FOR EACH ROW EXECUTE FUNCTION public.reject_channel_delivery_event_update();

CREATE TABLE public.channel_delivery_lanes (
    channel_id bigint PRIMARY KEY REFERENCES public.channels(id) ON DELETE CASCADE,
    head_item_id bigint NOT NULL,
    head_sequence integer NOT NULL,
    logical_shard smallint GENERATED ALWAYS AS
        (((channel_id % 256 + 256) % 256)::smallint) STORED,
    state varchar(16) NOT NULL DEFAULT 'ready',
    ready_at timestamptz NOT NULL DEFAULT now(),
    lease_fence bigint NOT NULL DEFAULT 0,
    lease_owner varchar(255),
    lease_until timestamptz,
    window_tail_item_id bigint,
    window_tail_sequence integer,
    retry_count integer NOT NULL DEFAULT 0,
    last_error text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT channel_delivery_lanes_head_sequence_check CHECK (head_sequence > 0),
    CONSTRAINT channel_delivery_lanes_lease_fence_check CHECK (lease_fence >= 0),
    CONSTRAINT channel_delivery_lanes_retry_count_check CHECK (retry_count >= 0),
    CONSTRAINT channel_delivery_lanes_state_check CHECK (state IN ('ready', 'leased')),
    CONSTRAINT channel_delivery_lanes_window_check CHECK (
        (window_tail_item_id IS NULL) = (window_tail_sequence IS NULL)
    ),
    CONSTRAINT channel_delivery_lanes_head_fkey
        FOREIGN KEY (channel_id, head_item_id)
        REFERENCES public.channel_delivery_events(channel_id, id)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX channel_delivery_lanes_claim_idx
    ON public.channel_delivery_lanes (logical_shard, ready_at, channel_id)
    WHERE state = 'ready';

CREATE INDEX channel_delivery_lanes_reclaim_idx
    ON public.channel_delivery_lanes (logical_shard, lease_until, channel_id)
    WHERE state = 'leased';

-- Attempts intentionally have no foreign key to channel_delivery_events: the
-- event is deleted after a terminal prefix is finalized while this row remains
-- as the positive AlreadyFinalized tombstone.
CREATE TABLE public.channel_delivery_attempts (
    item_id bigint NOT NULL,
    lease_fence bigint NOT NULL,
    channel_id bigint NOT NULL,
    min_pts integer NOT NULL,
    max_pts integer NOT NULL,
    attempt_no integer NOT NULL,
    window_ordinal integer NOT NULL,
    owner varchar(255) NOT NULL,
    issued_at timestamptz NOT NULL DEFAULT now(),
    lease_until timestamptz NOT NULL,
    command_not_after timestamptz NOT NULL,
    evidence_deadline timestamptz NOT NULL,
    targets_bound boolean NOT NULL DEFAULT false,
    target_count integer,
    delivery_source_instance_id varchar(255),
    empty_evidence_kind varchar(32),
    evidence_at timestamptz,
    resolution varchar(32) NOT NULL DEFAULT 'pending',
    resolution_error text,
    retry_at timestamptz,
    resolved_at timestamptz,
    finalized_at timestamptz,
    final_outcome varchar(32),
    PRIMARY KEY (item_id, lease_fence),
    CONSTRAINT channel_delivery_attempts_item_attempt_key UNIQUE (item_id, attempt_no),
    CONSTRAINT channel_delivery_attempts_pts_check CHECK (
        min_pts > 0 AND max_pts >= min_pts
    ),
    CONSTRAINT channel_delivery_attempts_fence_check CHECK (lease_fence > 0),
    CONSTRAINT channel_delivery_attempts_number_check CHECK (attempt_no > 0),
    CONSTRAINT channel_delivery_attempts_ordinal_check CHECK (window_ordinal >= 0),
    CONSTRAINT channel_delivery_attempts_target_count_check CHECK (
        (NOT targets_bound AND target_count IS NULL AND delivery_source_instance_id IS NULL)
        OR (targets_bound AND target_count IS NOT NULL AND target_count >= 0
            AND delivery_source_instance_id IS NOT NULL AND length(delivery_source_instance_id) > 0
        )
    ),
    CONSTRAINT channel_delivery_attempts_deadline_check CHECK (
        issued_at < command_not_after
        AND command_not_after < evidence_deadline
        AND evidence_deadline < lease_until
    ),
    CONSTRAINT channel_delivery_attempts_empty_evidence_check CHECK (
        empty_evidence_kind IS NULL
        OR (empty_evidence_kind = 'authoritative_no_targets'
            AND targets_bound AND target_count = 0)
    ),
    CONSTRAINT channel_delivery_attempts_resolution_check CHECK (
        resolution IN ('pending', 'confirmed', 'retry', 'terminal_resync')
    ),
    CONSTRAINT channel_delivery_attempts_resolution_time_check CHECK (
        (resolution = 'pending') = (resolved_at IS NULL)
        AND (resolution = 'confirmed') = (evidence_at IS NOT NULL)
        AND (resolution <> 'retry' OR retry_at IS NOT NULL)
    ),
    CONSTRAINT channel_delivery_attempts_finalized_check CHECK (
        (finalized_at IS NULL) = (final_outcome IS NULL)
        AND (
            final_outcome IS NULL OR final_outcome = 'superseded'
            OR (final_outcome = 'applied' AND resolution = 'confirmed')
            OR (final_outcome = 'scheduled_retry' AND resolution = 'retry')
            OR final_outcome = resolution
        )
    )
);

CREATE INDEX channel_delivery_attempts_stream_prefix_idx
    ON public.channel_delivery_attempts (channel_id, min_pts, max_pts, item_id, lease_fence);

CREATE INDEX channel_delivery_attempts_finalize_idx
    ON public.channel_delivery_attempts (channel_id, max_pts, item_id, lease_fence)
    WHERE finalized_at IS NULL
      AND resolution <> 'pending';

CREATE INDEX channel_delivery_attempts_evidence_deadline_idx
    ON public.channel_delivery_attempts (evidence_deadline, channel_id, item_id, lease_fence)
    WHERE resolution = 'pending' AND finalized_at IS NULL;

CREATE INDEX channel_delivery_attempts_tombstone_cleanup_idx
    ON public.channel_delivery_attempts (finalized_at, item_id, lease_fence)
    WHERE finalized_at IS NOT NULL;

CREATE TABLE public.channel_delivery_attempt_targets (
    item_id bigint NOT NULL,
    lease_fence bigint NOT NULL,
    target_instance_id varchar(255) NOT NULL,
    target_user_id bigint NOT NULL,
    batch_id bytea NOT NULL,
    command_id bytea NOT NULL,
    status varchar(32) NOT NULL DEFAULT 'pending',
    admitted_sessions integer NOT NULL DEFAULT 0,
    written_sessions integer NOT NULL DEFAULT 0,
    physical_first_server_msg_id bigint NOT NULL DEFAULT 0,
    client_ack_auth_key_id bytea,
    client_ack_session_id bigint,
    client_ack_server_msg_id bigint,
    evidence_at timestamptz,
    evidence_kind varchar(32),
    client_ack_at timestamptz,
    last_error text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (item_id, lease_fence, target_instance_id, target_user_id, batch_id, command_id),
    UNIQUE (item_id, lease_fence, target_instance_id, target_user_id),
    CONSTRAINT channel_delivery_attempt_targets_attempt_fkey
        FOREIGN KEY (item_id, lease_fence)
        REFERENCES public.channel_delivery_attempts(item_id, lease_fence)
        ON DELETE CASCADE,
    CONSTRAINT channel_delivery_attempt_targets_batch_id_check CHECK (octet_length(batch_id) = 16),
    CONSTRAINT channel_delivery_attempt_targets_command_id_check CHECK (octet_length(command_id) = 16),
    -- A channel command is addressed to an Edge/chunk. The Edge expands the
    -- immutable channel audience locally; it must never be duplicated per user.
    CONSTRAINT channel_delivery_attempt_targets_target_user_check CHECK (target_user_id = 0),
    CONSTRAINT channel_delivery_attempt_targets_auth_key_id_check CHECK (
        client_ack_auth_key_id IS NULL OR octet_length(client_ack_auth_key_id) = 8
    ),
    CONSTRAINT channel_delivery_attempt_targets_counts_check CHECK (
        admitted_sessions >= 0 AND written_sessions >= 0
        AND (
            (evidence_kind IS NULL AND admitted_sessions = 0 AND written_sessions = 0
             AND physical_first_server_msg_id = 0)
            OR (evidence_kind = 'edge_no_eligible' AND admitted_sessions = 0 AND written_sessions = 0
                AND physical_first_server_msg_id = 0)
            OR (evidence_kind = 'edge_written' AND admitted_sessions > 0
                AND written_sessions = admitted_sessions AND physical_first_server_msg_id > 0)
        )
    ),
    CONSTRAINT channel_delivery_attempt_targets_evidence_kind_check CHECK (
        evidence_kind IS NULL OR evidence_kind IN ('edge_written', 'edge_no_eligible')
    ),
    CONSTRAINT channel_delivery_attempt_targets_evidence_time_check CHECK (
        (evidence_kind IS NULL) = (evidence_at IS NULL)
    ),
    CONSTRAINT channel_delivery_attempt_targets_client_ack_check CHECK (
        (client_ack_at IS NULL AND client_ack_auth_key_id IS NULL
         AND client_ack_session_id IS NULL AND client_ack_server_msg_id IS NULL)
        OR
        (client_ack_at IS NOT NULL AND client_ack_auth_key_id IS NOT NULL
         AND client_ack_session_id IS NOT NULL AND client_ack_session_id <> 0
         AND client_ack_server_msg_id IS NOT NULL AND client_ack_server_msg_id > 0)
    ),
    CONSTRAINT channel_delivery_attempt_targets_status_check CHECK (
        status IN ('pending', 'admitted', 'written', 'no_eligible', 'indeterminate', 'rejected')
        AND (status = 'written') = (evidence_kind IS NOT DISTINCT FROM 'edge_written')
        AND (status = 'no_eligible') = (evidence_kind IS NOT DISTINCT FROM 'edge_no_eligible')
    )
);

CREATE INDEX channel_delivery_attempt_targets_batch_idx
    ON public.channel_delivery_attempt_targets (target_instance_id, target_user_id, batch_id, command_id);

CREATE FUNCTION public.reject_channel_delivery_attempt_target_identity_update()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'channel delivery target identity is immutable'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER channel_delivery_attempt_target_identity_immutable
BEFORE UPDATE OF item_id, lease_fence, target_instance_id, target_user_id, batch_id, command_id
ON public.channel_delivery_attempt_targets
FOR EACH ROW EXECUTE FUNCTION public.reject_channel_delivery_attempt_target_identity_update();

CREATE TRIGGER channel_delivery_attempt_target_membership_guard
BEFORE INSERT OR DELETE ON public.channel_delivery_attempt_targets
FOR EACH ROW EXECUTE FUNCTION public.guard_outbox_attempt_target_membership(
    'channel_delivery_attempts'
);

CREATE CONSTRAINT TRIGGER channel_delivery_attempt_target_count_from_attempt_bind
AFTER UPDATE OF targets_bound, target_count ON public.channel_delivery_attempts
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION public.validate_outbox_attempt_target_count(
    'channel_delivery_attempts', 'channel_delivery_attempt_targets'
);

CREATE FUNCTION public.channel_delivery_lanes_notify_ready()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE ready_shard smallint;
BEGIN
    FOR ready_shard IN
        SELECT DISTINCT logical_shard
        FROM new_rows
        WHERE state = 'ready' AND ready_at <= now()
    LOOP
        PERFORM pg_notify('telesrv_channel_delivery_ready', ready_shard::text);
    END LOOP;
    RETURN NULL;
END;
$$;

CREATE TRIGGER channel_delivery_lanes_insert_ready_notify
AFTER INSERT ON public.channel_delivery_lanes
REFERENCING NEW TABLE AS new_rows
FOR EACH STATEMENT EXECUTE FUNCTION public.channel_delivery_lanes_notify_ready();

CREATE TRIGGER channel_delivery_lanes_update_ready_notify
AFTER UPDATE ON public.channel_delivery_lanes
REFERENCING NEW TABLE AS new_rows
FOR EACH STATEMENT EXECUTE FUNCTION public.channel_delivery_lanes_notify_ready();

CREATE FUNCTION public.channel_delivery_attempts_notify_finalize()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE ready_shard smallint;
BEGIN
    FOR ready_shard IN
        SELECT DISTINCT l.logical_shard
        FROM new_rows a
        JOIN channel_delivery_lanes l ON l.channel_id = a.channel_id
        WHERE a.finalized_at IS NULL
          AND a.resolution <> 'pending'
    LOOP
        PERFORM pg_notify('telesrv_channel_delivery_finalize', ready_shard::text);
    END LOOP;
    RETURN NULL;
END;
$$;

CREATE TRIGGER channel_delivery_attempts_finalize_notify
AFTER UPDATE ON public.channel_delivery_attempts
REFERENCING NEW TABLE AS new_rows
FOR EACH STATEMENT EXECUTE FUNCTION public.channel_delivery_attempts_notify_finalize();

CREATE FUNCTION public.channel_delivery_attempts_notify_deadline()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE ready_shard smallint;
BEGIN
    FOR ready_shard IN
        SELECT DISTINCT l.logical_shard
        FROM new_rows a
        JOIN channel_delivery_lanes l ON l.channel_id = a.channel_id
        WHERE a.finalized_at IS NULL AND a.resolution = 'pending'
    LOOP
        PERFORM pg_notify('telesrv_channel_delivery_ready', ready_shard::text);
    END LOOP;
    RETURN NULL;
END;
$$;

CREATE TRIGGER channel_delivery_attempts_deadline_notify
AFTER INSERT ON public.channel_delivery_attempts
REFERENCING NEW TABLE AS new_rows
FOR EACH STATEMENT EXECUTE FUNCTION public.channel_delivery_attempts_notify_deadline();
