// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: internal/coreexec/coreexecpb/coreexec.proto

package coreexecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdmissionMode int32

const (
	AdmissionMode_ADMISSION_MODE_UNSPECIFIED AdmissionMode = 0
	AdmissionMode_ADMISSION_MODE_LAYER       AdmissionMode = 1
	AdmissionMode_ADMISSION_MODE_DEFAULT     AdmissionMode = 2
	AdmissionMode_ADMISSION_MODE_UNPROFILED  AdmissionMode = 3
)

// Enum value maps for AdmissionMode.
var (
	AdmissionMode_name = map[int32]string{
		0: "ADMISSION_MODE_UNSPECIFIED",
		1: "ADMISSION_MODE_LAYER",
		2: "ADMISSION_MODE_DEFAULT",
		3: "ADMISSION_MODE_UNPROFILED",
	}
	AdmissionMode_value = map[string]int32{
		"ADMISSION_MODE_UNSPECIFIED": 0,
		"ADMISSION_MODE_LAYER":       1,
		"ADMISSION_MODE_DEFAULT":     2,
		"ADMISSION_MODE_UNPROFILED":  3,
	}
)

func (x AdmissionMode) Enum() *AdmissionMode {
	p := new(AdmissionMode)
	*p = x
	return p
}

func (x AdmissionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdmissionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_coreexec_coreexecpb_coreexec_proto_enumTypes[0].Descriptor()
}

func (AdmissionMode) Type() protoreflect.EnumType {
	return &file_internal_coreexec_coreexecpb_coreexec_proto_enumTypes[0]
}

func (x AdmissionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdmissionMode.Descriptor instead.
func (AdmissionMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{0}
}

type UpdateStateCommitMode int32

const (
	UpdateStateCommitMode_UPDATE_STATE_COMMIT_MODE_UNSPECIFIED                UpdateStateCommitMode = 0
	UpdateStateCommitMode_UPDATE_STATE_COMMIT_DELIVERED_ONLY                  UpdateStateCommitMode = 1
	UpdateStateCommitMode_UPDATE_STATE_COMMIT_DELIVERED_AND_OBSERVED_BASELINE UpdateStateCommitMode = 2
)

// Enum value maps for UpdateStateCommitMode.
var (
	UpdateStateCommitMode_name = map[int32]string{
		0: "UPDATE_STATE_COMMIT_MODE_UNSPECIFIED",
		1: "UPDATE_STATE_COMMIT_DELIVERED_ONLY",
		2: "UPDATE_STATE_COMMIT_DELIVERED_AND_OBSERVED_BASELINE",
	}
	UpdateStateCommitMode_value = map[string]int32{
		"UPDATE_STATE_COMMIT_MODE_UNSPECIFIED":                0,
		"UPDATE_STATE_COMMIT_DELIVERED_ONLY":                  1,
		"UPDATE_STATE_COMMIT_DELIVERED_AND_OBSERVED_BASELINE": 2,
	}
)

func (x UpdateStateCommitMode) Enum() *UpdateStateCommitMode {
	p := new(UpdateStateCommitMode)
	*p = x
	return p
}

func (x UpdateStateCommitMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStateCommitMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_coreexec_coreexecpb_coreexec_proto_enumTypes[1].Descriptor()
}

func (UpdateStateCommitMode) Type() protoreflect.EnumType {
	return &file_internal_coreexec_coreexecpb_coreexec_proto_enumTypes[1]
}

func (x UpdateStateCommitMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateStateCommitMode.Descriptor instead.
func (UpdateStateCommitMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{1}
}

type CoreExecInfoRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CoreExecInfoRequest) Reset() {
	*x = CoreExecInfoRequest{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreExecInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreExecInfoRequest) ProtoMessage() {}

func (x *CoreExecInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreExecInfoRequest.ProtoReflect.Descriptor instead.
func (*CoreExecInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{0}
}

func (x *CoreExecInfoRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *CoreExecInfoRequest) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *CoreExecInfoRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type CoreExecInfoResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Implementation              string                 `protobuf:"bytes,4,opt,name=implementation,proto3" json:"implementation,omitempty"`
	Error                       string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	InstanceId                  string                 `protobuf:"bytes,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CoreExecInfoResponse) Reset() {
	*x = CoreExecInfoResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreExecInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreExecInfoResponse) ProtoMessage() {}

func (x *CoreExecInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreExecInfoResponse.ProtoReflect.Descriptor instead.
func (*CoreExecInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{1}
}

func (x *CoreExecInfoResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *CoreExecInfoResponse) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *CoreExecInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CoreExecInfoResponse) GetImplementation() string {
	if x != nil {
		return x.Implementation
	}
	return ""
}

func (x *CoreExecInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CoreExecInfoResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type Limits struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxWireBytes         int64                  `protobuf:"varint,1,opt,name=max_wire_bytes,json=maxWireBytes,proto3" json:"max_wire_bytes,omitempty"`
	MaxVectorElements    int64                  `protobuf:"varint,2,opt,name=max_vector_elements,json=maxVectorElements,proto3" json:"max_vector_elements,omitempty"`
	MaxAggregateElements int64                  `protobuf:"varint,3,opt,name=max_aggregate_elements,json=maxAggregateElements,proto3" json:"max_aggregate_elements,omitempty"`
	MaxDepth             int64                  `protobuf:"varint,4,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{2}
}

func (x *Limits) GetMaxWireBytes() int64 {
	if x != nil {
		return x.MaxWireBytes
	}
	return 0
}

func (x *Limits) GetMaxVectorElements() int64 {
	if x != nil {
		return x.MaxVectorElements
	}
	return 0
}

func (x *Limits) GetMaxAggregateElements() int64 {
	if x != nil {
		return x.MaxAggregateElements
	}
	return 0
}

func (x *Limits) GetMaxDepth() int64 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type ProfileMark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       int32                  `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Present       bool                   `protobuf:"varint,2,opt,name=present,proto3" json:"present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileMark) Reset() {
	*x = ProfileMark{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileMark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileMark) ProtoMessage() {}

func (x *ProfileMark) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileMark.ProtoReflect.Descriptor instead.
func (*ProfileMark) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileMark) GetProfile() int32 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *ProfileMark) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

type WireProof struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Profile          int32                  `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Method           uint64                 `protobuf:"varint,2,opt,name=method,proto3" json:"method,omitempty"`
	WireId           uint32                 `protobuf:"varint,3,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	WireSize         int64                  `protobuf:"varint,4,opt,name=wire_size,json=wireSize,proto3" json:"wire_size,omitempty"`
	WireDigest       string                 `protobuf:"bytes,5,opt,name=wire_digest,json=wireDigest,proto3" json:"wire_digest,omitempty"`
	WireInvariant    bool                   `protobuf:"varint,6,opt,name=wire_invariant,json=wireInvariant,proto3" json:"wire_invariant,omitempty"`
	EffectiveProfile *ProfileMark           `protobuf:"bytes,7,opt,name=effective_profile,json=effectiveProfile,proto3" json:"effective_profile,omitempty"`
	ProfileEvidence  *ProfileMark           `protobuf:"bytes,8,opt,name=profile_evidence,json=profileEvidence,proto3" json:"profile_evidence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WireProof) Reset() {
	*x = WireProof{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireProof) ProtoMessage() {}

func (x *WireProof) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireProof.ProtoReflect.Descriptor instead.
func (*WireProof) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{4}
}

func (x *WireProof) GetProfile() int32 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *WireProof) GetMethod() uint64 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *WireProof) GetWireId() uint32 {
	if x != nil {
		return x.WireId
	}
	return 0
}

func (x *WireProof) GetWireSize() int64 {
	if x != nil {
		return x.WireSize
	}
	return 0
}

func (x *WireProof) GetWireDigest() string {
	if x != nil {
		return x.WireDigest
	}
	return ""
}

func (x *WireProof) GetWireInvariant() bool {
	if x != nil {
		return x.WireInvariant
	}
	return false
}

func (x *WireProof) GetEffectiveProfile() *ProfileMark {
	if x != nil {
		return x.EffectiveProfile
	}
	return nil
}

func (x *WireProof) GetProfileEvidence() *ProfileMark {
	if x != nil {
		return x.ProfileEvidence
	}
	return nil
}

type RPCError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCError) Reset() {
	*x = RPCError{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCError) ProtoMessage() {}

func (x *RPCError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCError.ProtoReflect.Descriptor instead.
func (*RPCError) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{5}
}

func (x *RPCError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RPCError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IdentityHint struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	BusinessAuthKeyId           []byte                 `protobuf:"bytes,1,opt,name=business_auth_key_id,json=businessAuthKeyId,proto3" json:"business_auth_key_id,omitempty"`
	BusinessAuthKeyResolved     bool                   `protobuf:"varint,2,opt,name=business_auth_key_resolved,json=businessAuthKeyResolved,proto3" json:"business_auth_key_resolved,omitempty"`
	UserId                      int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserIdResolved              bool                   `protobuf:"varint,4,opt,name=user_id_resolved,json=userIdResolved,proto3" json:"user_id_resolved,omitempty"`
	RawAuthKeyExpiresAt         int32                  `protobuf:"varint,5,opt,name=raw_auth_key_expires_at,json=rawAuthKeyExpiresAt,proto3" json:"raw_auth_key_expires_at,omitempty"`
	RawAuthKeyExpiresAtResolved bool                   `protobuf:"varint,6,opt,name=raw_auth_key_expires_at_resolved,json=rawAuthKeyExpiresAtResolved,proto3" json:"raw_auth_key_expires_at_resolved,omitempty"`
	SessionUpdatesReady         bool                   `protobuf:"varint,7,opt,name=session_updates_ready,json=sessionUpdatesReady,proto3" json:"session_updates_ready,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *IdentityHint) Reset() {
	*x = IdentityHint{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityHint) ProtoMessage() {}

func (x *IdentityHint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityHint.ProtoReflect.Descriptor instead.
func (*IdentityHint) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{6}
}

func (x *IdentityHint) GetBusinessAuthKeyId() []byte {
	if x != nil {
		return x.BusinessAuthKeyId
	}
	return nil
}

func (x *IdentityHint) GetBusinessAuthKeyResolved() bool {
	if x != nil {
		return x.BusinessAuthKeyResolved
	}
	return false
}

func (x *IdentityHint) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IdentityHint) GetUserIdResolved() bool {
	if x != nil {
		return x.UserIdResolved
	}
	return false
}

func (x *IdentityHint) GetRawAuthKeyExpiresAt() int32 {
	if x != nil {
		return x.RawAuthKeyExpiresAt
	}
	return 0
}

func (x *IdentityHint) GetRawAuthKeyExpiresAtResolved() bool {
	if x != nil {
		return x.RawAuthKeyExpiresAtResolved
	}
	return false
}

func (x *IdentityHint) GetSessionUpdatesReady() bool {
	if x != nil {
		return x.SessionUpdatesReady
	}
	return false
}

type DispatchRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Mode                 AdmissionMode          `protobuf:"varint,1,opt,name=mode,proto3,enum=telesrv.coreexec.v1.AdmissionMode" json:"mode,omitempty"`
	Profile              int32                  `protobuf:"varint,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Limits               *Limits                `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	RequestWire          []byte                 `protobuf:"bytes,4,opt,name=request_wire,json=requestWire,proto3" json:"request_wire,omitempty"`
	Proof                *WireProof             `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	AuthKeyId            []byte                 `protobuf:"bytes,6,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	SessionId            int64                  `protobuf:"varint,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MsgId                int64                  `protobuf:"varint,8,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	AdmissionSeq         uint64                 `protobuf:"varint,9,opt,name=admission_seq,json=admissionSeq,proto3" json:"admission_seq,omitempty"`
	ProfileEvidenceFresh bool                   `protobuf:"varint,10,opt,name=profile_evidence_fresh,json=profileEvidenceFresh,proto3" json:"profile_evidence_fresh,omitempty"`
	IdentityHint         *IdentityHint          `protobuf:"bytes,11,opt,name=identity_hint,json=identityHint,proto3" json:"identity_hint,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{7}
}

func (x *DispatchRequest) GetMode() AdmissionMode {
	if x != nil {
		return x.Mode
	}
	return AdmissionMode_ADMISSION_MODE_UNSPECIFIED
}

func (x *DispatchRequest) GetProfile() int32 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *DispatchRequest) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *DispatchRequest) GetRequestWire() []byte {
	if x != nil {
		return x.RequestWire
	}
	return nil
}

func (x *DispatchRequest) GetProof() *WireProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *DispatchRequest) GetAuthKeyId() []byte {
	if x != nil {
		return x.AuthKeyId
	}
	return nil
}

func (x *DispatchRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *DispatchRequest) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *DispatchRequest) GetAdmissionSeq() uint64 {
	if x != nil {
		return x.AdmissionSeq
	}
	return 0
}

func (x *DispatchRequest) GetProfileEvidenceFresh() bool {
	if x != nil {
		return x.ProfileEvidenceFresh
	}
	return false
}

func (x *DispatchRequest) GetIdentityHint() *IdentityHint {
	if x != nil {
		return x.IdentityHint
	}
	return nil
}

type DispatchResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Method              string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	ResultWire          []byte                 `protobuf:"bytes,2,opt,name=result_wire,json=resultWire,proto3" json:"result_wire,omitempty"`
	WireInvariant       bool                   `protobuf:"varint,3,opt,name=wire_invariant,json=wireInvariant,proto3" json:"wire_invariant,omitempty"`
	RpcError            *RPCError              `protobuf:"bytes,4,opt,name=rpc_error,json=rpcError,proto3" json:"rpc_error,omitempty"`
	Error               string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	PostResponseActions []*PostResponseAction  `protobuf:"bytes,6,rep,name=post_response_actions,json=postResponseActions,proto3" json:"post_response_actions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{8}
}

func (x *DispatchResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *DispatchResponse) GetResultWire() []byte {
	if x != nil {
		return x.ResultWire
	}
	return nil
}

func (x *DispatchResponse) GetWireInvariant() bool {
	if x != nil {
		return x.WireInvariant
	}
	return false
}

func (x *DispatchResponse) GetRpcError() *RPCError {
	if x != nil {
		return x.RpcError
	}
	return nil
}

func (x *DispatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DispatchResponse) GetPostResponseActions() []*PostResponseAction {
	if x != nil {
		return x.PostResponseActions
	}
	return nil
}

type PostResponseAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*PostResponseAction_UpdatesDelivery
	//	*PostResponseAction_AccountAuthorizationTeardown
	Action        isPostResponseAction_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponseAction) Reset() {
	*x = PostResponseAction{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponseAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponseAction) ProtoMessage() {}

func (x *PostResponseAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponseAction.ProtoReflect.Descriptor instead.
func (*PostResponseAction) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{9}
}

func (x *PostResponseAction) GetAction() isPostResponseAction_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *PostResponseAction) GetUpdatesDelivery() *UpdatesDeliveryAction {
	if x != nil {
		if x, ok := x.Action.(*PostResponseAction_UpdatesDelivery); ok {
			return x.UpdatesDelivery
		}
	}
	return nil
}

func (x *PostResponseAction) GetAccountAuthorizationTeardown() *AccountAuthorizationTeardownAction {
	if x != nil {
		if x, ok := x.Action.(*PostResponseAction_AccountAuthorizationTeardown); ok {
			return x.AccountAuthorizationTeardown
		}
	}
	return nil
}

type isPostResponseAction_Action interface {
	isPostResponseAction_Action()
}

type PostResponseAction_UpdatesDelivery struct {
	UpdatesDelivery *UpdatesDeliveryAction `protobuf:"bytes,1,opt,name=updates_delivery,json=updatesDelivery,proto3,oneof"`
}

type PostResponseAction_AccountAuthorizationTeardown struct {
	AccountAuthorizationTeardown *AccountAuthorizationTeardownAction `protobuf:"bytes,2,opt,name=account_authorization_teardown,json=accountAuthorizationTeardown,proto3,oneof"`
}

func (*PostResponseAction_UpdatesDelivery) isPostResponseAction_Action() {}

func (*PostResponseAction_AccountAuthorizationTeardown) isPostResponseAction_Action() {}

type AccountAuthorizationTeardownAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     []byte                 `protobuf:"bytes,2,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountAuthorizationTeardownAction) Reset() {
	*x = AccountAuthorizationTeardownAction{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountAuthorizationTeardownAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAuthorizationTeardownAction) ProtoMessage() {}

func (x *AccountAuthorizationTeardownAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAuthorizationTeardownAction.ProtoReflect.Descriptor instead.
func (*AccountAuthorizationTeardownAction) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{10}
}

func (x *AccountAuthorizationTeardownAction) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AccountAuthorizationTeardownAction) GetAuthKeyId() []byte {
	if x != nil {
		return x.AuthKeyId
	}
	return nil
}

type UpdateState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pts           int32                  `protobuf:"varint,1,opt,name=pts,proto3" json:"pts,omitempty"`
	Qts           int32                  `protobuf:"varint,2,opt,name=qts,proto3" json:"qts,omitempty"`
	Date          int32                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Seq           int32                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateState) Reset() {
	*x = UpdateState{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateState) ProtoMessage() {}

func (x *UpdateState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateState.ProtoReflect.Descriptor instead.
func (*UpdateState) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateState) GetPts() int32 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *UpdateState) GetQts() int32 {
	if x != nil {
		return x.Qts
	}
	return 0
}

func (x *UpdateState) GetDate() int32 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *UpdateState) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type UpdatesDeliveryAction struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CommitCursor          bool                   `protobuf:"varint,1,opt,name=commit_cursor,json=commitCursor,proto3" json:"commit_cursor,omitempty"`
	CursorAuthKeyId       []byte                 `protobuf:"bytes,2,opt,name=cursor_auth_key_id,json=cursorAuthKeyId,proto3" json:"cursor_auth_key_id,omitempty"`
	CursorUserId          int64                  `protobuf:"varint,3,opt,name=cursor_user_id,json=cursorUserId,proto3" json:"cursor_user_id,omitempty"`
	CursorState           *UpdateState           `protobuf:"bytes,4,opt,name=cursor_state,json=cursorState,proto3" json:"cursor_state,omitempty"`
	CursorMode            UpdateStateCommitMode  `protobuf:"varint,5,opt,name=cursor_mode,json=cursorMode,proto3,enum=telesrv.coreexec.v1.UpdateStateCommitMode" json:"cursor_mode,omitempty"`
	MarkSecretDelivered   bool                   `protobuf:"varint,6,opt,name=mark_secret_delivered,json=markSecretDelivered,proto3" json:"mark_secret_delivered,omitempty"`
	SecretDeviceKey       int64                  `protobuf:"varint,7,opt,name=secret_device_key,json=secretDeviceKey,proto3" json:"secret_device_key,omitempty"`
	SecretEventIds        []int64                `protobuf:"varint,8,rep,packed,name=secret_event_ids,json=secretEventIds,proto3" json:"secret_event_ids,omitempty"`
	MarkSessionReady      bool                   `protobuf:"varint,9,opt,name=mark_session_ready,json=markSessionReady,proto3" json:"mark_session_ready,omitempty"`
	ReadyRawAuthKeyId     []byte                 `protobuf:"bytes,10,opt,name=ready_raw_auth_key_id,json=readyRawAuthKeyId,proto3" json:"ready_raw_auth_key_id,omitempty"`
	ReadySessionId        int64                  `protobuf:"varint,11,opt,name=ready_session_id,json=readySessionId,proto3" json:"ready_session_id,omitempty"`
	ReadyUserId           int64                  `protobuf:"varint,12,opt,name=ready_user_id,json=readyUserId,proto3" json:"ready_user_id,omitempty"`
	PublishBootstrap      bool                   `protobuf:"varint,13,opt,name=publish_bootstrap,json=publishBootstrap,proto3" json:"publish_bootstrap,omitempty"`
	BootstrapUserId       int64                  `protobuf:"varint,14,opt,name=bootstrap_user_id,json=bootstrapUserId,proto3" json:"bootstrap_user_id,omitempty"`
	ActivationToken       uint64                 `protobuf:"varint,15,opt,name=activation_token,json=activationToken,proto3" json:"activation_token,omitempty"`
	BootstrapAuthKeyId    []byte                 `protobuf:"bytes,16,opt,name=bootstrap_auth_key_id,json=bootstrapAuthKeyId,proto3" json:"bootstrap_auth_key_id,omitempty"`
	BootstrapSessionId    int64                  `protobuf:"varint,17,opt,name=bootstrap_session_id,json=bootstrapSessionId,proto3" json:"bootstrap_session_id,omitempty"`
	BootstrapProbeToken   uint64                 `protobuf:"varint,18,opt,name=bootstrap_probe_token,json=bootstrapProbeToken,proto3" json:"bootstrap_probe_token,omitempty"`
	BootstrapRawAuthKeyId []byte                 `protobuf:"bytes,19,opt,name=bootstrap_raw_auth_key_id,json=bootstrapRawAuthKeyId,proto3" json:"bootstrap_raw_auth_key_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdatesDeliveryAction) Reset() {
	*x = UpdatesDeliveryAction{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatesDeliveryAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatesDeliveryAction) ProtoMessage() {}

func (x *UpdatesDeliveryAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatesDeliveryAction.ProtoReflect.Descriptor instead.
func (*UpdatesDeliveryAction) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatesDeliveryAction) GetCommitCursor() bool {
	if x != nil {
		return x.CommitCursor
	}
	return false
}

func (x *UpdatesDeliveryAction) GetCursorAuthKeyId() []byte {
	if x != nil {
		return x.CursorAuthKeyId
	}
	return nil
}

func (x *UpdatesDeliveryAction) GetCursorUserId() int64 {
	if x != nil {
		return x.CursorUserId
	}
	return 0
}

func (x *UpdatesDeliveryAction) GetCursorState() *UpdateState {
	if x != nil {
		return x.CursorState
	}
	return nil
}

func (x *UpdatesDeliveryAction) GetCursorMode() UpdateStateCommitMode {
	if x != nil {
		return x.CursorMode
	}
	return UpdateStateCommitMode_UPDATE_STATE_COMMIT_MODE_UNSPECIFIED
}

func (x *UpdatesDeliveryAction) GetMarkSecretDelivered() bool {
	if x != nil {
		return x.MarkSecretDelivered
	}
	return false
}

func (x *UpdatesDeliveryAction) GetSecretDeviceKey() int64 {
	if x != nil {
		return x.SecretDeviceKey
	}
	return 0
}

func (x *UpdatesDeliveryAction) GetSecretEventIds() []int64 {
	if x != nil {
		return x.SecretEventIds
	}
	return nil
}

func (x *UpdatesDeliveryAction) GetMarkSessionReady() bool {
	if x != nil {
		return x.MarkSessionReady
	}
	return false
}

func (x *UpdatesDeliveryAction) GetReadyRawAuthKeyId() []byte {
	if x != nil {
		return x.ReadyRawAuthKeyId
	}
	return nil
}

func (x *UpdatesDeliveryAction) GetReadySessionId() int64 {
	if x != nil {
		return x.ReadySessionId
	}
	return 0
}

func (x *UpdatesDeliveryAction) GetReadyUserId() int64 {
	if x != nil {
		return x.ReadyUserId
	}
	return 0
}

func (x *UpdatesDeliveryAction) GetPublishBootstrap() bool {
	if x != nil {
		return x.PublishBootstrap
	}
	return false
}

func (x *UpdatesDeliveryAction) GetBootstrapUserId() int64 {
	if x != nil {
		return x.BootstrapUserId
	}
	return 0
}

func (x *UpdatesDeliveryAction) GetActivationToken() uint64 {
	if x != nil {
		return x.ActivationToken
	}
	return 0
}

func (x *UpdatesDeliveryAction) GetBootstrapAuthKeyId() []byte {
	if x != nil {
		return x.BootstrapAuthKeyId
	}
	return nil
}

func (x *UpdatesDeliveryAction) GetBootstrapSessionId() int64 {
	if x != nil {
		return x.BootstrapSessionId
	}
	return 0
}

func (x *UpdatesDeliveryAction) GetBootstrapProbeToken() uint64 {
	if x != nil {
		return x.BootstrapProbeToken
	}
	return 0
}

func (x *UpdatesDeliveryAction) GetBootstrapRawAuthKeyId() []byte {
	if x != nil {
		return x.BootstrapRawAuthKeyId
	}
	return nil
}

type PrepareReplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareReplayResponse) Reset() {
	*x = PrepareReplayResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareReplayResponse) ProtoMessage() {}

func (x *PrepareReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareReplayResponse.ProtoReflect.Descriptor instead.
func (*PrepareReplayResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{13}
}

func (x *PrepareReplayResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PrepareReplayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommitReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitReplayRequest) Reset() {
	*x = CommitReplayRequest{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReplayRequest) ProtoMessage() {}

func (x *CommitReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReplayRequest.ProtoReflect.Descriptor instead.
func (*CommitReplayRequest) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{14}
}

func (x *CommitReplayRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CommitReplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitReplayResponse) Reset() {
	*x = CommitReplayResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReplayResponse) ProtoMessage() {}

func (x *CommitReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReplayResponse.ProtoReflect.Descriptor instead.
func (*CommitReplayResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{15}
}

func (x *CommitReplayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommitPostResponseActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*PostResponseAction  `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPostResponseActionsRequest) Reset() {
	*x = CommitPostResponseActionsRequest{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPostResponseActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPostResponseActionsRequest) ProtoMessage() {}

func (x *CommitPostResponseActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPostResponseActionsRequest.ProtoReflect.Descriptor instead.
func (*CommitPostResponseActionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{16}
}

func (x *CommitPostResponseActionsRequest) GetActions() []*PostResponseAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type CommitPostResponseActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPostResponseActionsResponse) Reset() {
	*x = CommitPostResponseActionsResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPostResponseActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPostResponseActionsResponse) ProtoMessage() {}

func (x *CommitPostResponseActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPostResponseActionsResponse.ProtoReflect.Descriptor instead.
func (*CommitPostResponseActionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{17}
}

func (x *CommitPostResponseActionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SessionOfflineEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RawAuthKeyId   []byte                 `protobuf:"bytes,1,opt,name=raw_auth_key_id,json=rawAuthKeyId,proto3" json:"raw_auth_key_id,omitempty"`
	SessionId      int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastForUser    bool                   `protobuf:"varint,4,opt,name=last_for_user,json=lastForUser,proto3" json:"last_for_user,omitempty"`
	DisconnectedAt int32                  `protobuf:"varint,5,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionOfflineEvent) Reset() {
	*x = SessionOfflineEvent{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOfflineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOfflineEvent) ProtoMessage() {}

func (x *SessionOfflineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOfflineEvent.ProtoReflect.Descriptor instead.
func (*SessionOfflineEvent) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{18}
}

func (x *SessionOfflineEvent) GetRawAuthKeyId() []byte {
	if x != nil {
		return x.RawAuthKeyId
	}
	return nil
}

func (x *SessionOfflineEvent) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SessionOfflineEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SessionOfflineEvent) GetLastForUser() bool {
	if x != nil {
		return x.LastForUser
	}
	return false
}

func (x *SessionOfflineEvent) GetDisconnectedAt() int32 {
	if x != nil {
		return x.DisconnectedAt
	}
	return 0
}

type SessionOfflineBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*SessionOfflineEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOfflineBatchRequest) Reset() {
	*x = SessionOfflineBatchRequest{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOfflineBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOfflineBatchRequest) ProtoMessage() {}

func (x *SessionOfflineBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOfflineBatchRequest.ProtoReflect.Descriptor instead.
func (*SessionOfflineBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{19}
}

func (x *SessionOfflineBatchRequest) GetEvents() []*SessionOfflineEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type AuthKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawAuthKeyId  []byte                 `protobuf:"bytes,1,opt,name=raw_auth_key_id,json=rawAuthKeyId,proto3" json:"raw_auth_key_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Layer         int32                  `protobuf:"varint,3,opt,name=layer,proto3" json:"layer,omitempty"`
	MsgId         int64                  `protobuf:"varint,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthKeyRequest) Reset() {
	*x = AuthKeyRequest{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthKeyRequest) ProtoMessage() {}

func (x *AuthKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthKeyRequest.ProtoReflect.Descriptor instead.
func (*AuthKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{20}
}

func (x *AuthKeyRequest) GetRawAuthKeyId() []byte {
	if x != nil {
		return x.RawAuthKeyId
	}
	return nil
}

func (x *AuthKeyRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *AuthKeyRequest) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *AuthKeyRequest) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *AuthKeyRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type AuthKeyRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AuthKeyId          []byte                 `protobuf:"bytes,1,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	Value              []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ServerSalt         int64                  `protobuf:"varint,3,opt,name=server_salt,json=serverSalt,proto3" json:"server_salt,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt          int32                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Layer              int32                  `protobuf:"varint,6,opt,name=layer,proto3" json:"layer,omitempty"`
	LayerObservationId int64                  `protobuf:"varint,7,opt,name=layer_observation_id,json=layerObservationId,proto3" json:"layer_observation_id,omitempty"`
	DeviceModel        string                 `protobuf:"bytes,8,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	Platform           string                 `protobuf:"bytes,9,opt,name=platform,proto3" json:"platform,omitempty"`
	SystemVersion      string                 `protobuf:"bytes,10,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	ApiId              int32                  `protobuf:"varint,11,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
	AppVersion         string                 `protobuf:"bytes,12,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthKeyRecord) Reset() {
	*x = AuthKeyRecord{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthKeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthKeyRecord) ProtoMessage() {}

func (x *AuthKeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthKeyRecord.ProtoReflect.Descriptor instead.
func (*AuthKeyRecord) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{21}
}

func (x *AuthKeyRecord) GetAuthKeyId() []byte {
	if x != nil {
		return x.AuthKeyId
	}
	return nil
}

func (x *AuthKeyRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AuthKeyRecord) GetServerSalt() int64 {
	if x != nil {
		return x.ServerSalt
	}
	return 0
}

func (x *AuthKeyRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AuthKeyRecord) GetExpiresAt() int32 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AuthKeyRecord) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *AuthKeyRecord) GetLayerObservationId() int64 {
	if x != nil {
		return x.LayerObservationId
	}
	return 0
}

func (x *AuthKeyRecord) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *AuthKeyRecord) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AuthKeyRecord) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

func (x *AuthKeyRecord) GetApiId() int32 {
	if x != nil {
		return x.ApiId
	}
	return 0
}

func (x *AuthKeyRecord) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type GetAuthKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthKey       *AuthKeyRecord         `protobuf:"bytes,1,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthKeyResponse) Reset() {
	*x = GetAuthKeyResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthKeyResponse) ProtoMessage() {}

func (x *GetAuthKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAuthKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{22}
}

func (x *GetAuthKeyResponse) GetAuthKey() *AuthKeyRecord {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

func (x *GetAuthKeyResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetAuthKeyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuthKeyClientInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthKeyId     []byte                 `protobuf:"bytes,1,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	Layer         int32                  `protobuf:"varint,2,opt,name=layer,proto3" json:"layer,omitempty"`
	DeviceModel   string                 `protobuf:"bytes,3,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	SystemVersion string                 `protobuf:"bytes,5,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	ApiId         int32                  `protobuf:"varint,6,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
	AppVersion    string                 `protobuf:"bytes,7,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthKeyClientInfoRequest) Reset() {
	*x = AuthKeyClientInfoRequest{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthKeyClientInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthKeyClientInfoRequest) ProtoMessage() {}

func (x *AuthKeyClientInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthKeyClientInfoRequest.ProtoReflect.Descriptor instead.
func (*AuthKeyClientInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{23}
}

func (x *AuthKeyClientInfoRequest) GetAuthKeyId() []byte {
	if x != nil {
		return x.AuthKeyId
	}
	return nil
}

func (x *AuthKeyClientInfoRequest) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *AuthKeyClientInfoRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *AuthKeyClientInfoRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AuthKeyClientInfoRequest) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

func (x *AuthKeyClientInfoRequest) GetApiId() int32 {
	if x != nil {
		return x.ApiId
	}
	return 0
}

func (x *AuthKeyClientInfoRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type PublishLayerEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawAuthKeyId  []byte                 `protobuf:"bytes,1,opt,name=raw_auth_key_id,json=rawAuthKeyId,proto3" json:"raw_auth_key_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MsgId         int64                  `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	AdmissionSeq  uint64                 `protobuf:"varint,4,opt,name=admission_seq,json=admissionSeq,proto3" json:"admission_seq,omitempty"`
	SafeFloor     uint64                 `protobuf:"varint,5,opt,name=safe_floor,json=safeFloor,proto3" json:"safe_floor,omitempty"`
	Layer         int32                  `protobuf:"varint,6,opt,name=layer,proto3" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishLayerEvidenceRequest) Reset() {
	*x = PublishLayerEvidenceRequest{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishLayerEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishLayerEvidenceRequest) ProtoMessage() {}

func (x *PublishLayerEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishLayerEvidenceRequest.ProtoReflect.Descriptor instead.
func (*PublishLayerEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{24}
}

func (x *PublishLayerEvidenceRequest) GetRawAuthKeyId() []byte {
	if x != nil {
		return x.RawAuthKeyId
	}
	return nil
}

func (x *PublishLayerEvidenceRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *PublishLayerEvidenceRequest) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PublishLayerEvidenceRequest) GetAdmissionSeq() uint64 {
	if x != nil {
		return x.AdmissionSeq
	}
	return 0
}

func (x *PublishLayerEvidenceRequest) GetSafeFloor() uint64 {
	if x != nil {
		return x.SafeFloor
	}
	return 0
}

func (x *PublishLayerEvidenceRequest) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

type ResolveSessionLayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         int32                  `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`
	MsgId         int64                  `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSessionLayerResponse) Reset() {
	*x = ResolveSessionLayerResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSessionLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSessionLayerResponse) ProtoMessage() {}

func (x *ResolveSessionLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSessionLayerResponse.ProtoReflect.Descriptor instead.
func (*ResolveSessionLayerResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{25}
}

func (x *ResolveSessionLayerResponse) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *ResolveSessionLayerResponse) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ResolveSessionLayerResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolveSessionLayerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResolveInheritedLayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         int32                  `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveInheritedLayerResponse) Reset() {
	*x = ResolveInheritedLayerResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveInheritedLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveInheritedLayerResponse) ProtoMessage() {}

func (x *ResolveInheritedLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveInheritedLayerResponse.ProtoReflect.Descriptor instead.
func (*ResolveInheritedLayerResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{26}
}

func (x *ResolveInheritedLayerResponse) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *ResolveInheritedLayerResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolveInheritedLayerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdvanceSessionLayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentLayer  int32                  `protobuf:"varint,1,opt,name=current_layer,json=currentLayer,proto3" json:"current_layer,omitempty"`
	CurrentMsgId  int64                  `protobuf:"varint,2,opt,name=current_msg_id,json=currentMsgId,proto3" json:"current_msg_id,omitempty"`
	PublishShared bool                   `protobuf:"varint,3,opt,name=publish_shared,json=publishShared,proto3" json:"publish_shared,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvanceSessionLayerResponse) Reset() {
	*x = AdvanceSessionLayerResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceSessionLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceSessionLayerResponse) ProtoMessage() {}

func (x *AdvanceSessionLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceSessionLayerResponse.ProtoReflect.Descriptor instead.
func (*AdvanceSessionLayerResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{27}
}

func (x *AdvanceSessionLayerResponse) GetCurrentLayer() int32 {
	if x != nil {
		return x.CurrentLayer
	}
	return 0
}

func (x *AdvanceSessionLayerResponse) GetCurrentMsgId() int64 {
	if x != nil {
		return x.CurrentMsgId
	}
	return 0
}

func (x *AdvanceSessionLayerResponse) GetPublishShared() bool {
	if x != nil {
		return x.PublishShared
	}
	return false
}

func (x *AdvanceSessionLayerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteSessionLayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionLayerResponse) Reset() {
	*x = DeleteSessionLayerResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionLayerResponse) ProtoMessage() {}

func (x *DeleteSessionLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionLayerResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionLayerResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteSessionLayerResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *DeleteSessionLayerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ObserveInitConnectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthKeyId      []byte                 `protobuf:"bytes,1,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	SessionId      int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Layer          int32                  `protobuf:"varint,3,opt,name=layer,proto3" json:"layer,omitempty"`
	ApiId          int32                  `protobuf:"varint,4,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
	DeviceModel    string                 `protobuf:"bytes,5,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	SystemVersion  string                 `protobuf:"bytes,6,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	AppVersion     string                 `protobuf:"bytes,7,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	SystemLangCode string                 `protobuf:"bytes,8,opt,name=system_lang_code,json=systemLangCode,proto3" json:"system_lang_code,omitempty"`
	LangPack       string                 `protobuf:"bytes,9,opt,name=lang_pack,json=langPack,proto3" json:"lang_pack,omitempty"`
	LangCode       string                 `protobuf:"bytes,10,opt,name=lang_code,json=langCode,proto3" json:"lang_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ObserveInitConnectionRequest) Reset() {
	*x = ObserveInitConnectionRequest{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveInitConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveInitConnectionRequest) ProtoMessage() {}

func (x *ObserveInitConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveInitConnectionRequest.ProtoReflect.Descriptor instead.
func (*ObserveInitConnectionRequest) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{29}
}

func (x *ObserveInitConnectionRequest) GetAuthKeyId() []byte {
	if x != nil {
		return x.AuthKeyId
	}
	return nil
}

func (x *ObserveInitConnectionRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *ObserveInitConnectionRequest) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *ObserveInitConnectionRequest) GetApiId() int32 {
	if x != nil {
		return x.ApiId
	}
	return 0
}

func (x *ObserveInitConnectionRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *ObserveInitConnectionRequest) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

func (x *ObserveInitConnectionRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *ObserveInitConnectionRequest) GetSystemLangCode() string {
	if x != nil {
		return x.SystemLangCode
	}
	return ""
}

func (x *ObserveInitConnectionRequest) GetLangPack() string {
	if x != nil {
		return x.LangPack
	}
	return ""
}

func (x *ObserveInitConnectionRequest) GetLangCode() string {
	if x != nil {
		return x.LangCode
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP(), []int{30}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_coreexec_coreexecpb_coreexec_proto protoreflect.FileDescriptor

const file_internal_coreexec_coreexecpb_coreexec_proto_rawDesc = "" +
	"\n" +
	"+internal/coreexec/coreexecpb/coreexec.proto\x12\x13telesrv.coreexec.v1\"\xa9\x01\n" +
	"\x13CoreExecInfoRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x89\x02\n" +
	"\x14CoreExecInfoResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12&\n" +
	"\x0eimplementation\x18\x04 \x01(\tR\x0eimplementation\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\tR\n" +
	"instanceId\"\xb1\x01\n" +
	"\x06Limits\x12$\n" +
	"\x0emax_wire_bytes\x18\x01 \x01(\x03R\fmaxWireBytes\x12.\n" +
	"\x13max_vector_elements\x18\x02 \x01(\x03R\x11maxVectorElements\x124\n" +
	"\x16max_aggregate_elements\x18\x03 \x01(\x03R\x14maxAggregateElements\x12\x1b\n" +
	"\tmax_depth\x18\x04 \x01(\x03R\bmaxDepth\"A\n" +
	"\vProfileMark\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x05R\aprofile\x12\x18\n" +
	"\apresent\x18\x02 \x01(\bR\apresent\"\xd7\x02\n" +
	"\tWireProof\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x05R\aprofile\x12\x16\n" +
	"\x06method\x18\x02 \x01(\x04R\x06method\x12\x17\n" +
	"\awire_id\x18\x03 \x01(\rR\x06wireId\x12\x1b\n" +
	"\twire_size\x18\x04 \x01(\x03R\bwireSize\x12\x1f\n" +
	"\vwire_digest\x18\x05 \x01(\tR\n" +
	"wireDigest\x12%\n" +
	"\x0ewire_invariant\x18\x06 \x01(\bR\rwireInvariant\x12M\n" +
	"\x11effective_profile\x18\a \x01(\v2 .telesrv.coreexec.v1.ProfileMarkR\x10effectiveProfile\x12K\n" +
	"\x10profile_evidence\x18\b \x01(\v2 .telesrv.coreexec.v1.ProfileMarkR\x0fprofileEvidence\"8\n" +
	"\bRPCError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf0\x02\n" +
	"\fIdentityHint\x12/\n" +
	"\x14business_auth_key_id\x18\x01 \x01(\fR\x11businessAuthKeyId\x12;\n" +
	"\x1abusiness_auth_key_resolved\x18\x02 \x01(\bR\x17businessAuthKeyResolved\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12(\n" +
	"\x10user_id_resolved\x18\x04 \x01(\bR\x0euserIdResolved\x124\n" +
	"\x17raw_auth_key_expires_at\x18\x05 \x01(\x05R\x13rawAuthKeyExpiresAt\x12E\n" +
	" raw_auth_key_expires_at_resolved\x18\x06 \x01(\bR\x1brawAuthKeyExpiresAtResolved\x122\n" +
	"\x15session_updates_ready\x18\a \x01(\bR\x13sessionUpdatesReady\"\xea\x03\n" +
	"\x0fDispatchRequest\x126\n" +
	"\x04mode\x18\x01 \x01(\x0e2\".telesrv.coreexec.v1.AdmissionModeR\x04mode\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\x05R\aprofile\x123\n" +
	"\x06limits\x18\x03 \x01(\v2\x1b.telesrv.coreexec.v1.LimitsR\x06limits\x12!\n" +
	"\frequest_wire\x18\x04 \x01(\fR\vrequestWire\x124\n" +
	"\x05proof\x18\x05 \x01(\v2\x1e.telesrv.coreexec.v1.WireProofR\x05proof\x12\x1e\n" +
	"\vauth_key_id\x18\x06 \x01(\fR\tauthKeyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\x03R\tsessionId\x12\x15\n" +
	"\x06msg_id\x18\b \x01(\x03R\x05msgId\x12#\n" +
	"\radmission_seq\x18\t \x01(\x04R\fadmissionSeq\x124\n" +
	"\x16profile_evidence_fresh\x18\n" +
	" \x01(\bR\x14profileEvidenceFresh\x12F\n" +
	"\ridentity_hint\x18\v \x01(\v2!.telesrv.coreexec.v1.IdentityHintR\fidentityHint\"\xa1\x02\n" +
	"\x10DispatchResponse\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1f\n" +
	"\vresult_wire\x18\x02 \x01(\fR\n" +
	"resultWire\x12%\n" +
	"\x0ewire_invariant\x18\x03 \x01(\bR\rwireInvariant\x12:\n" +
	"\trpc_error\x18\x04 \x01(\v2\x1d.telesrv.coreexec.v1.RPCErrorR\brpcError\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12[\n" +
	"\x15post_response_actions\x18\x06 \x03(\v2'.telesrv.coreexec.v1.PostResponseActionR\x13postResponseActions\"\xf8\x01\n" +
	"\x12PostResponseAction\x12W\n" +
	"\x10updates_delivery\x18\x01 \x01(\v2*.telesrv.coreexec.v1.UpdatesDeliveryActionH\x00R\x0fupdatesDelivery\x12\x7f\n" +
	"\x1eaccount_authorization_teardown\x18\x02 \x01(\v27.telesrv.coreexec.v1.AccountAuthorizationTeardownActionH\x00R\x1caccountAuthorizationTeardownB\b\n" +
	"\x06action\"]\n" +
	"\"AccountAuthorizationTeardownAction\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x02 \x01(\fR\tauthKeyId\"W\n" +
	"\vUpdateState\x12\x10\n" +
	"\x03pts\x18\x01 \x01(\x05R\x03pts\x12\x10\n" +
	"\x03qts\x18\x02 \x01(\x05R\x03qts\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x05R\x04date\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x05R\x03seq\"\xb0\a\n" +
	"\x15UpdatesDeliveryAction\x12#\n" +
	"\rcommit_cursor\x18\x01 \x01(\bR\fcommitCursor\x12+\n" +
	"\x12cursor_auth_key_id\x18\x02 \x01(\fR\x0fcursorAuthKeyId\x12$\n" +
	"\x0ecursor_user_id\x18\x03 \x01(\x03R\fcursorUserId\x12C\n" +
	"\fcursor_state\x18\x04 \x01(\v2 .telesrv.coreexec.v1.UpdateStateR\vcursorState\x12K\n" +
	"\vcursor_mode\x18\x05 \x01(\x0e2*.telesrv.coreexec.v1.UpdateStateCommitModeR\n" +
	"cursorMode\x122\n" +
	"\x15mark_secret_delivered\x18\x06 \x01(\bR\x13markSecretDelivered\x12*\n" +
	"\x11secret_device_key\x18\a \x01(\x03R\x0fsecretDeviceKey\x12(\n" +
	"\x10secret_event_ids\x18\b \x03(\x03R\x0esecretEventIds\x12,\n" +
	"\x12mark_session_ready\x18\t \x01(\bR\x10markSessionReady\x120\n" +
	"\x15ready_raw_auth_key_id\x18\n" +
	" \x01(\fR\x11readyRawAuthKeyId\x12(\n" +
	"\x10ready_session_id\x18\v \x01(\x03R\x0ereadySessionId\x12\"\n" +
	"\rready_user_id\x18\f \x01(\x03R\vreadyUserId\x12+\n" +
	"\x11publish_bootstrap\x18\r \x01(\bR\x10publishBootstrap\x12*\n" +
	"\x11bootstrap_user_id\x18\x0e \x01(\x03R\x0fbootstrapUserId\x12)\n" +
	"\x10activation_token\x18\x0f \x01(\x04R\x0factivationToken\x121\n" +
	"\x15bootstrap_auth_key_id\x18\x10 \x01(\fR\x12bootstrapAuthKeyId\x120\n" +
	"\x14bootstrap_session_id\x18\x11 \x01(\x03R\x12bootstrapSessionId\x122\n" +
	"\x15bootstrap_probe_token\x18\x12 \x01(\x04R\x13bootstrapProbeToken\x128\n" +
	"\x19bootstrap_raw_auth_key_id\x18\x13 \x01(\fR\x15bootstrapRawAuthKeyId\"C\n" +
	"\x15PrepareReplayResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x13CommitReplayRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\",\n" +
	"\x14CommitReplayResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"e\n" +
	" CommitPostResponseActionsRequest\x12A\n" +
	"\aactions\x18\x01 \x03(\v2'.telesrv.coreexec.v1.PostResponseActionR\aactions\"9\n" +
	"!CommitPostResponseActionsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xc1\x01\n" +
	"\x13SessionOfflineEvent\x12%\n" +
	"\x0fraw_auth_key_id\x18\x01 \x01(\fR\frawAuthKeyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\"\n" +
	"\rlast_for_user\x18\x04 \x01(\bR\vlastForUser\x12'\n" +
	"\x0fdisconnected_at\x18\x05 \x01(\x05R\x0edisconnectedAt\"^\n" +
	"\x1aSessionOfflineBatchRequest\x12@\n" +
	"\x06events\x18\x01 \x03(\v2(.telesrv.coreexec.v1.SessionOfflineEventR\x06events\"\xa0\x01\n" +
	"\x0eAuthKeyRequest\x12%\n" +
	"\x0fraw_auth_key_id\x18\x01 \x01(\fR\frawAuthKeyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x14\n" +
	"\x05layer\x18\x03 \x01(\x05R\x05layer\x12\x15\n" +
	"\x06msg_id\x18\x04 \x01(\x03R\x05msgId\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\tR\bsourceId\"\x8a\x03\n" +
	"\rAuthKeyRecord\x12\x1e\n" +
	"\vauth_key_id\x18\x01 \x01(\fR\tauthKeyId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vserver_salt\x18\x03 \x01(\x03R\n" +
	"serverSalt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x05R\texpiresAt\x12\x14\n" +
	"\x05layer\x18\x06 \x01(\x05R\x05layer\x120\n" +
	"\x14layer_observation_id\x18\a \x01(\x03R\x12layerObservationId\x12!\n" +
	"\fdevice_model\x18\b \x01(\tR\vdeviceModel\x12\x1a\n" +
	"\bplatform\x18\t \x01(\tR\bplatform\x12%\n" +
	"\x0esystem_version\x18\n" +
	" \x01(\tR\rsystemVersion\x12\x15\n" +
	"\x06api_id\x18\v \x01(\x05R\x05apiId\x12\x1f\n" +
	"\vapp_version\x18\f \x01(\tR\n" +
	"appVersion\"\x7f\n" +
	"\x12GetAuthKeyResponse\x12=\n" +
	"\bauth_key\x18\x01 \x01(\v2\".telesrv.coreexec.v1.AuthKeyRecordR\aauthKey\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xee\x01\n" +
	"\x18AuthKeyClientInfoRequest\x12\x1e\n" +
	"\vauth_key_id\x18\x01 \x01(\fR\tauthKeyId\x12\x14\n" +
	"\x05layer\x18\x02 \x01(\x05R\x05layer\x12!\n" +
	"\fdevice_model\x18\x03 \x01(\tR\vdeviceModel\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12%\n" +
	"\x0esystem_version\x18\x05 \x01(\tR\rsystemVersion\x12\x15\n" +
	"\x06api_id\x18\x06 \x01(\x05R\x05apiId\x12\x1f\n" +
	"\vapp_version\x18\a \x01(\tR\n" +
	"appVersion\"\xd4\x01\n" +
	"\x1bPublishLayerEvidenceRequest\x12%\n" +
	"\x0fraw_auth_key_id\x18\x01 \x01(\fR\frawAuthKeyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x03R\x05msgId\x12#\n" +
	"\radmission_seq\x18\x04 \x01(\x04R\fadmissionSeq\x12\x1d\n" +
	"\n" +
	"safe_floor\x18\x05 \x01(\x04R\tsafeFloor\x12\x14\n" +
	"\x05layer\x18\x06 \x01(\x05R\x05layer\"v\n" +
	"\x1bResolveSessionLayerResponse\x12\x14\n" +
	"\x05layer\x18\x01 \x01(\x05R\x05layer\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x03R\x05msgId\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"a\n" +
	"\x1dResolveInheritedLayerResponse\x12\x14\n" +
	"\x05layer\x18\x01 \x01(\x05R\x05layer\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa5\x01\n" +
	"\x1bAdvanceSessionLayerResponse\x12#\n" +
	"\rcurrent_layer\x18\x01 \x01(\x05R\fcurrentLayer\x12$\n" +
	"\x0ecurrent_msg_id\x18\x02 \x01(\x03R\fcurrentMsgId\x12%\n" +
	"\x0epublish_shared\x18\x03 \x01(\bR\rpublishShared\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"L\n" +
	"\x1aDeleteSessionLayerResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd9\x02\n" +
	"\x1cObserveInitConnectionRequest\x12\x1e\n" +
	"\vauth_key_id\x18\x01 \x01(\fR\tauthKeyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x14\n" +
	"\x05layer\x18\x03 \x01(\x05R\x05layer\x12\x15\n" +
	"\x06api_id\x18\x04 \x01(\x05R\x05apiId\x12!\n" +
	"\fdevice_model\x18\x05 \x01(\tR\vdeviceModel\x12%\n" +
	"\x0esystem_version\x18\x06 \x01(\tR\rsystemVersion\x12\x1f\n" +
	"\vapp_version\x18\a \x01(\tR\n" +
	"appVersion\x12(\n" +
	"\x10system_lang_code\x18\b \x01(\tR\x0esystemLangCode\x12\x1b\n" +
	"\tlang_pack\x18\t \x01(\tR\blangPack\x12\x1b\n" +
	"\tlang_code\x18\n" +
	" \x01(\tR\blangCode\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error*\x84\x01\n" +
	"\rAdmissionMode\x12\x1e\n" +
	"\x1aADMISSION_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ADMISSION_MODE_LAYER\x10\x01\x12\x1a\n" +
	"\x16ADMISSION_MODE_DEFAULT\x10\x02\x12\x1d\n" +
	"\x19ADMISSION_MODE_UNPROFILED\x10\x03*\xa2\x01\n" +
	"\x15UpdateStateCommitMode\x12(\n" +
	"$UPDATE_STATE_COMMIT_MODE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"UPDATE_STATE_COMMIT_DELIVERED_ONLY\x10\x01\x127\n" +
	"3UPDATE_STATE_COMMIT_DELIVERED_AND_OBSERVED_BASELINE\x10\x022\xdc\r\n" +
	"\x0fCoreExecService\x12^\n" +
	"\aGetInfo\x12(.telesrv.coreexec.v1.CoreExecInfoRequest\x1a).telesrv.coreexec.v1.CoreExecInfoResponse\x12_\n" +
	"\x10DispatchAdmitted\x12$.telesrv.coreexec.v1.DispatchRequest\x1a%.telesrv.coreexec.v1.DispatchResponse\x12i\n" +
	"\x15PrepareAdmittedReplay\x12$.telesrv.coreexec.v1.DispatchRequest\x1a*.telesrv.coreexec.v1.PrepareReplayResponse\x12k\n" +
	"\x14CommitAdmittedReplay\x12(.telesrv.coreexec.v1.CommitReplayRequest\x1a).telesrv.coreexec.v1.CommitReplayResponse\x12\x8a\x01\n" +
	"\x19CommitPostResponseActions\x125.telesrv.coreexec.v1.CommitPostResponseActionsRequest\x1a6.telesrv.coreexec.v1.CommitPostResponseActionsResponse\x12k\n" +
	"\x14ReportSessionOffline\x12/.telesrv.coreexec.v1.SessionOfflineBatchRequest\x1a\".telesrv.coreexec.v1.ErrorResponse\x12v\n" +
	"\x1dResolveNegotiatedSessionLayer\x12#.telesrv.coreexec.v1.AuthKeyRequest\x1a0.telesrv.coreexec.v1.ResolveSessionLayerResponse\x12w\n" +
	"\x1cResolveInheritedAuthKeyLayer\x12#.telesrv.coreexec.v1.AuthKeyRequest\x1a2.telesrv.coreexec.v1.ResolveInheritedLayerResponse\x12v\n" +
	"\x1dAdvanceNegotiatedSessionLayer\x12#.telesrv.coreexec.v1.AuthKeyRequest\x1a0.telesrv.coreexec.v1.AdvanceSessionLayerResponse\x12t\n" +
	"\x1cDeleteNegotiatedSessionLayer\x12#.telesrv.coreexec.v1.AuthKeyRequest\x1a/.telesrv.coreexec.v1.DeleteSessionLayerResponse\x12l\n" +
	"\x14PublishLayerEvidence\x120.telesrv.coreexec.v1.PublishLayerEvidenceRequest\x1a\".telesrv.coreexec.v1.ErrorResponse\x12n\n" +
	"\x15ObserveInitConnection\x121.telesrv.coreexec.v1.ObserveInitConnectionRequest\x1a\".telesrv.coreexec.v1.ErrorResponse\x12U\n" +
	"\vSaveAuthKey\x12\".telesrv.coreexec.v1.AuthKeyRecord\x1a\".telesrv.coreexec.v1.ErrorResponse\x12Z\n" +
	"\n" +
	"GetAuthKey\x12#.telesrv.coreexec.v1.AuthKeyRequest\x1a'.telesrv.coreexec.v1.GetAuthKeyResponse\x12l\n" +
	"\x17UpdateAuthKeyClientInfo\x12-.telesrv.coreexec.v1.AuthKeyClientInfoRequest\x1a\".telesrv.coreexec.v1.ErrorResponse\x12X\n" +
	"\rDeleteAuthKey\x12#.telesrv.coreexec.v1.AuthKeyRequest\x1a\".telesrv.coreexec.v1.ErrorResponseB1Z/telesrv/internal/coreexec/coreexecpb;coreexecpbb\x06proto3"

var (
	file_internal_coreexec_coreexecpb_coreexec_proto_rawDescOnce sync.Once
	file_internal_coreexec_coreexecpb_coreexec_proto_rawDescData []byte
)

func file_internal_coreexec_coreexecpb_coreexec_proto_rawDescGZIP() []byte {
	file_internal_coreexec_coreexecpb_coreexec_proto_rawDescOnce.Do(func() {
		file_internal_coreexec_coreexecpb_coreexec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_coreexec_coreexecpb_coreexec_proto_rawDesc), len(file_internal_coreexec_coreexecpb_coreexec_proto_rawDesc)))
	})
	return file_internal_coreexec_coreexecpb_coreexec_proto_rawDescData
}

var file_internal_coreexec_coreexecpb_coreexec_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_internal_coreexec_coreexecpb_coreexec_proto_goTypes = []any{
	(AdmissionMode)(0),                         // 0: telesrv.coreexec.v1.AdmissionMode
	(UpdateStateCommitMode)(0),                 // 1: telesrv.coreexec.v1.UpdateStateCommitMode
	(*CoreExecInfoRequest)(nil),                // 2: telesrv.coreexec.v1.CoreExecInfoRequest
	(*CoreExecInfoResponse)(nil),               // 3: telesrv.coreexec.v1.CoreExecInfoResponse
	(*Limits)(nil),                             // 4: telesrv.coreexec.v1.Limits
	(*ProfileMark)(nil),                        // 5: telesrv.coreexec.v1.ProfileMark
	(*WireProof)(nil),                          // 6: telesrv.coreexec.v1.WireProof
	(*RPCError)(nil),                           // 7: telesrv.coreexec.v1.RPCError
	(*IdentityHint)(nil),                       // 8: telesrv.coreexec.v1.IdentityHint
	(*DispatchRequest)(nil),                    // 9: telesrv.coreexec.v1.DispatchRequest
	(*DispatchResponse)(nil),                   // 10: telesrv.coreexec.v1.DispatchResponse
	(*PostResponseAction)(nil),                 // 11: telesrv.coreexec.v1.PostResponseAction
	(*AccountAuthorizationTeardownAction)(nil), // 12: telesrv.coreexec.v1.AccountAuthorizationTeardownAction
	(*UpdateState)(nil),                        // 13: telesrv.coreexec.v1.UpdateState
	(*UpdatesDeliveryAction)(nil),              // 14: telesrv.coreexec.v1.UpdatesDeliveryAction
	(*PrepareReplayResponse)(nil),              // 15: telesrv.coreexec.v1.PrepareReplayResponse
	(*CommitReplayRequest)(nil),                // 16: telesrv.coreexec.v1.CommitReplayRequest
	(*CommitReplayResponse)(nil),               // 17: telesrv.coreexec.v1.CommitReplayResponse
	(*CommitPostResponseActionsRequest)(nil),   // 18: telesrv.coreexec.v1.CommitPostResponseActionsRequest
	(*CommitPostResponseActionsResponse)(nil),  // 19: telesrv.coreexec.v1.CommitPostResponseActionsResponse
	(*SessionOfflineEvent)(nil),                // 20: telesrv.coreexec.v1.SessionOfflineEvent
	(*SessionOfflineBatchRequest)(nil),         // 21: telesrv.coreexec.v1.SessionOfflineBatchRequest
	(*AuthKeyRequest)(nil),                     // 22: telesrv.coreexec.v1.AuthKeyRequest
	(*AuthKeyRecord)(nil),                      // 23: telesrv.coreexec.v1.AuthKeyRecord
	(*GetAuthKeyResponse)(nil),                 // 24: telesrv.coreexec.v1.GetAuthKeyResponse
	(*AuthKeyClientInfoRequest)(nil),           // 25: telesrv.coreexec.v1.AuthKeyClientInfoRequest
	(*PublishLayerEvidenceRequest)(nil),        // 26: telesrv.coreexec.v1.PublishLayerEvidenceRequest
	(*ResolveSessionLayerResponse)(nil),        // 27: telesrv.coreexec.v1.ResolveSessionLayerResponse
	(*ResolveInheritedLayerResponse)(nil),      // 28: telesrv.coreexec.v1.ResolveInheritedLayerResponse
	(*AdvanceSessionLayerResponse)(nil),        // 29: telesrv.coreexec.v1.AdvanceSessionLayerResponse
	(*DeleteSessionLayerResponse)(nil),         // 30: telesrv.coreexec.v1.DeleteSessionLayerResponse
	(*ObserveInitConnectionRequest)(nil),       // 31: telesrv.coreexec.v1.ObserveInitConnectionRequest
	(*ErrorResponse)(nil),                      // 32: telesrv.coreexec.v1.ErrorResponse
}
var file_internal_coreexec_coreexecpb_coreexec_proto_depIdxs = []int32{
	5,  // 0: telesrv.coreexec.v1.WireProof.effective_profile:type_name -> telesrv.coreexec.v1.ProfileMark
	5,  // 1: telesrv.coreexec.v1.WireProof.profile_evidence:type_name -> telesrv.coreexec.v1.ProfileMark
	0,  // 2: telesrv.coreexec.v1.DispatchRequest.mode:type_name -> telesrv.coreexec.v1.AdmissionMode
	4,  // 3: telesrv.coreexec.v1.DispatchRequest.limits:type_name -> telesrv.coreexec.v1.Limits
	6,  // 4: telesrv.coreexec.v1.DispatchRequest.proof:type_name -> telesrv.coreexec.v1.WireProof
	8,  // 5: telesrv.coreexec.v1.DispatchRequest.identity_hint:type_name -> telesrv.coreexec.v1.IdentityHint
	7,  // 6: telesrv.coreexec.v1.DispatchResponse.rpc_error:type_name -> telesrv.coreexec.v1.RPCError
	11, // 7: telesrv.coreexec.v1.DispatchResponse.post_response_actions:type_name -> telesrv.coreexec.v1.PostResponseAction
	14, // 8: telesrv.coreexec.v1.PostResponseAction.updates_delivery:type_name -> telesrv.coreexec.v1.UpdatesDeliveryAction
	12, // 9: telesrv.coreexec.v1.PostResponseAction.account_authorization_teardown:type_name -> telesrv.coreexec.v1.AccountAuthorizationTeardownAction
	13, // 10: telesrv.coreexec.v1.UpdatesDeliveryAction.cursor_state:type_name -> telesrv.coreexec.v1.UpdateState
	1,  // 11: telesrv.coreexec.v1.UpdatesDeliveryAction.cursor_mode:type_name -> telesrv.coreexec.v1.UpdateStateCommitMode
	11, // 12: telesrv.coreexec.v1.CommitPostResponseActionsRequest.actions:type_name -> telesrv.coreexec.v1.PostResponseAction
	20, // 13: telesrv.coreexec.v1.SessionOfflineBatchRequest.events:type_name -> telesrv.coreexec.v1.SessionOfflineEvent
	23, // 14: telesrv.coreexec.v1.GetAuthKeyResponse.auth_key:type_name -> telesrv.coreexec.v1.AuthKeyRecord
	2,  // 15: telesrv.coreexec.v1.CoreExecService.GetInfo:input_type -> telesrv.coreexec.v1.CoreExecInfoRequest
	9,  // 16: telesrv.coreexec.v1.CoreExecService.DispatchAdmitted:input_type -> telesrv.coreexec.v1.DispatchRequest
	9,  // 17: telesrv.coreexec.v1.CoreExecService.PrepareAdmittedReplay:input_type -> telesrv.coreexec.v1.DispatchRequest
	16, // 18: telesrv.coreexec.v1.CoreExecService.CommitAdmittedReplay:input_type -> telesrv.coreexec.v1.CommitReplayRequest
	18, // 19: telesrv.coreexec.v1.CoreExecService.CommitPostResponseActions:input_type -> telesrv.coreexec.v1.CommitPostResponseActionsRequest
	21, // 20: telesrv.coreexec.v1.CoreExecService.ReportSessionOffline:input_type -> telesrv.coreexec.v1.SessionOfflineBatchRequest
	22, // 21: telesrv.coreexec.v1.CoreExecService.ResolveNegotiatedSessionLayer:input_type -> telesrv.coreexec.v1.AuthKeyRequest
	22, // 22: telesrv.coreexec.v1.CoreExecService.ResolveInheritedAuthKeyLayer:input_type -> telesrv.coreexec.v1.AuthKeyRequest
	22, // 23: telesrv.coreexec.v1.CoreExecService.AdvanceNegotiatedSessionLayer:input_type -> telesrv.coreexec.v1.AuthKeyRequest
	22, // 24: telesrv.coreexec.v1.CoreExecService.DeleteNegotiatedSessionLayer:input_type -> telesrv.coreexec.v1.AuthKeyRequest
	26, // 25: telesrv.coreexec.v1.CoreExecService.PublishLayerEvidence:input_type -> telesrv.coreexec.v1.PublishLayerEvidenceRequest
	31, // 26: telesrv.coreexec.v1.CoreExecService.ObserveInitConnection:input_type -> telesrv.coreexec.v1.ObserveInitConnectionRequest
	23, // 27: telesrv.coreexec.v1.CoreExecService.SaveAuthKey:input_type -> telesrv.coreexec.v1.AuthKeyRecord
	22, // 28: telesrv.coreexec.v1.CoreExecService.GetAuthKey:input_type -> telesrv.coreexec.v1.AuthKeyRequest
	25, // 29: telesrv.coreexec.v1.CoreExecService.UpdateAuthKeyClientInfo:input_type -> telesrv.coreexec.v1.AuthKeyClientInfoRequest
	22, // 30: telesrv.coreexec.v1.CoreExecService.DeleteAuthKey:input_type -> telesrv.coreexec.v1.AuthKeyRequest
	3,  // 31: telesrv.coreexec.v1.CoreExecService.GetInfo:output_type -> telesrv.coreexec.v1.CoreExecInfoResponse
	10, // 32: telesrv.coreexec.v1.CoreExecService.DispatchAdmitted:output_type -> telesrv.coreexec.v1.DispatchResponse
	15, // 33: telesrv.coreexec.v1.CoreExecService.PrepareAdmittedReplay:output_type -> telesrv.coreexec.v1.PrepareReplayResponse
	17, // 34: telesrv.coreexec.v1.CoreExecService.CommitAdmittedReplay:output_type -> telesrv.coreexec.v1.CommitReplayResponse
	19, // 35: telesrv.coreexec.v1.CoreExecService.CommitPostResponseActions:output_type -> telesrv.coreexec.v1.CommitPostResponseActionsResponse
	32, // 36: telesrv.coreexec.v1.CoreExecService.ReportSessionOffline:output_type -> telesrv.coreexec.v1.ErrorResponse
	27, // 37: telesrv.coreexec.v1.CoreExecService.ResolveNegotiatedSessionLayer:output_type -> telesrv.coreexec.v1.ResolveSessionLayerResponse
	28, // 38: telesrv.coreexec.v1.CoreExecService.ResolveInheritedAuthKeyLayer:output_type -> telesrv.coreexec.v1.ResolveInheritedLayerResponse
	29, // 39: telesrv.coreexec.v1.CoreExecService.AdvanceNegotiatedSessionLayer:output_type -> telesrv.coreexec.v1.AdvanceSessionLayerResponse
	30, // 40: telesrv.coreexec.v1.CoreExecService.DeleteNegotiatedSessionLayer:output_type -> telesrv.coreexec.v1.DeleteSessionLayerResponse
	32, // 41: telesrv.coreexec.v1.CoreExecService.PublishLayerEvidence:output_type -> telesrv.coreexec.v1.ErrorResponse
	32, // 42: telesrv.coreexec.v1.CoreExecService.ObserveInitConnection:output_type -> telesrv.coreexec.v1.ErrorResponse
	32, // 43: telesrv.coreexec.v1.CoreExecService.SaveAuthKey:output_type -> telesrv.coreexec.v1.ErrorResponse
	24, // 44: telesrv.coreexec.v1.CoreExecService.GetAuthKey:output_type -> telesrv.coreexec.v1.GetAuthKeyResponse
	32, // 45: telesrv.coreexec.v1.CoreExecService.UpdateAuthKeyClientInfo:output_type -> telesrv.coreexec.v1.ErrorResponse
	32, // 46: telesrv.coreexec.v1.CoreExecService.DeleteAuthKey:output_type -> telesrv.coreexec.v1.ErrorResponse
	31, // [31:47] is the sub-list for method output_type
	15, // [15:31] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_coreexec_coreexecpb_coreexec_proto_init() }
func file_internal_coreexec_coreexecpb_coreexec_proto_init() {
	if File_internal_coreexec_coreexecpb_coreexec_proto != nil {
		return
	}
	file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes[9].OneofWrappers = []any{
		(*PostResponseAction_UpdatesDelivery)(nil),
		(*PostResponseAction_AccountAuthorizationTeardown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_coreexec_coreexecpb_coreexec_proto_rawDesc), len(file_internal_coreexec_coreexecpb_coreexec_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_coreexec_coreexecpb_coreexec_proto_goTypes,
		DependencyIndexes: file_internal_coreexec_coreexecpb_coreexec_proto_depIdxs,
		EnumInfos:         file_internal_coreexec_coreexecpb_coreexec_proto_enumTypes,
		MessageInfos:      file_internal_coreexec_coreexecpb_coreexec_proto_msgTypes,
	}.Build()
	File_internal_coreexec_coreexecpb_coreexec_proto = out.File
	file_internal_coreexec_coreexecpb_coreexec_proto_goTypes = nil
	file_internal_coreexec_coreexecpb_coreexec_proto_depIdxs = nil
}
