// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: internal/coreexec/coreexecpb/coreexec.proto

package coreexecpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreExecService_GetInfo_FullMethodName                       = "/telesrv.coreexec.v1.CoreExecService/GetInfo"
	CoreExecService_DispatchAdmitted_FullMethodName              = "/telesrv.coreexec.v1.CoreExecService/DispatchAdmitted"
	CoreExecService_PrepareAdmittedReplay_FullMethodName         = "/telesrv.coreexec.v1.CoreExecService/PrepareAdmittedReplay"
	CoreExecService_CommitAdmittedReplay_FullMethodName          = "/telesrv.coreexec.v1.CoreExecService/CommitAdmittedReplay"
	CoreExecService_CommitPostResponseActions_FullMethodName     = "/telesrv.coreexec.v1.CoreExecService/CommitPostResponseActions"
	CoreExecService_ReportSessionOffline_FullMethodName          = "/telesrv.coreexec.v1.CoreExecService/ReportSessionOffline"
	CoreExecService_ResolveNegotiatedSessionLayer_FullMethodName = "/telesrv.coreexec.v1.CoreExecService/ResolveNegotiatedSessionLayer"
	CoreExecService_ResolveInheritedAuthKeyLayer_FullMethodName  = "/telesrv.coreexec.v1.CoreExecService/ResolveInheritedAuthKeyLayer"
	CoreExecService_AdvanceNegotiatedSessionLayer_FullMethodName = "/telesrv.coreexec.v1.CoreExecService/AdvanceNegotiatedSessionLayer"
	CoreExecService_DeleteNegotiatedSessionLayer_FullMethodName  = "/telesrv.coreexec.v1.CoreExecService/DeleteNegotiatedSessionLayer"
	CoreExecService_PublishLayerEvidence_FullMethodName          = "/telesrv.coreexec.v1.CoreExecService/PublishLayerEvidence"
	CoreExecService_ObserveInitConnection_FullMethodName         = "/telesrv.coreexec.v1.CoreExecService/ObserveInitConnection"
	CoreExecService_SaveAuthKey_FullMethodName                   = "/telesrv.coreexec.v1.CoreExecService/SaveAuthKey"
	CoreExecService_GetAuthKey_FullMethodName                    = "/telesrv.coreexec.v1.CoreExecService/GetAuthKey"
	CoreExecService_UpdateAuthKeyClientInfo_FullMethodName       = "/telesrv.coreexec.v1.CoreExecService/UpdateAuthKeyClientInfo"
	CoreExecService_DeleteAuthKey_FullMethodName                 = "/telesrv.coreexec.v1.CoreExecService/DeleteAuthKey"
)

// CoreExecServiceClient is the client API for CoreExecService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreExecServiceClient interface {
	GetInfo(ctx context.Context, in *CoreExecInfoRequest, opts ...grpc.CallOption) (*CoreExecInfoResponse, error)
	DispatchAdmitted(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	PrepareAdmittedReplay(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*PrepareReplayResponse, error)
	CommitAdmittedReplay(ctx context.Context, in *CommitReplayRequest, opts ...grpc.CallOption) (*CommitReplayResponse, error)
	CommitPostResponseActions(ctx context.Context, in *CommitPostResponseActionsRequest, opts ...grpc.CallOption) (*CommitPostResponseActionsResponse, error)
	ReportSessionOffline(ctx context.Context, in *SessionOfflineBatchRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	ResolveNegotiatedSessionLayer(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*ResolveSessionLayerResponse, error)
	ResolveInheritedAuthKeyLayer(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*ResolveInheritedLayerResponse, error)
	AdvanceNegotiatedSessionLayer(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*AdvanceSessionLayerResponse, error)
	DeleteNegotiatedSessionLayer(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*DeleteSessionLayerResponse, error)
	PublishLayerEvidence(ctx context.Context, in *PublishLayerEvidenceRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	ObserveInitConnection(ctx context.Context, in *ObserveInitConnectionRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	SaveAuthKey(ctx context.Context, in *AuthKeyRecord, opts ...grpc.CallOption) (*ErrorResponse, error)
	GetAuthKey(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*GetAuthKeyResponse, error)
	UpdateAuthKeyClientInfo(ctx context.Context, in *AuthKeyClientInfoRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	DeleteAuthKey(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type coreExecServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreExecServiceClient(cc grpc.ClientConnInterface) CoreExecServiceClient {
	return &coreExecServiceClient{cc}
}

func (c *coreExecServiceClient) GetInfo(ctx context.Context, in *CoreExecInfoRequest, opts ...grpc.CallOption) (*CoreExecInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoreExecInfoResponse)
	err := c.cc.Invoke(ctx, CoreExecService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) DispatchAdmitted(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, CoreExecService_DispatchAdmitted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) PrepareAdmittedReplay(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*PrepareReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareReplayResponse)
	err := c.cc.Invoke(ctx, CoreExecService_PrepareAdmittedReplay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) CommitAdmittedReplay(ctx context.Context, in *CommitReplayRequest, opts ...grpc.CallOption) (*CommitReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitReplayResponse)
	err := c.cc.Invoke(ctx, CoreExecService_CommitAdmittedReplay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) CommitPostResponseActions(ctx context.Context, in *CommitPostResponseActionsRequest, opts ...grpc.CallOption) (*CommitPostResponseActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitPostResponseActionsResponse)
	err := c.cc.Invoke(ctx, CoreExecService_CommitPostResponseActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) ReportSessionOffline(ctx context.Context, in *SessionOfflineBatchRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, CoreExecService_ReportSessionOffline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) ResolveNegotiatedSessionLayer(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*ResolveSessionLayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSessionLayerResponse)
	err := c.cc.Invoke(ctx, CoreExecService_ResolveNegotiatedSessionLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) ResolveInheritedAuthKeyLayer(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*ResolveInheritedLayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveInheritedLayerResponse)
	err := c.cc.Invoke(ctx, CoreExecService_ResolveInheritedAuthKeyLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) AdvanceNegotiatedSessionLayer(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*AdvanceSessionLayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvanceSessionLayerResponse)
	err := c.cc.Invoke(ctx, CoreExecService_AdvanceNegotiatedSessionLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) DeleteNegotiatedSessionLayer(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*DeleteSessionLayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionLayerResponse)
	err := c.cc.Invoke(ctx, CoreExecService_DeleteNegotiatedSessionLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) PublishLayerEvidence(ctx context.Context, in *PublishLayerEvidenceRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, CoreExecService_PublishLayerEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) ObserveInitConnection(ctx context.Context, in *ObserveInitConnectionRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, CoreExecService_ObserveInitConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) SaveAuthKey(ctx context.Context, in *AuthKeyRecord, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, CoreExecService_SaveAuthKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) GetAuthKey(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*GetAuthKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthKeyResponse)
	err := c.cc.Invoke(ctx, CoreExecService_GetAuthKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) UpdateAuthKeyClientInfo(ctx context.Context, in *AuthKeyClientInfoRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, CoreExecService_UpdateAuthKeyClientInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreExecServiceClient) DeleteAuthKey(ctx context.Context, in *AuthKeyRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, CoreExecService_DeleteAuthKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreExecServiceServer is the server API for CoreExecService service.
// All implementations must embed UnimplementedCoreExecServiceServer
// for forward compatibility.
type CoreExecServiceServer interface {
	GetInfo(context.Context, *CoreExecInfoRequest) (*CoreExecInfoResponse, error)
	DispatchAdmitted(context.Context, *DispatchRequest) (*DispatchResponse, error)
	PrepareAdmittedReplay(context.Context, *DispatchRequest) (*PrepareReplayResponse, error)
	CommitAdmittedReplay(context.Context, *CommitReplayRequest) (*CommitReplayResponse, error)
	CommitPostResponseActions(context.Context, *CommitPostResponseActionsRequest) (*CommitPostResponseActionsResponse, error)
	ReportSessionOffline(context.Context, *SessionOfflineBatchRequest) (*ErrorResponse, error)
	ResolveNegotiatedSessionLayer(context.Context, *AuthKeyRequest) (*ResolveSessionLayerResponse, error)
	ResolveInheritedAuthKeyLayer(context.Context, *AuthKeyRequest) (*ResolveInheritedLayerResponse, error)
	AdvanceNegotiatedSessionLayer(context.Context, *AuthKeyRequest) (*AdvanceSessionLayerResponse, error)
	DeleteNegotiatedSessionLayer(context.Context, *AuthKeyRequest) (*DeleteSessionLayerResponse, error)
	PublishLayerEvidence(context.Context, *PublishLayerEvidenceRequest) (*ErrorResponse, error)
	ObserveInitConnection(context.Context, *ObserveInitConnectionRequest) (*ErrorResponse, error)
	SaveAuthKey(context.Context, *AuthKeyRecord) (*ErrorResponse, error)
	GetAuthKey(context.Context, *AuthKeyRequest) (*GetAuthKeyResponse, error)
	UpdateAuthKeyClientInfo(context.Context, *AuthKeyClientInfoRequest) (*ErrorResponse, error)
	DeleteAuthKey(context.Context, *AuthKeyRequest) (*ErrorResponse, error)
	mustEmbedUnimplementedCoreExecServiceServer()
}

// UnimplementedCoreExecServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreExecServiceServer struct{}

func (UnimplementedCoreExecServiceServer) GetInfo(context.Context, *CoreExecInfoRequest) (*CoreExecInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedCoreExecServiceServer) DispatchAdmitted(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispatchAdmitted not implemented")
}
func (UnimplementedCoreExecServiceServer) PrepareAdmittedReplay(context.Context, *DispatchRequest) (*PrepareReplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareAdmittedReplay not implemented")
}
func (UnimplementedCoreExecServiceServer) CommitAdmittedReplay(context.Context, *CommitReplayRequest) (*CommitReplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitAdmittedReplay not implemented")
}
func (UnimplementedCoreExecServiceServer) CommitPostResponseActions(context.Context, *CommitPostResponseActionsRequest) (*CommitPostResponseActionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitPostResponseActions not implemented")
}
func (UnimplementedCoreExecServiceServer) ReportSessionOffline(context.Context, *SessionOfflineBatchRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSessionOffline not implemented")
}
func (UnimplementedCoreExecServiceServer) ResolveNegotiatedSessionLayer(context.Context, *AuthKeyRequest) (*ResolveSessionLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveNegotiatedSessionLayer not implemented")
}
func (UnimplementedCoreExecServiceServer) ResolveInheritedAuthKeyLayer(context.Context, *AuthKeyRequest) (*ResolveInheritedLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveInheritedAuthKeyLayer not implemented")
}
func (UnimplementedCoreExecServiceServer) AdvanceNegotiatedSessionLayer(context.Context, *AuthKeyRequest) (*AdvanceSessionLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdvanceNegotiatedSessionLayer not implemented")
}
func (UnimplementedCoreExecServiceServer) DeleteNegotiatedSessionLayer(context.Context, *AuthKeyRequest) (*DeleteSessionLayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNegotiatedSessionLayer not implemented")
}
func (UnimplementedCoreExecServiceServer) PublishLayerEvidence(context.Context, *PublishLayerEvidenceRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishLayerEvidence not implemented")
}
func (UnimplementedCoreExecServiceServer) ObserveInitConnection(context.Context, *ObserveInitConnectionRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObserveInitConnection not implemented")
}
func (UnimplementedCoreExecServiceServer) SaveAuthKey(context.Context, *AuthKeyRecord) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAuthKey not implemented")
}
func (UnimplementedCoreExecServiceServer) GetAuthKey(context.Context, *AuthKeyRequest) (*GetAuthKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthKey not implemented")
}
func (UnimplementedCoreExecServiceServer) UpdateAuthKeyClientInfo(context.Context, *AuthKeyClientInfoRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAuthKeyClientInfo not implemented")
}
func (UnimplementedCoreExecServiceServer) DeleteAuthKey(context.Context, *AuthKeyRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAuthKey not implemented")
}
func (UnimplementedCoreExecServiceServer) mustEmbedUnimplementedCoreExecServiceServer() {}
func (UnimplementedCoreExecServiceServer) testEmbeddedByValue()                         {}

// UnsafeCoreExecServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreExecServiceServer will
// result in compilation errors.
type UnsafeCoreExecServiceServer interface {
	mustEmbedUnimplementedCoreExecServiceServer()
}

func RegisterCoreExecServiceServer(s grpc.ServiceRegistrar, srv CoreExecServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreExecServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreExecService_ServiceDesc, srv)
}

func _CoreExecService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoreExecInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).GetInfo(ctx, req.(*CoreExecInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_DispatchAdmitted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).DispatchAdmitted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_DispatchAdmitted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).DispatchAdmitted(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_PrepareAdmittedReplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).PrepareAdmittedReplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_PrepareAdmittedReplay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).PrepareAdmittedReplay(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_CommitAdmittedReplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).CommitAdmittedReplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_CommitAdmittedReplay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).CommitAdmittedReplay(ctx, req.(*CommitReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_CommitPostResponseActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitPostResponseActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).CommitPostResponseActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_CommitPostResponseActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).CommitPostResponseActions(ctx, req.(*CommitPostResponseActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_ReportSessionOffline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionOfflineBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).ReportSessionOffline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_ReportSessionOffline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).ReportSessionOffline(ctx, req.(*SessionOfflineBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_ResolveNegotiatedSessionLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).ResolveNegotiatedSessionLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_ResolveNegotiatedSessionLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).ResolveNegotiatedSessionLayer(ctx, req.(*AuthKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_ResolveInheritedAuthKeyLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).ResolveInheritedAuthKeyLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_ResolveInheritedAuthKeyLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).ResolveInheritedAuthKeyLayer(ctx, req.(*AuthKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_AdvanceNegotiatedSessionLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).AdvanceNegotiatedSessionLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_AdvanceNegotiatedSessionLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).AdvanceNegotiatedSessionLayer(ctx, req.(*AuthKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_DeleteNegotiatedSessionLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).DeleteNegotiatedSessionLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_DeleteNegotiatedSessionLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).DeleteNegotiatedSessionLayer(ctx, req.(*AuthKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_PublishLayerEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishLayerEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).PublishLayerEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_PublishLayerEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).PublishLayerEvidence(ctx, req.(*PublishLayerEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_ObserveInitConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveInitConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).ObserveInitConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_ObserveInitConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).ObserveInitConnection(ctx, req.(*ObserveInitConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_SaveAuthKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).SaveAuthKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_SaveAuthKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).SaveAuthKey(ctx, req.(*AuthKeyRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_GetAuthKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).GetAuthKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_GetAuthKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).GetAuthKey(ctx, req.(*AuthKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_UpdateAuthKeyClientInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyClientInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).UpdateAuthKeyClientInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_UpdateAuthKeyClientInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).UpdateAuthKeyClientInfo(ctx, req.(*AuthKeyClientInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreExecService_DeleteAuthKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreExecServiceServer).DeleteAuthKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreExecService_DeleteAuthKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreExecServiceServer).DeleteAuthKey(ctx, req.(*AuthKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreExecService_ServiceDesc is the grpc.ServiceDesc for CoreExecService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreExecService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telesrv.coreexec.v1.CoreExecService",
	HandlerType: (*CoreExecServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _CoreExecService_GetInfo_Handler,
		},
		{
			MethodName: "DispatchAdmitted",
			Handler:    _CoreExecService_DispatchAdmitted_Handler,
		},
		{
			MethodName: "PrepareAdmittedReplay",
			Handler:    _CoreExecService_PrepareAdmittedReplay_Handler,
		},
		{
			MethodName: "CommitAdmittedReplay",
			Handler:    _CoreExecService_CommitAdmittedReplay_Handler,
		},
		{
			MethodName: "CommitPostResponseActions",
			Handler:    _CoreExecService_CommitPostResponseActions_Handler,
		},
		{
			MethodName: "ReportSessionOffline",
			Handler:    _CoreExecService_ReportSessionOffline_Handler,
		},
		{
			MethodName: "ResolveNegotiatedSessionLayer",
			Handler:    _CoreExecService_ResolveNegotiatedSessionLayer_Handler,
		},
		{
			MethodName: "ResolveInheritedAuthKeyLayer",
			Handler:    _CoreExecService_ResolveInheritedAuthKeyLayer_Handler,
		},
		{
			MethodName: "AdvanceNegotiatedSessionLayer",
			Handler:    _CoreExecService_AdvanceNegotiatedSessionLayer_Handler,
		},
		{
			MethodName: "DeleteNegotiatedSessionLayer",
			Handler:    _CoreExecService_DeleteNegotiatedSessionLayer_Handler,
		},
		{
			MethodName: "PublishLayerEvidence",
			Handler:    _CoreExecService_PublishLayerEvidence_Handler,
		},
		{
			MethodName: "ObserveInitConnection",
			Handler:    _CoreExecService_ObserveInitConnection_Handler,
		},
		{
			MethodName: "SaveAuthKey",
			Handler:    _CoreExecService_SaveAuthKey_Handler,
		},
		{
			MethodName: "GetAuthKey",
			Handler:    _CoreExecService_GetAuthKey_Handler,
		},
		{
			MethodName: "UpdateAuthKeyClientInfo",
			Handler:    _CoreExecService_UpdateAuthKeyClientInfo_Handler,
		},
		{
			MethodName: "DeleteAuthKey",
			Handler:    _CoreExecService_DeleteAuthKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/coreexec/coreexecpb/coreexec.proto",
}
