// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: internal/sfu/sfupb/sfu.proto

package sfupb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointKind int32

const (
	EndpointKind_ENDPOINT_KIND_MAIN         EndpointKind = 0
	EndpointKind_ENDPOINT_KIND_PRESENTATION EndpointKind = 1
)

// Enum value maps for EndpointKind.
var (
	EndpointKind_name = map[int32]string{
		0: "ENDPOINT_KIND_MAIN",
		1: "ENDPOINT_KIND_PRESENTATION",
	}
	EndpointKind_value = map[string]int32{
		"ENDPOINT_KIND_MAIN":         0,
		"ENDPOINT_KIND_PRESENTATION": 1,
	}
)

func (x EndpointKind) Enum() *EndpointKind {
	p := new(EndpointKind)
	*p = x
	return p
}

func (x EndpointKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_sfu_sfupb_sfu_proto_enumTypes[0].Descriptor()
}

func (EndpointKind) Type() protoreflect.EnumType {
	return &file_internal_sfu_sfupb_sfu_proto_enumTypes[0]
}

func (x EndpointKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointKind.Descriptor instead.
func (EndpointKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{0}
}

type SFUInfoRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SFUInfoRequest) Reset() {
	*x = SFUInfoRequest{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SFUInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFUInfoRequest) ProtoMessage() {}

func (x *SFUInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFUInfoRequest.ProtoReflect.Descriptor instead.
func (*SFUInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{0}
}

func (x *SFUInfoRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *SFUInfoRequest) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *SFUInfoRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type SFUInfoResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Implementation              string                 `protobuf:"bytes,4,opt,name=implementation,proto3" json:"implementation,omitempty"`
	InstanceId                  string                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Error                       string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SFUInfoResponse) Reset() {
	*x = SFUInfoResponse{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SFUInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFUInfoResponse) ProtoMessage() {}

func (x *SFUInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFUInfoResponse.ProtoReflect.Descriptor instead.
func (*SFUInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{1}
}

func (x *SFUInfoResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *SFUInfoResponse) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *SFUInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *SFUInfoResponse) GetImplementation() string {
	if x != nil {
		return x.Implementation
	}
	return ""
}

func (x *SFUInfoResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SFUInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SsrcGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Semantics     string                 `protobuf:"bytes,1,opt,name=semantics,proto3" json:"semantics,omitempty"`
	Sources       []uint32               `protobuf:"varint,2,rep,packed,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SsrcGroup) Reset() {
	*x = SsrcGroup{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SsrcGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SsrcGroup) ProtoMessage() {}

func (x *SsrcGroup) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SsrcGroup.ProtoReflect.Descriptor instead.
func (*SsrcGroup) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{2}
}

func (x *SsrcGroup) GetSemantics() string {
	if x != nil {
		return x.Semantics
	}
	return ""
}

func (x *SsrcGroup) GetSources() []uint32 {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ClientOffer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AudioSsrc         uint32                 `protobuf:"varint,1,opt,name=audio_ssrc,json=audioSsrc,proto3" json:"audio_ssrc,omitempty"`
	Ufrag             string                 `protobuf:"bytes,2,opt,name=ufrag,proto3" json:"ufrag,omitempty"`
	Pwd               string                 `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	FingerprintSha256 string                 `protobuf:"bytes,4,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3" json:"fingerprint_sha256,omitempty"`
	SsrcGroups        []*SsrcGroup           `protobuf:"bytes,5,rep,name=ssrc_groups,json=ssrcGroups,proto3" json:"ssrc_groups,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientOffer) Reset() {
	*x = ClientOffer{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOffer) ProtoMessage() {}

func (x *ClientOffer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOffer.ProtoReflect.Descriptor instead.
func (*ClientOffer) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{3}
}

func (x *ClientOffer) GetAudioSsrc() uint32 {
	if x != nil {
		return x.AudioSsrc
	}
	return 0
}

func (x *ClientOffer) GetUfrag() string {
	if x != nil {
		return x.Ufrag
	}
	return ""
}

func (x *ClientOffer) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *ClientOffer) GetFingerprintSha256() string {
	if x != nil {
		return x.FingerprintSha256
	}
	return ""
}

func (x *ClientOffer) GetSsrcGroups() []*SsrcGroup {
	if x != nil {
		return x.SsrcGroups
	}
	return nil
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{4}
}

func (x *Candidate) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Candidate) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Candidate) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Candidate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ServerAnswer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ufrag             string                 `protobuf:"bytes,1,opt,name=ufrag,proto3" json:"ufrag,omitempty"`
	Pwd               string                 `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	FingerprintSha256 string                 `protobuf:"bytes,3,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3" json:"fingerprint_sha256,omitempty"`
	Candidates        []*Candidate           `protobuf:"bytes,4,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerAnswer) Reset() {
	*x = ServerAnswer{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAnswer) ProtoMessage() {}

func (x *ServerAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAnswer.ProtoReflect.Descriptor instead.
func (*ServerAnswer) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{5}
}

func (x *ServerAnswer) GetUfrag() string {
	if x != nil {
		return x.Ufrag
	}
	return ""
}

func (x *ServerAnswer) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *ServerAnswer) GetFingerprintSha256() string {
	if x != nil {
		return x.FingerprintSha256
	}
	return ""
}

func (x *ServerAnswer) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        int64                  `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kind          EndpointKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=telesrv.sfu.v1.EndpointKind" json:"kind,omitempty"`
	Offer         *ClientOffer           `protobuf:"bytes,4,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRequest) GetCallId() int64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *JoinRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *JoinRequest) GetKind() EndpointKind {
	if x != nil {
		return x.Kind
	}
	return EndpointKind_ENDPOINT_KIND_MAIN
}

func (x *JoinRequest) GetOffer() *ClientOffer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        *ServerAnswer          `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{7}
}

func (x *JoinResponse) GetAnswer() *ServerAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *JoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        int64                  `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kind          EndpointKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=telesrv.sfu.v1.EndpointKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveRequest) GetCallId() int64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *LeaveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LeaveRequest) GetKind() EndpointKind {
	if x != nil {
		return x.Kind
	}
	return EndpointKind_ENDPOINT_KIND_MAIN
}

type CloseRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        int64                  `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRoomRequest) Reset() {
	*x = CloseRoomRequest{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomRequest) ProtoMessage() {}

func (x *CloseRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomRequest.ProtoReflect.Descriptor instead.
func (*CloseRoomRequest) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{9}
}

func (x *CloseRoomRequest) GetCallId() int64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

type AliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        int64                  `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveRequest) Reset() {
	*x = AliveRequest{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveRequest) ProtoMessage() {}

func (x *AliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveRequest.ProtoReflect.Descriptor instead.
func (*AliveRequest) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{10}
}

func (x *AliveRequest) GetCallId() int64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

type AliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveResponse) Reset() {
	*x = AliveResponse{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveResponse) ProtoMessage() {}

func (x *AliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveResponse.ProtoReflect.Descriptor instead.
func (*AliveResponse) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{11}
}

func (x *AliveResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *AliveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sfu_sfupb_sfu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_sfu_sfupb_sfu_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_sfu_sfupb_sfu_proto protoreflect.FileDescriptor

const file_internal_sfu_sfupb_sfu_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/sfu/sfupb/sfu.proto\x12\x0etelesrv.sfu.v1\"\xa4\x01\n" +
	"\x0eSFUInfoRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x84\x02\n" +
	"\x0fSFUInfoResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12&\n" +
	"\x0eimplementation\x18\x04 \x01(\tR\x0eimplementation\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"C\n" +
	"\tSsrcGroup\x12\x1c\n" +
	"\tsemantics\x18\x01 \x01(\tR\tsemantics\x12\x18\n" +
	"\asources\x18\x02 \x03(\rR\asources\"\xbf\x01\n" +
	"\vClientOffer\x12\x1d\n" +
	"\n" +
	"audio_ssrc\x18\x01 \x01(\rR\taudioSsrc\x12\x14\n" +
	"\x05ufrag\x18\x02 \x01(\tR\x05ufrag\x12\x10\n" +
	"\x03pwd\x18\x03 \x01(\tR\x03pwd\x12-\n" +
	"\x12fingerprint_sha256\x18\x04 \x01(\tR\x11fingerprintSha256\x12:\n" +
	"\vssrc_groups\x18\x05 \x03(\v2\x19.telesrv.sfu.v1.SsrcGroupR\n" +
	"ssrcGroups\"_\n" +
	"\tCandidate\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xa0\x01\n" +
	"\fServerAnswer\x12\x14\n" +
	"\x05ufrag\x18\x01 \x01(\tR\x05ufrag\x12\x10\n" +
	"\x03pwd\x18\x02 \x01(\tR\x03pwd\x12-\n" +
	"\x12fingerprint_sha256\x18\x03 \x01(\tR\x11fingerprintSha256\x129\n" +
	"\n" +
	"candidates\x18\x04 \x03(\v2\x19.telesrv.sfu.v1.CandidateR\n" +
	"candidates\"\xa4\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x03R\x06callId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.telesrv.sfu.v1.EndpointKindR\x04kind\x121\n" +
	"\x05offer\x18\x04 \x01(\v2\x1b.telesrv.sfu.v1.ClientOfferR\x05offer\"Z\n" +
	"\fJoinResponse\x124\n" +
	"\x06answer\x18\x01 \x01(\v2\x1c.telesrv.sfu.v1.ServerAnswerR\x06answer\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"r\n" +
	"\fLeaveRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x03R\x06callId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.telesrv.sfu.v1.EndpointKindR\x04kind\"+\n" +
	"\x10CloseRoomRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x03R\x06callId\"'\n" +
	"\fAliveRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\x03R\x06callId\"@\n" +
	"\rAliveResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error*F\n" +
	"\fEndpointKind\x12\x16\n" +
	"\x12ENDPOINT_KIND_MAIN\x10\x00\x12\x1e\n" +
	"\x1aENDPOINT_KIND_PRESENTATION\x10\x012\xfc\x02\n" +
	"\x11SFUControlService\x12J\n" +
	"\aGetInfo\x12\x1e.telesrv.sfu.v1.SFUInfoRequest\x1a\x1f.telesrv.sfu.v1.SFUInfoResponse\x12A\n" +
	"\x04Join\x12\x1b.telesrv.sfu.v1.JoinRequest\x1a\x1c.telesrv.sfu.v1.JoinResponse\x12D\n" +
	"\x05Leave\x12\x1c.telesrv.sfu.v1.LeaveRequest\x1a\x1d.telesrv.sfu.v1.ErrorResponse\x12L\n" +
	"\tCloseRoom\x12 .telesrv.sfu.v1.CloseRoomRequest\x1a\x1d.telesrv.sfu.v1.ErrorResponse\x12D\n" +
	"\x05Alive\x12\x1c.telesrv.sfu.v1.AliveRequest\x1a\x1d.telesrv.sfu.v1.AliveResponseB\"Z telesrv/internal/sfu/sfupb;sfupbb\x06proto3"

var (
	file_internal_sfu_sfupb_sfu_proto_rawDescOnce sync.Once
	file_internal_sfu_sfupb_sfu_proto_rawDescData []byte
)

func file_internal_sfu_sfupb_sfu_proto_rawDescGZIP() []byte {
	file_internal_sfu_sfupb_sfu_proto_rawDescOnce.Do(func() {
		file_internal_sfu_sfupb_sfu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_sfu_sfupb_sfu_proto_rawDesc), len(file_internal_sfu_sfupb_sfu_proto_rawDesc)))
	})
	return file_internal_sfu_sfupb_sfu_proto_rawDescData
}

var file_internal_sfu_sfupb_sfu_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_sfu_sfupb_sfu_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_sfu_sfupb_sfu_proto_goTypes = []any{
	(EndpointKind)(0),        // 0: telesrv.sfu.v1.EndpointKind
	(*SFUInfoRequest)(nil),   // 1: telesrv.sfu.v1.SFUInfoRequest
	(*SFUInfoResponse)(nil),  // 2: telesrv.sfu.v1.SFUInfoResponse
	(*SsrcGroup)(nil),        // 3: telesrv.sfu.v1.SsrcGroup
	(*ClientOffer)(nil),      // 4: telesrv.sfu.v1.ClientOffer
	(*Candidate)(nil),        // 5: telesrv.sfu.v1.Candidate
	(*ServerAnswer)(nil),     // 6: telesrv.sfu.v1.ServerAnswer
	(*JoinRequest)(nil),      // 7: telesrv.sfu.v1.JoinRequest
	(*JoinResponse)(nil),     // 8: telesrv.sfu.v1.JoinResponse
	(*LeaveRequest)(nil),     // 9: telesrv.sfu.v1.LeaveRequest
	(*CloseRoomRequest)(nil), // 10: telesrv.sfu.v1.CloseRoomRequest
	(*AliveRequest)(nil),     // 11: telesrv.sfu.v1.AliveRequest
	(*AliveResponse)(nil),    // 12: telesrv.sfu.v1.AliveResponse
	(*ErrorResponse)(nil),    // 13: telesrv.sfu.v1.ErrorResponse
}
var file_internal_sfu_sfupb_sfu_proto_depIdxs = []int32{
	3,  // 0: telesrv.sfu.v1.ClientOffer.ssrc_groups:type_name -> telesrv.sfu.v1.SsrcGroup
	5,  // 1: telesrv.sfu.v1.ServerAnswer.candidates:type_name -> telesrv.sfu.v1.Candidate
	0,  // 2: telesrv.sfu.v1.JoinRequest.kind:type_name -> telesrv.sfu.v1.EndpointKind
	4,  // 3: telesrv.sfu.v1.JoinRequest.offer:type_name -> telesrv.sfu.v1.ClientOffer
	6,  // 4: telesrv.sfu.v1.JoinResponse.answer:type_name -> telesrv.sfu.v1.ServerAnswer
	0,  // 5: telesrv.sfu.v1.LeaveRequest.kind:type_name -> telesrv.sfu.v1.EndpointKind
	1,  // 6: telesrv.sfu.v1.SFUControlService.GetInfo:input_type -> telesrv.sfu.v1.SFUInfoRequest
	7,  // 7: telesrv.sfu.v1.SFUControlService.Join:input_type -> telesrv.sfu.v1.JoinRequest
	9,  // 8: telesrv.sfu.v1.SFUControlService.Leave:input_type -> telesrv.sfu.v1.LeaveRequest
	10, // 9: telesrv.sfu.v1.SFUControlService.CloseRoom:input_type -> telesrv.sfu.v1.CloseRoomRequest
	11, // 10: telesrv.sfu.v1.SFUControlService.Alive:input_type -> telesrv.sfu.v1.AliveRequest
	2,  // 11: telesrv.sfu.v1.SFUControlService.GetInfo:output_type -> telesrv.sfu.v1.SFUInfoResponse
	8,  // 12: telesrv.sfu.v1.SFUControlService.Join:output_type -> telesrv.sfu.v1.JoinResponse
	13, // 13: telesrv.sfu.v1.SFUControlService.Leave:output_type -> telesrv.sfu.v1.ErrorResponse
	13, // 14: telesrv.sfu.v1.SFUControlService.CloseRoom:output_type -> telesrv.sfu.v1.ErrorResponse
	12, // 15: telesrv.sfu.v1.SFUControlService.Alive:output_type -> telesrv.sfu.v1.AliveResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_sfu_sfupb_sfu_proto_init() }
func file_internal_sfu_sfupb_sfu_proto_init() {
	if File_internal_sfu_sfupb_sfu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_sfu_sfupb_sfu_proto_rawDesc), len(file_internal_sfu_sfupb_sfu_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_sfu_sfupb_sfu_proto_goTypes,
		DependencyIndexes: file_internal_sfu_sfupb_sfu_proto_depIdxs,
		EnumInfos:         file_internal_sfu_sfupb_sfu_proto_enumTypes,
		MessageInfos:      file_internal_sfu_sfupb_sfu_proto_msgTypes,
	}.Build()
	File_internal_sfu_sfupb_sfu_proto = out.File
	file_internal_sfu_sfupb_sfu_proto_goTypes = nil
	file_internal_sfu_sfupb_sfu_proto_depIdxs = nil
}
