// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: internal/sfu/sfupb/sfu.proto

package sfupb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SFUControlService_GetInfo_FullMethodName   = "/telesrv.sfu.v1.SFUControlService/GetInfo"
	SFUControlService_Join_FullMethodName      = "/telesrv.sfu.v1.SFUControlService/Join"
	SFUControlService_Leave_FullMethodName     = "/telesrv.sfu.v1.SFUControlService/Leave"
	SFUControlService_CloseRoom_FullMethodName = "/telesrv.sfu.v1.SFUControlService/CloseRoom"
	SFUControlService_Alive_FullMethodName     = "/telesrv.sfu.v1.SFUControlService/Alive"
)

// SFUControlServiceClient is the client API for SFUControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SFUControlServiceClient interface {
	GetInfo(ctx context.Context, in *SFUInfoRequest, opts ...grpc.CallOption) (*SFUInfoResponse, error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	CloseRoom(ctx context.Context, in *CloseRoomRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	Alive(ctx context.Context, in *AliveRequest, opts ...grpc.CallOption) (*AliveResponse, error)
}

type sFUControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSFUControlServiceClient(cc grpc.ClientConnInterface) SFUControlServiceClient {
	return &sFUControlServiceClient{cc}
}

func (c *sFUControlServiceClient) GetInfo(ctx context.Context, in *SFUInfoRequest, opts ...grpc.CallOption) (*SFUInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SFUInfoResponse)
	err := c.cc.Invoke(ctx, SFUControlService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFUControlServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, SFUControlService_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFUControlServiceClient) Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, SFUControlService_Leave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFUControlServiceClient) CloseRoom(ctx context.Context, in *CloseRoomRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, SFUControlService_CloseRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFUControlServiceClient) Alive(ctx context.Context, in *AliveRequest, opts ...grpc.CallOption) (*AliveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliveResponse)
	err := c.cc.Invoke(ctx, SFUControlService_Alive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SFUControlServiceServer is the server API for SFUControlService service.
// All implementations must embed UnimplementedSFUControlServiceServer
// for forward compatibility.
type SFUControlServiceServer interface {
	GetInfo(context.Context, *SFUInfoRequest) (*SFUInfoResponse, error)
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Leave(context.Context, *LeaveRequest) (*ErrorResponse, error)
	CloseRoom(context.Context, *CloseRoomRequest) (*ErrorResponse, error)
	Alive(context.Context, *AliveRequest) (*AliveResponse, error)
	mustEmbedUnimplementedSFUControlServiceServer()
}

// UnimplementedSFUControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSFUControlServiceServer struct{}

func (UnimplementedSFUControlServiceServer) GetInfo(context.Context, *SFUInfoRequest) (*SFUInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedSFUControlServiceServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedSFUControlServiceServer) Leave(context.Context, *LeaveRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedSFUControlServiceServer) CloseRoom(context.Context, *CloseRoomRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseRoom not implemented")
}
func (UnimplementedSFUControlServiceServer) Alive(context.Context, *AliveRequest) (*AliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alive not implemented")
}
func (UnimplementedSFUControlServiceServer) mustEmbedUnimplementedSFUControlServiceServer() {}
func (UnimplementedSFUControlServiceServer) testEmbeddedByValue()                           {}

// UnsafeSFUControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SFUControlServiceServer will
// result in compilation errors.
type UnsafeSFUControlServiceServer interface {
	mustEmbedUnimplementedSFUControlServiceServer()
}

func RegisterSFUControlServiceServer(s grpc.ServiceRegistrar, srv SFUControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedSFUControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SFUControlService_ServiceDesc, srv)
}

func _SFUControlService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SFUInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUControlServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SFUControlService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUControlServiceServer).GetInfo(ctx, req.(*SFUInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFUControlService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUControlServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SFUControlService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUControlServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFUControlService_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUControlServiceServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SFUControlService_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUControlServiceServer).Leave(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFUControlService_CloseRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUControlServiceServer).CloseRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SFUControlService_CloseRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUControlServiceServer).CloseRoom(ctx, req.(*CloseRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFUControlService_Alive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUControlServiceServer).Alive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SFUControlService_Alive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUControlServiceServer).Alive(ctx, req.(*AliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SFUControlService_ServiceDesc is the grpc.ServiceDesc for SFUControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SFUControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telesrv.sfu.v1.SFUControlService",
	HandlerType: (*SFUControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _SFUControlService_GetInfo_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _SFUControlService_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _SFUControlService_Leave_Handler,
		},
		{
			MethodName: "CloseRoom",
			Handler:    _SFUControlService_CloseRoom_Handler,
		},
		{
			MethodName: "Alive",
			Handler:    _SFUControlService_Alive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/sfu/sfupb/sfu.proto",
}
