// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: internal/egress/egresspb/egress.proto

package egresspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryQueueKind int32

const (
	DeliveryQueueKind_DELIVERY_QUEUE_KIND_UNSPECIFIED     DeliveryQueueKind = 0
	DeliveryQueueKind_DELIVERY_QUEUE_KIND_ACCOUNT_PTS     DeliveryQueueKind = 1
	DeliveryQueueKind_DELIVERY_QUEUE_KIND_ACCOUNT_NON_PTS DeliveryQueueKind = 2
	DeliveryQueueKind_DELIVERY_QUEUE_KIND_CHANNEL_PTS     DeliveryQueueKind = 3
)

// Enum value maps for DeliveryQueueKind.
var (
	DeliveryQueueKind_name = map[int32]string{
		0: "DELIVERY_QUEUE_KIND_UNSPECIFIED",
		1: "DELIVERY_QUEUE_KIND_ACCOUNT_PTS",
		2: "DELIVERY_QUEUE_KIND_ACCOUNT_NON_PTS",
		3: "DELIVERY_QUEUE_KIND_CHANNEL_PTS",
	}
	DeliveryQueueKind_value = map[string]int32{
		"DELIVERY_QUEUE_KIND_UNSPECIFIED":     0,
		"DELIVERY_QUEUE_KIND_ACCOUNT_PTS":     1,
		"DELIVERY_QUEUE_KIND_ACCOUNT_NON_PTS": 2,
		"DELIVERY_QUEUE_KIND_CHANNEL_PTS":     3,
	}
)

func (x DeliveryQueueKind) Enum() *DeliveryQueueKind {
	p := new(DeliveryQueueKind)
	*p = x
	return p
}

func (x DeliveryQueueKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryQueueKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_egress_egresspb_egress_proto_enumTypes[0].Descriptor()
}

func (DeliveryQueueKind) Type() protoreflect.EnumType {
	return &file_internal_egress_egresspb_egress_proto_enumTypes[0]
}

func (x DeliveryQueueKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryQueueKind.Descriptor instead.
func (DeliveryQueueKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{0}
}

type PhysicalReceiptOutcome int32

const (
	PhysicalReceiptOutcome_PHYSICAL_RECEIPT_OUTCOME_UNSPECIFIED          PhysicalReceiptOutcome = 0
	PhysicalReceiptOutcome_PHYSICAL_RECEIPT_OUTCOME_WRITTEN              PhysicalReceiptOutcome = 1
	PhysicalReceiptOutcome_PHYSICAL_RECEIPT_OUTCOME_NO_ELIGIBLE_SESSIONS PhysicalReceiptOutcome = 2
	PhysicalReceiptOutcome_PHYSICAL_RECEIPT_OUTCOME_INDETERMINATE        PhysicalReceiptOutcome = 3
	PhysicalReceiptOutcome_PHYSICAL_RECEIPT_OUTCOME_REJECTED             PhysicalReceiptOutcome = 4
)

// Enum value maps for PhysicalReceiptOutcome.
var (
	PhysicalReceiptOutcome_name = map[int32]string{
		0: "PHYSICAL_RECEIPT_OUTCOME_UNSPECIFIED",
		1: "PHYSICAL_RECEIPT_OUTCOME_WRITTEN",
		2: "PHYSICAL_RECEIPT_OUTCOME_NO_ELIGIBLE_SESSIONS",
		3: "PHYSICAL_RECEIPT_OUTCOME_INDETERMINATE",
		4: "PHYSICAL_RECEIPT_OUTCOME_REJECTED",
	}
	PhysicalReceiptOutcome_value = map[string]int32{
		"PHYSICAL_RECEIPT_OUTCOME_UNSPECIFIED":          0,
		"PHYSICAL_RECEIPT_OUTCOME_WRITTEN":              1,
		"PHYSICAL_RECEIPT_OUTCOME_NO_ELIGIBLE_SESSIONS": 2,
		"PHYSICAL_RECEIPT_OUTCOME_INDETERMINATE":        3,
		"PHYSICAL_RECEIPT_OUTCOME_REJECTED":             4,
	}
)

func (x PhysicalReceiptOutcome) Enum() *PhysicalReceiptOutcome {
	p := new(PhysicalReceiptOutcome)
	*p = x
	return p
}

func (x PhysicalReceiptOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhysicalReceiptOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_egress_egresspb_egress_proto_enumTypes[1].Descriptor()
}

func (PhysicalReceiptOutcome) Type() protoreflect.EnumType {
	return &file_internal_egress_egresspb_egress_proto_enumTypes[1]
}

func (x PhysicalReceiptOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhysicalReceiptOutcome.Descriptor instead.
func (PhysicalReceiptOutcome) EnumDescriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{1}
}

type DeliveryEvidenceOutcome int32

const (
	DeliveryEvidenceOutcome_DELIVERY_EVIDENCE_OUTCOME_UNSPECIFIED       DeliveryEvidenceOutcome = 0
	DeliveryEvidenceOutcome_DELIVERY_EVIDENCE_OUTCOME_RECORDED          DeliveryEvidenceOutcome = 1
	DeliveryEvidenceOutcome_DELIVERY_EVIDENCE_OUTCOME_DUPLICATE         DeliveryEvidenceOutcome = 2
	DeliveryEvidenceOutcome_DELIVERY_EVIDENCE_OUTCOME_ALREADY_FINALIZED DeliveryEvidenceOutcome = 3
	DeliveryEvidenceOutcome_DELIVERY_EVIDENCE_OUTCOME_FENCED            DeliveryEvidenceOutcome = 4
	DeliveryEvidenceOutcome_DELIVERY_EVIDENCE_OUTCOME_REJECTED          DeliveryEvidenceOutcome = 5
	DeliveryEvidenceOutcome_DELIVERY_EVIDENCE_OUTCOME_RETRYABLE         DeliveryEvidenceOutcome = 6
)

// Enum value maps for DeliveryEvidenceOutcome.
var (
	DeliveryEvidenceOutcome_name = map[int32]string{
		0: "DELIVERY_EVIDENCE_OUTCOME_UNSPECIFIED",
		1: "DELIVERY_EVIDENCE_OUTCOME_RECORDED",
		2: "DELIVERY_EVIDENCE_OUTCOME_DUPLICATE",
		3: "DELIVERY_EVIDENCE_OUTCOME_ALREADY_FINALIZED",
		4: "DELIVERY_EVIDENCE_OUTCOME_FENCED",
		5: "DELIVERY_EVIDENCE_OUTCOME_REJECTED",
		6: "DELIVERY_EVIDENCE_OUTCOME_RETRYABLE",
	}
	DeliveryEvidenceOutcome_value = map[string]int32{
		"DELIVERY_EVIDENCE_OUTCOME_UNSPECIFIED":       0,
		"DELIVERY_EVIDENCE_OUTCOME_RECORDED":          1,
		"DELIVERY_EVIDENCE_OUTCOME_DUPLICATE":         2,
		"DELIVERY_EVIDENCE_OUTCOME_ALREADY_FINALIZED": 3,
		"DELIVERY_EVIDENCE_OUTCOME_FENCED":            4,
		"DELIVERY_EVIDENCE_OUTCOME_REJECTED":          5,
		"DELIVERY_EVIDENCE_OUTCOME_RETRYABLE":         6,
	}
)

func (x DeliveryEvidenceOutcome) Enum() *DeliveryEvidenceOutcome {
	p := new(DeliveryEvidenceOutcome)
	*p = x
	return p
}

func (x DeliveryEvidenceOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryEvidenceOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_egress_egresspb_egress_proto_enumTypes[2].Descriptor()
}

func (DeliveryEvidenceOutcome) Type() protoreflect.EnumType {
	return &file_internal_egress_egresspb_egress_proto_enumTypes[2]
}

func (x DeliveryEvidenceOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryEvidenceOutcome.Descriptor instead.
func (DeliveryEvidenceOutcome) EnumDescriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{2}
}

type EgressInfoRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *EgressInfoRequest) Reset() {
	*x = EgressInfoRequest{}
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressInfoRequest) ProtoMessage() {}

func (x *EgressInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressInfoRequest.ProtoReflect.Descriptor instead.
func (*EgressInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{0}
}

func (x *EgressInfoRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EgressInfoRequest) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *EgressInfoRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type EgressInfoResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Implementation              string                 `protobuf:"bytes,4,opt,name=implementation,proto3" json:"implementation,omitempty"`
	InstanceId                  string                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Error                       string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *EgressInfoResponse) Reset() {
	*x = EgressInfoResponse{}
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressInfoResponse) ProtoMessage() {}

func (x *EgressInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressInfoResponse.ProtoReflect.Descriptor instead.
func (*EgressInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{1}
}

func (x *EgressInfoResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EgressInfoResponse) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *EgressInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *EgressInfoResponse) GetImplementation() string {
	if x != nil {
		return x.Implementation
	}
	return ""
}

func (x *EgressInfoResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *EgressInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// All repeated fields are positional columns and must have identical lengths.
// A 128-bit batch id uses two fixed64 columns to avoid one bytes allocation per
// receipt in the hot path.
type PhysicalReceiptBatchRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	QueueKinds          []uint32               `protobuf:"varint,1,rep,packed,name=queue_kinds,json=queueKinds,proto3" json:"queue_kinds,omitempty"`
	StreamIds           []int64                `protobuf:"varint,2,rep,packed,name=stream_ids,json=streamIds,proto3" json:"stream_ids,omitempty"`
	ItemIds             []int64                `protobuf:"varint,3,rep,packed,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	Sequences           []int64                `protobuf:"varint,4,rep,packed,name=sequences,proto3" json:"sequences,omitempty"`
	LeaseFences         []uint64               `protobuf:"fixed64,5,rep,packed,name=lease_fences,json=leaseFences,proto3" json:"lease_fences,omitempty"`
	Attempts            []uint32               `protobuf:"varint,6,rep,packed,name=attempts,proto3" json:"attempts,omitempty"`
	BatchIdLow          []uint64               `protobuf:"fixed64,7,rep,packed,name=batch_id_low,json=batchIdLow,proto3" json:"batch_id_low,omitempty"`
	BatchIdHigh         []uint64               `protobuf:"fixed64,8,rep,packed,name=batch_id_high,json=batchIdHigh,proto3" json:"batch_id_high,omitempty"`
	SourceInstanceIds   []string               `protobuf:"bytes,9,rep,name=source_instance_ids,json=sourceInstanceIds,proto3" json:"source_instance_ids,omitempty"`
	TargetInstanceIds   []string               `protobuf:"bytes,10,rep,name=target_instance_ids,json=targetInstanceIds,proto3" json:"target_instance_ids,omitempty"`
	Outcomes            []uint32               `protobuf:"varint,11,rep,packed,name=outcomes,proto3" json:"outcomes,omitempty"`
	EligibleSessions    []uint32               `protobuf:"varint,12,rep,packed,name=eligible_sessions,json=eligibleSessions,proto3" json:"eligible_sessions,omitempty"`
	WrittenSessions     []uint32               `protobuf:"varint,13,rep,packed,name=written_sessions,json=writtenSessions,proto3" json:"written_sessions,omitempty"`
	FirstServerMsgIds   []int64                `protobuf:"varint,14,rep,packed,name=first_server_msg_ids,json=firstServerMsgIds,proto3" json:"first_server_msg_ids,omitempty"`
	ObservedAtUnixNanos []int64                `protobuf:"varint,15,rep,packed,name=observed_at_unix_nanos,json=observedAtUnixNanos,proto3" json:"observed_at_unix_nanos,omitempty"`
	DetailCodes         []uint32               `protobuf:"varint,16,rep,packed,name=detail_codes,json=detailCodes,proto3" json:"detail_codes,omitempty"`
	CommandIdLow        []uint64               `protobuf:"fixed64,17,rep,packed,name=command_id_low,json=commandIdLow,proto3" json:"command_id_low,omitempty"`
	CommandIdHigh       []uint64               `protobuf:"fixed64,18,rep,packed,name=command_id_high,json=commandIdHigh,proto3" json:"command_id_high,omitempty"`
	TargetUserIds       []int64                `protobuf:"varint,19,rep,packed,name=target_user_ids,json=targetUserIds,proto3" json:"target_user_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PhysicalReceiptBatchRequest) Reset() {
	*x = PhysicalReceiptBatchRequest{}
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalReceiptBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalReceiptBatchRequest) ProtoMessage() {}

func (x *PhysicalReceiptBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalReceiptBatchRequest.ProtoReflect.Descriptor instead.
func (*PhysicalReceiptBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{2}
}

func (x *PhysicalReceiptBatchRequest) GetQueueKinds() []uint32 {
	if x != nil {
		return x.QueueKinds
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetStreamIds() []int64 {
	if x != nil {
		return x.StreamIds
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetItemIds() []int64 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetSequences() []int64 {
	if x != nil {
		return x.Sequences
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetLeaseFences() []uint64 {
	if x != nil {
		return x.LeaseFences
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetAttempts() []uint32 {
	if x != nil {
		return x.Attempts
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetBatchIdLow() []uint64 {
	if x != nil {
		return x.BatchIdLow
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetBatchIdHigh() []uint64 {
	if x != nil {
		return x.BatchIdHigh
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetSourceInstanceIds() []string {
	if x != nil {
		return x.SourceInstanceIds
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetTargetInstanceIds() []string {
	if x != nil {
		return x.TargetInstanceIds
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetOutcomes() []uint32 {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetEligibleSessions() []uint32 {
	if x != nil {
		return x.EligibleSessions
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetWrittenSessions() []uint32 {
	if x != nil {
		return x.WrittenSessions
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetFirstServerMsgIds() []int64 {
	if x != nil {
		return x.FirstServerMsgIds
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetObservedAtUnixNanos() []int64 {
	if x != nil {
		return x.ObservedAtUnixNanos
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetDetailCodes() []uint32 {
	if x != nil {
		return x.DetailCodes
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetCommandIdLow() []uint64 {
	if x != nil {
		return x.CommandIdLow
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetCommandIdHigh() []uint64 {
	if x != nil {
		return x.CommandIdHigh
	}
	return nil
}

func (x *PhysicalReceiptBatchRequest) GetTargetUserIds() []int64 {
	if x != nil {
		return x.TargetUserIds
	}
	return nil
}

type ClientAckBatchRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueueKinds        []uint32               `protobuf:"varint,1,rep,packed,name=queue_kinds,json=queueKinds,proto3" json:"queue_kinds,omitempty"`
	StreamIds         []int64                `protobuf:"varint,2,rep,packed,name=stream_ids,json=streamIds,proto3" json:"stream_ids,omitempty"`
	ItemIds           []int64                `protobuf:"varint,3,rep,packed,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	Sequences         []int64                `protobuf:"varint,4,rep,packed,name=sequences,proto3" json:"sequences,omitempty"`
	LeaseFences       []uint64               `protobuf:"fixed64,5,rep,packed,name=lease_fences,json=leaseFences,proto3" json:"lease_fences,omitempty"`
	Attempts          []uint32               `protobuf:"varint,6,rep,packed,name=attempts,proto3" json:"attempts,omitempty"`
	BatchIdLow        []uint64               `protobuf:"fixed64,7,rep,packed,name=batch_id_low,json=batchIdLow,proto3" json:"batch_id_low,omitempty"`
	BatchIdHigh       []uint64               `protobuf:"fixed64,8,rep,packed,name=batch_id_high,json=batchIdHigh,proto3" json:"batch_id_high,omitempty"`
	TargetInstanceIds []string               `protobuf:"bytes,9,rep,name=target_instance_ids,json=targetInstanceIds,proto3" json:"target_instance_ids,omitempty"`
	AuthKeyIds        []uint64               `protobuf:"fixed64,10,rep,packed,name=auth_key_ids,json=authKeyIds,proto3" json:"auth_key_ids,omitempty"`
	SessionIds        []int64                `protobuf:"fixed64,11,rep,packed,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	ServerMsgIds      []int64                `protobuf:"varint,12,rep,packed,name=server_msg_ids,json=serverMsgIds,proto3" json:"server_msg_ids,omitempty"`
	AckedAtUnixNanos  []int64                `protobuf:"varint,13,rep,packed,name=acked_at_unix_nanos,json=ackedAtUnixNanos,proto3" json:"acked_at_unix_nanos,omitempty"`
	CommandIdLow      []uint64               `protobuf:"fixed64,14,rep,packed,name=command_id_low,json=commandIdLow,proto3" json:"command_id_low,omitempty"`
	CommandIdHigh     []uint64               `protobuf:"fixed64,15,rep,packed,name=command_id_high,json=commandIdHigh,proto3" json:"command_id_high,omitempty"`
	TargetUserIds     []int64                `protobuf:"varint,16,rep,packed,name=target_user_ids,json=targetUserIds,proto3" json:"target_user_ids,omitempty"`
	SourceInstanceIds []string               `protobuf:"bytes,17,rep,name=source_instance_ids,json=sourceInstanceIds,proto3" json:"source_instance_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientAckBatchRequest) Reset() {
	*x = ClientAckBatchRequest{}
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAckBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAckBatchRequest) ProtoMessage() {}

func (x *ClientAckBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAckBatchRequest.ProtoReflect.Descriptor instead.
func (*ClientAckBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{3}
}

func (x *ClientAckBatchRequest) GetQueueKinds() []uint32 {
	if x != nil {
		return x.QueueKinds
	}
	return nil
}

func (x *ClientAckBatchRequest) GetStreamIds() []int64 {
	if x != nil {
		return x.StreamIds
	}
	return nil
}

func (x *ClientAckBatchRequest) GetItemIds() []int64 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *ClientAckBatchRequest) GetSequences() []int64 {
	if x != nil {
		return x.Sequences
	}
	return nil
}

func (x *ClientAckBatchRequest) GetLeaseFences() []uint64 {
	if x != nil {
		return x.LeaseFences
	}
	return nil
}

func (x *ClientAckBatchRequest) GetAttempts() []uint32 {
	if x != nil {
		return x.Attempts
	}
	return nil
}

func (x *ClientAckBatchRequest) GetBatchIdLow() []uint64 {
	if x != nil {
		return x.BatchIdLow
	}
	return nil
}

func (x *ClientAckBatchRequest) GetBatchIdHigh() []uint64 {
	if x != nil {
		return x.BatchIdHigh
	}
	return nil
}

func (x *ClientAckBatchRequest) GetTargetInstanceIds() []string {
	if x != nil {
		return x.TargetInstanceIds
	}
	return nil
}

func (x *ClientAckBatchRequest) GetAuthKeyIds() []uint64 {
	if x != nil {
		return x.AuthKeyIds
	}
	return nil
}

func (x *ClientAckBatchRequest) GetSessionIds() []int64 {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *ClientAckBatchRequest) GetServerMsgIds() []int64 {
	if x != nil {
		return x.ServerMsgIds
	}
	return nil
}

func (x *ClientAckBatchRequest) GetAckedAtUnixNanos() []int64 {
	if x != nil {
		return x.AckedAtUnixNanos
	}
	return nil
}

func (x *ClientAckBatchRequest) GetCommandIdLow() []uint64 {
	if x != nil {
		return x.CommandIdLow
	}
	return nil
}

func (x *ClientAckBatchRequest) GetCommandIdHigh() []uint64 {
	if x != nil {
		return x.CommandIdHigh
	}
	return nil
}

func (x *ClientAckBatchRequest) GetTargetUserIds() []int64 {
	if x != nil {
		return x.TargetUserIds
	}
	return nil
}

func (x *ClientAckBatchRequest) GetSourceInstanceIds() []string {
	if x != nil {
		return x.SourceInstanceIds
	}
	return nil
}

type DeliveryEvidenceBatchResponse struct {
	state    protoimpl.MessageState    `protogen:"open.v1"`
	Outcomes []DeliveryEvidenceOutcome `protobuf:"varint,1,rep,packed,name=outcomes,proto3,enum=telesrv.egress.v3.DeliveryEvidenceOutcome" json:"outcomes,omitempty"`
	// Details are exceptional diagnostics only. The success path leaves this
	// sparse map empty and relies on typed outcomes.
	Details       map[uint32]string `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryEvidenceBatchResponse) Reset() {
	*x = DeliveryEvidenceBatchResponse{}
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryEvidenceBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryEvidenceBatchResponse) ProtoMessage() {}

func (x *DeliveryEvidenceBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_egress_egresspb_egress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryEvidenceBatchResponse.ProtoReflect.Descriptor instead.
func (*DeliveryEvidenceBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_egress_egresspb_egress_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryEvidenceBatchResponse) GetOutcomes() []DeliveryEvidenceOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *DeliveryEvidenceBatchResponse) GetDetails() map[uint32]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_internal_egress_egresspb_egress_proto protoreflect.FileDescriptor

const file_internal_egress_egresspb_egress_proto_rawDesc = "" +
	"\n" +
	"%internal/egress/egresspb/egress.proto\x12\x11telesrv.egress.v3\"\xa7\x01\n" +
	"\x11EgressInfoRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x87\x02\n" +
	"\x12EgressInfoResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12&\n" +
	"\x0eimplementation\x18\x04 \x01(\tR\x0eimplementation\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xee\x05\n" +
	"\x1bPhysicalReceiptBatchRequest\x12\x1f\n" +
	"\vqueue_kinds\x18\x01 \x03(\rR\n" +
	"queueKinds\x12\x1d\n" +
	"\n" +
	"stream_ids\x18\x02 \x03(\x03R\tstreamIds\x12\x19\n" +
	"\bitem_ids\x18\x03 \x03(\x03R\aitemIds\x12\x1c\n" +
	"\tsequences\x18\x04 \x03(\x03R\tsequences\x12!\n" +
	"\flease_fences\x18\x05 \x03(\x06R\vleaseFences\x12\x1a\n" +
	"\battempts\x18\x06 \x03(\rR\battempts\x12 \n" +
	"\fbatch_id_low\x18\a \x03(\x06R\n" +
	"batchIdLow\x12\"\n" +
	"\rbatch_id_high\x18\b \x03(\x06R\vbatchIdHigh\x12.\n" +
	"\x13source_instance_ids\x18\t \x03(\tR\x11sourceInstanceIds\x12.\n" +
	"\x13target_instance_ids\x18\n" +
	" \x03(\tR\x11targetInstanceIds\x12\x1a\n" +
	"\boutcomes\x18\v \x03(\rR\boutcomes\x12+\n" +
	"\x11eligible_sessions\x18\f \x03(\rR\x10eligibleSessions\x12)\n" +
	"\x10written_sessions\x18\r \x03(\rR\x0fwrittenSessions\x12/\n" +
	"\x14first_server_msg_ids\x18\x0e \x03(\x03R\x11firstServerMsgIds\x123\n" +
	"\x16observed_at_unix_nanos\x18\x0f \x03(\x03R\x13observedAtUnixNanos\x12!\n" +
	"\fdetail_codes\x18\x10 \x03(\rR\vdetailCodes\x12$\n" +
	"\x0ecommand_id_low\x18\x11 \x03(\x06R\fcommandIdLow\x12&\n" +
	"\x0fcommand_id_high\x18\x12 \x03(\x06R\rcommandIdHigh\x12&\n" +
	"\x0ftarget_user_ids\x18\x13 \x03(\x03R\rtargetUserIds\"\x83\x05\n" +
	"\x15ClientAckBatchRequest\x12\x1f\n" +
	"\vqueue_kinds\x18\x01 \x03(\rR\n" +
	"queueKinds\x12\x1d\n" +
	"\n" +
	"stream_ids\x18\x02 \x03(\x03R\tstreamIds\x12\x19\n" +
	"\bitem_ids\x18\x03 \x03(\x03R\aitemIds\x12\x1c\n" +
	"\tsequences\x18\x04 \x03(\x03R\tsequences\x12!\n" +
	"\flease_fences\x18\x05 \x03(\x06R\vleaseFences\x12\x1a\n" +
	"\battempts\x18\x06 \x03(\rR\battempts\x12 \n" +
	"\fbatch_id_low\x18\a \x03(\x06R\n" +
	"batchIdLow\x12\"\n" +
	"\rbatch_id_high\x18\b \x03(\x06R\vbatchIdHigh\x12.\n" +
	"\x13target_instance_ids\x18\t \x03(\tR\x11targetInstanceIds\x12 \n" +
	"\fauth_key_ids\x18\n" +
	" \x03(\x06R\n" +
	"authKeyIds\x12\x1f\n" +
	"\vsession_ids\x18\v \x03(\x10R\n" +
	"sessionIds\x12$\n" +
	"\x0eserver_msg_ids\x18\f \x03(\x03R\fserverMsgIds\x12-\n" +
	"\x13acked_at_unix_nanos\x18\r \x03(\x03R\x10ackedAtUnixNanos\x12$\n" +
	"\x0ecommand_id_low\x18\x0e \x03(\x06R\fcommandIdLow\x12&\n" +
	"\x0fcommand_id_high\x18\x0f \x03(\x06R\rcommandIdHigh\x12&\n" +
	"\x0ftarget_user_ids\x18\x10 \x03(\x03R\rtargetUserIds\x12.\n" +
	"\x13source_instance_ids\x18\x11 \x03(\tR\x11sourceInstanceIds\"\xfc\x01\n" +
	"\x1dDeliveryEvidenceBatchResponse\x12F\n" +
	"\boutcomes\x18\x01 \x03(\x0e2*.telesrv.egress.v3.DeliveryEvidenceOutcomeR\boutcomes\x12W\n" +
	"\adetails\x18\x02 \x03(\v2=.telesrv.egress.v3.DeliveryEvidenceBatchResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xab\x01\n" +
	"\x11DeliveryQueueKind\x12#\n" +
	"\x1fDELIVERY_QUEUE_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fDELIVERY_QUEUE_KIND_ACCOUNT_PTS\x10\x01\x12'\n" +
	"#DELIVERY_QUEUE_KIND_ACCOUNT_NON_PTS\x10\x02\x12#\n" +
	"\x1fDELIVERY_QUEUE_KIND_CHANNEL_PTS\x10\x03*\xee\x01\n" +
	"\x16PhysicalReceiptOutcome\x12(\n" +
	"$PHYSICAL_RECEIPT_OUTCOME_UNSPECIFIED\x10\x00\x12$\n" +
	" PHYSICAL_RECEIPT_OUTCOME_WRITTEN\x10\x01\x121\n" +
	"-PHYSICAL_RECEIPT_OUTCOME_NO_ELIGIBLE_SESSIONS\x10\x02\x12*\n" +
	"&PHYSICAL_RECEIPT_OUTCOME_INDETERMINATE\x10\x03\x12%\n" +
	"!PHYSICAL_RECEIPT_OUTCOME_REJECTED\x10\x04*\xbd\x02\n" +
	"\x17DeliveryEvidenceOutcome\x12)\n" +
	"%DELIVERY_EVIDENCE_OUTCOME_UNSPECIFIED\x10\x00\x12&\n" +
	"\"DELIVERY_EVIDENCE_OUTCOME_RECORDED\x10\x01\x12'\n" +
	"#DELIVERY_EVIDENCE_OUTCOME_DUPLICATE\x10\x02\x12/\n" +
	"+DELIVERY_EVIDENCE_OUTCOME_ALREADY_FINALIZED\x10\x03\x12$\n" +
	" DELIVERY_EVIDENCE_OUTCOME_FENCED\x10\x04\x12&\n" +
	"\"DELIVERY_EVIDENCE_OUTCOME_REJECTED\x10\x05\x12'\n" +
	"#DELIVERY_EVIDENCE_OUTCOME_RETRYABLE\x10\x062\xdb\x02\n" +
	"\x15EgressDeliveryService\x12V\n" +
	"\aGetInfo\x12$.telesrv.egress.v3.EgressInfoRequest\x1a%.telesrv.egress.v3.EgressInfoResponse\x12z\n" +
	"\x16ReportPhysicalReceipts\x12..telesrv.egress.v3.PhysicalReceiptBatchRequest\x1a0.telesrv.egress.v3.DeliveryEvidenceBatchResponse\x12n\n" +
	"\x10ReportClientAcks\x12(.telesrv.egress.v3.ClientAckBatchRequest\x1a0.telesrv.egress.v3.DeliveryEvidenceBatchResponseB+Z)telesrv/internal/egress/egresspb;egresspbb\x06proto3"

var (
	file_internal_egress_egresspb_egress_proto_rawDescOnce sync.Once
	file_internal_egress_egresspb_egress_proto_rawDescData []byte
)

func file_internal_egress_egresspb_egress_proto_rawDescGZIP() []byte {
	file_internal_egress_egresspb_egress_proto_rawDescOnce.Do(func() {
		file_internal_egress_egresspb_egress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_egress_egresspb_egress_proto_rawDesc), len(file_internal_egress_egresspb_egress_proto_rawDesc)))
	})
	return file_internal_egress_egresspb_egress_proto_rawDescData
}

var file_internal_egress_egresspb_egress_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_egress_egresspb_egress_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_egress_egresspb_egress_proto_goTypes = []any{
	(DeliveryQueueKind)(0),                // 0: telesrv.egress.v3.DeliveryQueueKind
	(PhysicalReceiptOutcome)(0),           // 1: telesrv.egress.v3.PhysicalReceiptOutcome
	(DeliveryEvidenceOutcome)(0),          // 2: telesrv.egress.v3.DeliveryEvidenceOutcome
	(*EgressInfoRequest)(nil),             // 3: telesrv.egress.v3.EgressInfoRequest
	(*EgressInfoResponse)(nil),            // 4: telesrv.egress.v3.EgressInfoResponse
	(*PhysicalReceiptBatchRequest)(nil),   // 5: telesrv.egress.v3.PhysicalReceiptBatchRequest
	(*ClientAckBatchRequest)(nil),         // 6: telesrv.egress.v3.ClientAckBatchRequest
	(*DeliveryEvidenceBatchResponse)(nil), // 7: telesrv.egress.v3.DeliveryEvidenceBatchResponse
	nil,                                   // 8: telesrv.egress.v3.DeliveryEvidenceBatchResponse.DetailsEntry
}
var file_internal_egress_egresspb_egress_proto_depIdxs = []int32{
	2, // 0: telesrv.egress.v3.DeliveryEvidenceBatchResponse.outcomes:type_name -> telesrv.egress.v3.DeliveryEvidenceOutcome
	8, // 1: telesrv.egress.v3.DeliveryEvidenceBatchResponse.details:type_name -> telesrv.egress.v3.DeliveryEvidenceBatchResponse.DetailsEntry
	3, // 2: telesrv.egress.v3.EgressDeliveryService.GetInfo:input_type -> telesrv.egress.v3.EgressInfoRequest
	5, // 3: telesrv.egress.v3.EgressDeliveryService.ReportPhysicalReceipts:input_type -> telesrv.egress.v3.PhysicalReceiptBatchRequest
	6, // 4: telesrv.egress.v3.EgressDeliveryService.ReportClientAcks:input_type -> telesrv.egress.v3.ClientAckBatchRequest
	4, // 5: telesrv.egress.v3.EgressDeliveryService.GetInfo:output_type -> telesrv.egress.v3.EgressInfoResponse
	7, // 6: telesrv.egress.v3.EgressDeliveryService.ReportPhysicalReceipts:output_type -> telesrv.egress.v3.DeliveryEvidenceBatchResponse
	7, // 7: telesrv.egress.v3.EgressDeliveryService.ReportClientAcks:output_type -> telesrv.egress.v3.DeliveryEvidenceBatchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_egress_egresspb_egress_proto_init() }
func file_internal_egress_egresspb_egress_proto_init() {
	if File_internal_egress_egresspb_egress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_egress_egresspb_egress_proto_rawDesc), len(file_internal_egress_egresspb_egress_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_egress_egresspb_egress_proto_goTypes,
		DependencyIndexes: file_internal_egress_egresspb_egress_proto_depIdxs,
		EnumInfos:         file_internal_egress_egresspb_egress_proto_enumTypes,
		MessageInfos:      file_internal_egress_egresspb_egress_proto_msgTypes,
	}.Build()
	File_internal_egress_egresspb_egress_proto = out.File
	file_internal_egress_egresspb_egress_proto_goTypes = nil
	file_internal_egress_egresspb_egress_proto_depIdxs = nil
}
