// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: internal/egress/egresspb/egress.proto

package egresspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EgressDeliveryService_GetInfo_FullMethodName                = "/telesrv.egress.v3.EgressDeliveryService/GetInfo"
	EgressDeliveryService_ReportPhysicalReceipts_FullMethodName = "/telesrv.egress.v3.EgressDeliveryService/ReportPhysicalReceipts"
	EgressDeliveryService_ReportClientAcks_FullMethodName       = "/telesrv.egress.v3.EgressDeliveryService/ReportClientAcks"
)

// EgressDeliveryServiceClient is the client API for EgressDeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EgressDeliveryServiceClient interface {
	GetInfo(ctx context.Context, in *EgressInfoRequest, opts ...grpc.CallOption) (*EgressInfoResponse, error)
	ReportPhysicalReceipts(ctx context.Context, in *PhysicalReceiptBatchRequest, opts ...grpc.CallOption) (*DeliveryEvidenceBatchResponse, error)
	ReportClientAcks(ctx context.Context, in *ClientAckBatchRequest, opts ...grpc.CallOption) (*DeliveryEvidenceBatchResponse, error)
}

type egressDeliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEgressDeliveryServiceClient(cc grpc.ClientConnInterface) EgressDeliveryServiceClient {
	return &egressDeliveryServiceClient{cc}
}

func (c *egressDeliveryServiceClient) GetInfo(ctx context.Context, in *EgressInfoRequest, opts ...grpc.CallOption) (*EgressInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EgressInfoResponse)
	err := c.cc.Invoke(ctx, EgressDeliveryService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressDeliveryServiceClient) ReportPhysicalReceipts(ctx context.Context, in *PhysicalReceiptBatchRequest, opts ...grpc.CallOption) (*DeliveryEvidenceBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryEvidenceBatchResponse)
	err := c.cc.Invoke(ctx, EgressDeliveryService_ReportPhysicalReceipts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressDeliveryServiceClient) ReportClientAcks(ctx context.Context, in *ClientAckBatchRequest, opts ...grpc.CallOption) (*DeliveryEvidenceBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryEvidenceBatchResponse)
	err := c.cc.Invoke(ctx, EgressDeliveryService_ReportClientAcks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgressDeliveryServiceServer is the server API for EgressDeliveryService service.
// All implementations must embed UnimplementedEgressDeliveryServiceServer
// for forward compatibility.
type EgressDeliveryServiceServer interface {
	GetInfo(context.Context, *EgressInfoRequest) (*EgressInfoResponse, error)
	ReportPhysicalReceipts(context.Context, *PhysicalReceiptBatchRequest) (*DeliveryEvidenceBatchResponse, error)
	ReportClientAcks(context.Context, *ClientAckBatchRequest) (*DeliveryEvidenceBatchResponse, error)
	mustEmbedUnimplementedEgressDeliveryServiceServer()
}

// UnimplementedEgressDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgressDeliveryServiceServer struct{}

func (UnimplementedEgressDeliveryServiceServer) GetInfo(context.Context, *EgressInfoRequest) (*EgressInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedEgressDeliveryServiceServer) ReportPhysicalReceipts(context.Context, *PhysicalReceiptBatchRequest) (*DeliveryEvidenceBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportPhysicalReceipts not implemented")
}
func (UnimplementedEgressDeliveryServiceServer) ReportClientAcks(context.Context, *ClientAckBatchRequest) (*DeliveryEvidenceBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportClientAcks not implemented")
}
func (UnimplementedEgressDeliveryServiceServer) mustEmbedUnimplementedEgressDeliveryServiceServer() {}
func (UnimplementedEgressDeliveryServiceServer) testEmbeddedByValue()                               {}

// UnsafeEgressDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgressDeliveryServiceServer will
// result in compilation errors.
type UnsafeEgressDeliveryServiceServer interface {
	mustEmbedUnimplementedEgressDeliveryServiceServer()
}

func RegisterEgressDeliveryServiceServer(s grpc.ServiceRegistrar, srv EgressDeliveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedEgressDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EgressDeliveryService_ServiceDesc, srv)
}

func _EgressDeliveryService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EgressInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressDeliveryServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressDeliveryService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressDeliveryServiceServer).GetInfo(ctx, req.(*EgressInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressDeliveryService_ReportPhysicalReceipts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhysicalReceiptBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressDeliveryServiceServer).ReportPhysicalReceipts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressDeliveryService_ReportPhysicalReceipts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressDeliveryServiceServer).ReportPhysicalReceipts(ctx, req.(*PhysicalReceiptBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EgressDeliveryService_ReportClientAcks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientAckBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressDeliveryServiceServer).ReportClientAcks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressDeliveryService_ReportClientAcks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressDeliveryServiceServer).ReportClientAcks(ctx, req.(*ClientAckBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EgressDeliveryService_ServiceDesc is the grpc.ServiceDesc for EgressDeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EgressDeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telesrv.egress.v3.EgressDeliveryService",
	HandlerType: (*EgressDeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _EgressDeliveryService_GetInfo_Handler,
		},
		{
			MethodName: "ReportPhysicalReceipts",
			Handler:    _EgressDeliveryService_ReportPhysicalReceipts_Handler,
		},
		{
			MethodName: "ReportClientAcks",
			Handler:    _EgressDeliveryService_ReportClientAcks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/egress/egresspb/egress.proto",
}
