// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: internal/filedata/filedatapb/filedata.proto

package filedatapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorKind int32

const (
	ErrorKind_ERROR_KIND_NONE                  ErrorKind = 0
	ErrorKind_ERROR_KIND_FILE_PART_INVALID     ErrorKind = 1
	ErrorKind_ERROR_KIND_FILE_PARTS_INVALID    ErrorKind = 2
	ErrorKind_ERROR_KIND_FILE_PART_TOO_BIG     ErrorKind = 3
	ErrorKind_ERROR_KIND_UPLOAD_QUOTA_EXCEEDED ErrorKind = 4
	ErrorKind_ERROR_KIND_STORAGE_FULL          ErrorKind = 5
	ErrorKind_ERROR_KIND_PHOTO_INVALID         ErrorKind = 6
	ErrorKind_ERROR_KIND_DOCUMENT_INVALID      ErrorKind = 7
)

// Enum value maps for ErrorKind.
var (
	ErrorKind_name = map[int32]string{
		0: "ERROR_KIND_NONE",
		1: "ERROR_KIND_FILE_PART_INVALID",
		2: "ERROR_KIND_FILE_PARTS_INVALID",
		3: "ERROR_KIND_FILE_PART_TOO_BIG",
		4: "ERROR_KIND_UPLOAD_QUOTA_EXCEEDED",
		5: "ERROR_KIND_STORAGE_FULL",
		6: "ERROR_KIND_PHOTO_INVALID",
		7: "ERROR_KIND_DOCUMENT_INVALID",
	}
	ErrorKind_value = map[string]int32{
		"ERROR_KIND_NONE":                  0,
		"ERROR_KIND_FILE_PART_INVALID":     1,
		"ERROR_KIND_FILE_PARTS_INVALID":    2,
		"ERROR_KIND_FILE_PART_TOO_BIG":     3,
		"ERROR_KIND_UPLOAD_QUOTA_EXCEEDED": 4,
		"ERROR_KIND_STORAGE_FULL":          5,
		"ERROR_KIND_PHOTO_INVALID":         6,
		"ERROR_KIND_DOCUMENT_INVALID":      7,
	}
)

func (x ErrorKind) Enum() *ErrorKind {
	p := new(ErrorKind)
	*p = x
	return p
}

func (x ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_filedata_filedatapb_filedata_proto_enumTypes[0].Descriptor()
}

func (ErrorKind) Type() protoreflect.EnumType {
	return &file_internal_filedata_filedatapb_filedata_proto_enumTypes[0]
}

func (x ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorKind.Descriptor instead.
func (ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{0}
}

type FileDataInfoRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *FileDataInfoRequest) Reset() {
	*x = FileDataInfoRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDataInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDataInfoRequest) ProtoMessage() {}

func (x *FileDataInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDataInfoRequest.ProtoReflect.Descriptor instead.
func (*FileDataInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{0}
}

func (x *FileDataInfoRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *FileDataInfoRequest) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *FileDataInfoRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type FileDataInfoResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion             uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MinSupportedProtocolVersion uint32                 `protobuf:"varint,2,opt,name=min_supported_protocol_version,json=minSupportedProtocolVersion,proto3" json:"min_supported_protocol_version,omitempty"`
	Capabilities                []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Implementation              string                 `protobuf:"bytes,4,opt,name=implementation,proto3" json:"implementation,omitempty"`
	InstanceId                  string                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Backend                     string                 `protobuf:"bytes,6,opt,name=backend,proto3" json:"backend,omitempty"`
	Error                       string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *FileDataInfoResponse) Reset() {
	*x = FileDataInfoResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDataInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDataInfoResponse) ProtoMessage() {}

func (x *FileDataInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDataInfoResponse.ProtoReflect.Descriptor instead.
func (*FileDataInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{1}
}

func (x *FileDataInfoResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *FileDataInfoResponse) GetMinSupportedProtocolVersion() uint32 {
	if x != nil {
		return x.MinSupportedProtocolVersion
	}
	return 0
}

func (x *FileDataInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *FileDataInfoResponse) GetImplementation() string {
	if x != nil {
		return x.Implementation
	}
	return ""
}

func (x *FileDataInfoResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *FileDataInfoResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *FileDataInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SaveFilePartRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserId    int64                  `protobuf:"varint,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	FileId         int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FilePart       int32                  `protobuf:"varint,3,opt,name=file_part,json=filePart,proto3" json:"file_part,omitempty"`
	FileTotalParts int32                  `protobuf:"varint,4,opt,name=file_total_parts,json=fileTotalParts,proto3" json:"file_total_parts,omitempty"`
	Big            bool                   `protobuf:"varint,5,opt,name=big,proto3" json:"big,omitempty"`
	Data           []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SaveFilePartRequest) Reset() {
	*x = SaveFilePartRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFilePartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFilePartRequest) ProtoMessage() {}

func (x *SaveFilePartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFilePartRequest.ProtoReflect.Descriptor instead.
func (*SaveFilePartRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{2}
}

func (x *SaveFilePartRequest) GetOwnerUserId() int64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *SaveFilePartRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *SaveFilePartRequest) GetFilePart() int32 {
	if x != nil {
		return x.FilePart
	}
	return 0
}

func (x *SaveFilePartRequest) GetFileTotalParts() int32 {
	if x != nil {
		return x.FileTotalParts
	}
	return 0
}

func (x *SaveFilePartRequest) GetBig() bool {
	if x != nil {
		return x.Big
	}
	return false
}

func (x *SaveFilePartRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SaveFilePartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saved         bool                   `protobuf:"varint,1,opt,name=saved,proto3" json:"saved,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind     ErrorKind              `protobuf:"varint,3,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFilePartResponse) Reset() {
	*x = SaveFilePartResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFilePartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFilePartResponse) ProtoMessage() {}

func (x *SaveFilePartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFilePartResponse.ProtoReflect.Descriptor instead.
func (*SaveFilePartResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{3}
}

func (x *SaveFilePartResponse) GetSaved() bool {
	if x != nil {
		return x.Saved
	}
	return false
}

func (x *SaveFilePartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SaveFilePartResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationKey   string                 `protobuf:"bytes,1,opt,name=location_key,json=locationKey,proto3" json:"location_key,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileRequest) GetLocationKey() string {
	if x != nil {
		return x.LocationKey
	}
	return ""
}

func (x *GetFileRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetFileRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFileResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Found                bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Data                 []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	MimeType             string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Total                int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Error                string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind            ErrorKind              `protobuf:"varint,6,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	ImmutableBackend     string                 `protobuf:"bytes,7,opt,name=immutable_backend,json=immutableBackend,proto3" json:"immutable_backend,omitempty"`
	ImmutableObjectKey   string                 `protobuf:"bytes,8,opt,name=immutable_object_key,json=immutableObjectKey,proto3" json:"immutable_object_key,omitempty"`
	ImmutableOffset      int64                  `protobuf:"varint,9,opt,name=immutable_offset,json=immutableOffset,proto3" json:"immutable_offset,omitempty"`
	ImmutableLength      int32                  `protobuf:"varint,10,opt,name=immutable_length,json=immutableLength,proto3" json:"immutable_length,omitempty"`
	ImmutableRangeSha256 []byte                 `protobuf:"bytes,11,opt,name=immutable_range_sha256,json=immutableRangeSha256,proto3" json:"immutable_range_sha256,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetFileResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetFileResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetFileResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

func (x *GetFileResponse) GetImmutableBackend() string {
	if x != nil {
		return x.ImmutableBackend
	}
	return ""
}

func (x *GetFileResponse) GetImmutableObjectKey() string {
	if x != nil {
		return x.ImmutableObjectKey
	}
	return ""
}

func (x *GetFileResponse) GetImmutableOffset() int64 {
	if x != nil {
		return x.ImmutableOffset
	}
	return 0
}

func (x *GetFileResponse) GetImmutableLength() int32 {
	if x != nil {
		return x.ImmutableLength
	}
	return 0
}

func (x *GetFileResponse) GetImmutableRangeSha256() []byte {
	if x != nil {
		return x.ImmutableRangeSha256
	}
	return nil
}

type GetFileHashesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationKey   string                 `protobuf:"bytes,1,opt,name=location_key,json=locationKey,proto3" json:"location_key,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileHashesRequest) Reset() {
	*x = GetFileHashesRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileHashesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileHashesRequest) ProtoMessage() {}

func (x *GetFileHashesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileHashesRequest.ProtoReflect.Descriptor instead.
func (*GetFileHashesRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileHashesRequest) GetLocationKey() string {
	if x != nil {
		return x.LocationKey
	}
	return ""
}

func (x *GetFileHashesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FileHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileHash) Reset() {
	*x = FileHash{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHash) ProtoMessage() {}

func (x *FileHash) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHash.ProtoReflect.Descriptor instead.
func (*FileHash) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{7}
}

func (x *FileHash) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileHash) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FileHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetFileHashesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Hashes        []*FileHash            `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind     ErrorKind              `protobuf:"varint,4,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileHashesResponse) Reset() {
	*x = GetFileHashesResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileHashesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileHashesResponse) ProtoMessage() {}

func (x *GetFileHashesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileHashesResponse.ProtoReflect.Descriptor instead.
func (*GetFileHashesResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileHashesResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetFileHashesResponse) GetHashes() []*FileHash {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *GetFileHashesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetFileHashesResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

type MaterializeUploadBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserId   int64                  `protobuf:"varint,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	FileId        int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ExpectedParts int32                  `protobuf:"varint,3,opt,name=expected_parts,json=expectedParts,proto3" json:"expected_parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeUploadBlobRequest) Reset() {
	*x = MaterializeUploadBlobRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeUploadBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeUploadBlobRequest) ProtoMessage() {}

func (x *MaterializeUploadBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeUploadBlobRequest.ProtoReflect.Descriptor instead.
func (*MaterializeUploadBlobRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{9}
}

func (x *MaterializeUploadBlobRequest) GetOwnerUserId() int64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *MaterializeUploadBlobRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *MaterializeUploadBlobRequest) GetExpectedParts() int32 {
	if x != nil {
		return x.ExpectedParts
	}
	return 0
}

type MaterializeUploadBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind     ErrorKind              `protobuf:"varint,5,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeUploadBlobResponse) Reset() {
	*x = MaterializeUploadBlobResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeUploadBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeUploadBlobResponse) ProtoMessage() {}

func (x *MaterializeUploadBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeUploadBlobResponse.ProtoReflect.Descriptor instead.
func (*MaterializeUploadBlobResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{10}
}

func (x *MaterializeUploadBlobResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *MaterializeUploadBlobResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MaterializeUploadBlobResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *MaterializeUploadBlobResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MaterializeUploadBlobResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

type PutBlobChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobChunk) Reset() {
	*x = PutBlobChunk{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobChunk) ProtoMessage() {}

func (x *PutBlobChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobChunk.ProtoReflect.Descriptor instead.
func (*PutBlobChunk) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{11}
}

func (x *PutBlobChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlobObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind     ErrorKind              `protobuf:"varint,5,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobObjectResponse) Reset() {
	*x = BlobObjectResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobObjectResponse) ProtoMessage() {}

func (x *BlobObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobObjectResponse.ProtoReflect.Descriptor instead.
func (*BlobObjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{12}
}

func (x *BlobObjectResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *BlobObjectResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlobObjectResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *BlobObjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BlobObjectResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

type GetBlobRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRangeRequest) Reset() {
	*x = GetBlobRangeRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRangeRequest) ProtoMessage() {}

func (x *GetBlobRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRangeRequest.ProtoReflect.Descriptor instead.
func (*GetBlobRangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{13}
}

func (x *GetBlobRangeRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *GetBlobRangeRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetBlobRangeRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetBlobRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind     ErrorKind              `protobuf:"varint,4,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRangeResponse) Reset() {
	*x = GetBlobRangeResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRangeResponse) ProtoMessage() {}

func (x *GetBlobRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRangeResponse.ProtoReflect.Descriptor instead.
func (*GetBlobRangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{14}
}

func (x *GetBlobRangeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBlobRangeResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetBlobRangeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetBlobRangeResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

type PutUploadPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserId   int64                  `protobuf:"varint,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	FileId        int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FilePart      int32                  `protobuf:"varint,3,opt,name=file_part,json=filePart,proto3" json:"file_part,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutUploadPartRequest) Reset() {
	*x = PutUploadPartRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutUploadPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutUploadPartRequest) ProtoMessage() {}

func (x *PutUploadPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutUploadPartRequest.ProtoReflect.Descriptor instead.
func (*PutUploadPartRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{15}
}

func (x *PutUploadPartRequest) GetOwnerUserId() int64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *PutUploadPartRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *PutUploadPartRequest) GetFilePart() int32 {
	if x != nil {
		return x.FilePart
	}
	return 0
}

func (x *PutUploadPartRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPartObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind     ErrorKind              `protobuf:"varint,6,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartObjectResponse) Reset() {
	*x = UploadPartObjectResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartObjectResponse) ProtoMessage() {}

func (x *UploadPartObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartObjectResponse.ProtoReflect.Descriptor instead.
func (*UploadPartObjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{16}
}

func (x *UploadPartObjectResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *UploadPartObjectResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *UploadPartObjectResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadPartObjectResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *UploadPartObjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadPartObjectResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

type GetUploadPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadPartRequest) Reset() {
	*x = GetUploadPartRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadPartRequest) ProtoMessage() {}

func (x *GetUploadPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadPartRequest.ProtoReflect.Descriptor instead.
func (*GetUploadPartRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{17}
}

func (x *GetUploadPartRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type GetUploadPartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind     ErrorKind              `protobuf:"varint,3,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadPartResponse) Reset() {
	*x = GetUploadPartResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadPartResponse) ProtoMessage() {}

func (x *GetUploadPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadPartResponse.ProtoReflect.Descriptor instead.
func (*GetUploadPartResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{18}
}

func (x *GetUploadPartResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetUploadPartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetUploadPartResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

type DeleteUploadPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUploadPartRequest) Reset() {
	*x = DeleteUploadPartRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUploadPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUploadPartRequest) ProtoMessage() {}

func (x *DeleteUploadPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUploadPartRequest.ProtoReflect.Descriptor instead.
func (*DeleteUploadPartRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteUploadPartRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type DeleteExpiredUploadPartsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BeforeUnixNano int64                  `protobuf:"varint,1,opt,name=before_unix_nano,json=beforeUnixNano,proto3" json:"before_unix_nano,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteExpiredUploadPartsRequest) Reset() {
	*x = DeleteExpiredUploadPartsRequest{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpiredUploadPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpiredUploadPartsRequest) ProtoMessage() {}

func (x *DeleteExpiredUploadPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpiredUploadPartsRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpiredUploadPartsRequest) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteExpiredUploadPartsRequest) GetBeforeUnixNano() int64 {
	if x != nil {
		return x.BeforeUnixNano
	}
	return 0
}

func (x *DeleteExpiredUploadPartsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DeleteExpiredUploadPartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind     ErrorKind              `protobuf:"varint,3,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpiredUploadPartsResponse) Reset() {
	*x = DeleteExpiredUploadPartsResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpiredUploadPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpiredUploadPartsResponse) ProtoMessage() {}

func (x *DeleteExpiredUploadPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpiredUploadPartsResponse.ProtoReflect.Descriptor instead.
func (*DeleteExpiredUploadPartsResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteExpiredUploadPartsResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteExpiredUploadPartsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteExpiredUploadPartsResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorKind     ErrorKind              `protobuf:"varint,2,opt,name=error_kind,json=errorKind,proto3,enum=telesrv.filedata.v1.ErrorKind" json:"error_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_filedata_filedatapb_filedata_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP(), []int{22}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorResponse) GetErrorKind() ErrorKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrorKind_ERROR_KIND_NONE
}

var File_internal_filedata_filedatapb_filedata_proto protoreflect.FileDescriptor

const file_internal_filedata_filedatapb_filedata_proto_rawDesc = "" +
	"\n" +
	"+internal/filedata/filedatapb/filedata.proto\x12\x13telesrv.filedata.v1\"\xa9\x01\n" +
	"\x13FileDataInfoRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\xa3\x02\n" +
	"\x14FileDataInfoResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12C\n" +
	"\x1emin_supported_protocol_version\x18\x02 \x01(\rR\x1bminSupportedProtocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12&\n" +
	"\x0eimplementation\x18\x04 \x01(\tR\x0eimplementation\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\abackend\x18\x06 \x01(\tR\abackend\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xbf\x01\n" +
	"\x13SaveFilePartRequest\x12\"\n" +
	"\rowner_user_id\x18\x01 \x01(\x03R\vownerUserId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\x12\x1b\n" +
	"\tfile_part\x18\x03 \x01(\x05R\bfilePart\x12(\n" +
	"\x10file_total_parts\x18\x04 \x01(\x05R\x0efileTotalParts\x12\x10\n" +
	"\x03big\x18\x05 \x01(\bR\x03big\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\x81\x01\n" +
	"\x14SaveFilePartResponse\x12\x14\n" +
	"\x05saved\x18\x01 \x01(\bR\x05saved\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x03 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind\"a\n" +
	"\x0eGetFileRequest\x12!\n" +
	"\flocation_key\x18\x01 \x01(\tR\vlocationKey\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xae\x03\n" +
	"\x0fGetFileResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x06 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind\x12+\n" +
	"\x11immutable_backend\x18\a \x01(\tR\x10immutableBackend\x120\n" +
	"\x14immutable_object_key\x18\b \x01(\tR\x12immutableObjectKey\x12)\n" +
	"\x10immutable_offset\x18\t \x01(\x03R\x0fimmutableOffset\x12)\n" +
	"\x10immutable_length\x18\n" +
	" \x01(\x05R\x0fimmutableLength\x124\n" +
	"\x16immutable_range_sha256\x18\v \x01(\fR\x14immutableRangeSha256\"Q\n" +
	"\x14GetFileHashesRequest\x12!\n" +
	"\flocation_key\x18\x01 \x01(\tR\vlocationKey\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"L\n" +
	"\bFileHash\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\"\xb9\x01\n" +
	"\x15GetFileHashesResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x125\n" +
	"\x06hashes\x18\x02 \x03(\v2\x1d.telesrv.filedata.v1.FileHashR\x06hashes\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x04 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind\"\x82\x01\n" +
	"\x1cMaterializeUploadBlobRequest\x12\"\n" +
	"\rowner_user_id\x18\x01 \x01(\x03R\vownerUserId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\x12%\n" +
	"\x0eexpected_parts\x18\x03 \x01(\x05R\rexpectedParts\"\xbf\x01\n" +
	"\x1dMaterializeUploadBlobResponse\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x05 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind\"\"\n" +
	"\fPutBlobChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xb4\x01\n" +
	"\x12BlobObjectResponse\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x05 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind\"b\n" +
	"\x13GetBlobRangeRequest\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\x95\x01\n" +
	"\x14GetBlobRangeResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x04 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind\"\x84\x01\n" +
	"\x14PutUploadPartRequest\x12\"\n" +
	"\rowner_user_id\x18\x01 \x01(\x03R\vownerUserId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\x12\x1b\n" +
	"\tfile_part\x18\x03 \x01(\x05R\bfilePart\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xd4\x01\n" +
	"\x18UploadPartObjectResponse\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x06 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind\"5\n" +
	"\x14GetUploadPartRequest\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\"\x80\x01\n" +
	"\x15GetUploadPartResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x03 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind\"8\n" +
	"\x17DeleteUploadPartRequest\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\"a\n" +
	"\x1fDeleteExpiredUploadPartsRequest\x12(\n" +
	"\x10before_unix_nano\x18\x01 \x01(\x03R\x0ebeforeUnixNano\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x91\x01\n" +
	" DeleteExpiredUploadPartsResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x03 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind\"d\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12=\n" +
	"\n" +
	"error_kind\x18\x02 \x01(\x0e2\x1e.telesrv.filedata.v1.ErrorKindR\terrorKind*\x89\x02\n" +
	"\tErrorKind\x12\x13\n" +
	"\x0fERROR_KIND_NONE\x10\x00\x12 \n" +
	"\x1cERROR_KIND_FILE_PART_INVALID\x10\x01\x12!\n" +
	"\x1dERROR_KIND_FILE_PARTS_INVALID\x10\x02\x12 \n" +
	"\x1cERROR_KIND_FILE_PART_TOO_BIG\x10\x03\x12$\n" +
	" ERROR_KIND_UPLOAD_QUOTA_EXCEEDED\x10\x04\x12\x1b\n" +
	"\x17ERROR_KIND_STORAGE_FULL\x10\x05\x12\x1c\n" +
	"\x18ERROR_KIND_PHOTO_INVALID\x10\x06\x12\x1f\n" +
	"\x1bERROR_KIND_DOCUMENT_INVALID\x10\a2\x95\t\n" +
	"\x0fFileDataService\x12^\n" +
	"\aGetInfo\x12(.telesrv.filedata.v1.FileDataInfoRequest\x1a).telesrv.filedata.v1.FileDataInfoResponse\x12c\n" +
	"\fSaveFilePart\x12(.telesrv.filedata.v1.SaveFilePartRequest\x1a).telesrv.filedata.v1.SaveFilePartResponse\x12T\n" +
	"\aGetFile\x12#.telesrv.filedata.v1.GetFileRequest\x1a$.telesrv.filedata.v1.GetFileResponse\x12f\n" +
	"\rGetFileHashes\x12).telesrv.filedata.v1.GetFileHashesRequest\x1a*.telesrv.filedata.v1.GetFileHashesResponse\x12~\n" +
	"\x15MaterializeUploadBlob\x121.telesrv.filedata.v1.MaterializeUploadBlobRequest\x1a2.telesrv.filedata.v1.MaterializeUploadBlobResponse\x12W\n" +
	"\aPutBlob\x12!.telesrv.filedata.v1.PutBlobChunk\x1a'.telesrv.filedata.v1.BlobObjectResponse(\x01\x12c\n" +
	"\fGetBlobRange\x12(.telesrv.filedata.v1.GetBlobRangeRequest\x1a).telesrv.filedata.v1.GetBlobRangeResponse\x12i\n" +
	"\rPutUploadPart\x12).telesrv.filedata.v1.PutUploadPartRequest\x1a-.telesrv.filedata.v1.UploadPartObjectResponse\x12f\n" +
	"\rGetUploadPart\x12).telesrv.filedata.v1.GetUploadPartRequest\x1a*.telesrv.filedata.v1.GetUploadPartResponse\x12d\n" +
	"\x10DeleteUploadPart\x12,.telesrv.filedata.v1.DeleteUploadPartRequest\x1a\".telesrv.filedata.v1.ErrorResponse\x12\x87\x01\n" +
	"\x18DeleteExpiredUploadParts\x124.telesrv.filedata.v1.DeleteExpiredUploadPartsRequest\x1a5.telesrv.filedata.v1.DeleteExpiredUploadPartsResponseB1Z/telesrv/internal/filedata/filedatapb;filedatapbb\x06proto3"

var (
	file_internal_filedata_filedatapb_filedata_proto_rawDescOnce sync.Once
	file_internal_filedata_filedatapb_filedata_proto_rawDescData []byte
)

func file_internal_filedata_filedatapb_filedata_proto_rawDescGZIP() []byte {
	file_internal_filedata_filedatapb_filedata_proto_rawDescOnce.Do(func() {
		file_internal_filedata_filedatapb_filedata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_filedata_filedatapb_filedata_proto_rawDesc), len(file_internal_filedata_filedatapb_filedata_proto_rawDesc)))
	})
	return file_internal_filedata_filedatapb_filedata_proto_rawDescData
}

var file_internal_filedata_filedatapb_filedata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_filedata_filedatapb_filedata_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internal_filedata_filedatapb_filedata_proto_goTypes = []any{
	(ErrorKind)(0),                           // 0: telesrv.filedata.v1.ErrorKind
	(*FileDataInfoRequest)(nil),              // 1: telesrv.filedata.v1.FileDataInfoRequest
	(*FileDataInfoResponse)(nil),             // 2: telesrv.filedata.v1.FileDataInfoResponse
	(*SaveFilePartRequest)(nil),              // 3: telesrv.filedata.v1.SaveFilePartRequest
	(*SaveFilePartResponse)(nil),             // 4: telesrv.filedata.v1.SaveFilePartResponse
	(*GetFileRequest)(nil),                   // 5: telesrv.filedata.v1.GetFileRequest
	(*GetFileResponse)(nil),                  // 6: telesrv.filedata.v1.GetFileResponse
	(*GetFileHashesRequest)(nil),             // 7: telesrv.filedata.v1.GetFileHashesRequest
	(*FileHash)(nil),                         // 8: telesrv.filedata.v1.FileHash
	(*GetFileHashesResponse)(nil),            // 9: telesrv.filedata.v1.GetFileHashesResponse
	(*MaterializeUploadBlobRequest)(nil),     // 10: telesrv.filedata.v1.MaterializeUploadBlobRequest
	(*MaterializeUploadBlobResponse)(nil),    // 11: telesrv.filedata.v1.MaterializeUploadBlobResponse
	(*PutBlobChunk)(nil),                     // 12: telesrv.filedata.v1.PutBlobChunk
	(*BlobObjectResponse)(nil),               // 13: telesrv.filedata.v1.BlobObjectResponse
	(*GetBlobRangeRequest)(nil),              // 14: telesrv.filedata.v1.GetBlobRangeRequest
	(*GetBlobRangeResponse)(nil),             // 15: telesrv.filedata.v1.GetBlobRangeResponse
	(*PutUploadPartRequest)(nil),             // 16: telesrv.filedata.v1.PutUploadPartRequest
	(*UploadPartObjectResponse)(nil),         // 17: telesrv.filedata.v1.UploadPartObjectResponse
	(*GetUploadPartRequest)(nil),             // 18: telesrv.filedata.v1.GetUploadPartRequest
	(*GetUploadPartResponse)(nil),            // 19: telesrv.filedata.v1.GetUploadPartResponse
	(*DeleteUploadPartRequest)(nil),          // 20: telesrv.filedata.v1.DeleteUploadPartRequest
	(*DeleteExpiredUploadPartsRequest)(nil),  // 21: telesrv.filedata.v1.DeleteExpiredUploadPartsRequest
	(*DeleteExpiredUploadPartsResponse)(nil), // 22: telesrv.filedata.v1.DeleteExpiredUploadPartsResponse
	(*ErrorResponse)(nil),                    // 23: telesrv.filedata.v1.ErrorResponse
}
var file_internal_filedata_filedatapb_filedata_proto_depIdxs = []int32{
	0,  // 0: telesrv.filedata.v1.SaveFilePartResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	0,  // 1: telesrv.filedata.v1.GetFileResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	8,  // 2: telesrv.filedata.v1.GetFileHashesResponse.hashes:type_name -> telesrv.filedata.v1.FileHash
	0,  // 3: telesrv.filedata.v1.GetFileHashesResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	0,  // 4: telesrv.filedata.v1.MaterializeUploadBlobResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	0,  // 5: telesrv.filedata.v1.BlobObjectResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	0,  // 6: telesrv.filedata.v1.GetBlobRangeResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	0,  // 7: telesrv.filedata.v1.UploadPartObjectResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	0,  // 8: telesrv.filedata.v1.GetUploadPartResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	0,  // 9: telesrv.filedata.v1.DeleteExpiredUploadPartsResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	0,  // 10: telesrv.filedata.v1.ErrorResponse.error_kind:type_name -> telesrv.filedata.v1.ErrorKind
	1,  // 11: telesrv.filedata.v1.FileDataService.GetInfo:input_type -> telesrv.filedata.v1.FileDataInfoRequest
	3,  // 12: telesrv.filedata.v1.FileDataService.SaveFilePart:input_type -> telesrv.filedata.v1.SaveFilePartRequest
	5,  // 13: telesrv.filedata.v1.FileDataService.GetFile:input_type -> telesrv.filedata.v1.GetFileRequest
	7,  // 14: telesrv.filedata.v1.FileDataService.GetFileHashes:input_type -> telesrv.filedata.v1.GetFileHashesRequest
	10, // 15: telesrv.filedata.v1.FileDataService.MaterializeUploadBlob:input_type -> telesrv.filedata.v1.MaterializeUploadBlobRequest
	12, // 16: telesrv.filedata.v1.FileDataService.PutBlob:input_type -> telesrv.filedata.v1.PutBlobChunk
	14, // 17: telesrv.filedata.v1.FileDataService.GetBlobRange:input_type -> telesrv.filedata.v1.GetBlobRangeRequest
	16, // 18: telesrv.filedata.v1.FileDataService.PutUploadPart:input_type -> telesrv.filedata.v1.PutUploadPartRequest
	18, // 19: telesrv.filedata.v1.FileDataService.GetUploadPart:input_type -> telesrv.filedata.v1.GetUploadPartRequest
	20, // 20: telesrv.filedata.v1.FileDataService.DeleteUploadPart:input_type -> telesrv.filedata.v1.DeleteUploadPartRequest
	21, // 21: telesrv.filedata.v1.FileDataService.DeleteExpiredUploadParts:input_type -> telesrv.filedata.v1.DeleteExpiredUploadPartsRequest
	2,  // 22: telesrv.filedata.v1.FileDataService.GetInfo:output_type -> telesrv.filedata.v1.FileDataInfoResponse
	4,  // 23: telesrv.filedata.v1.FileDataService.SaveFilePart:output_type -> telesrv.filedata.v1.SaveFilePartResponse
	6,  // 24: telesrv.filedata.v1.FileDataService.GetFile:output_type -> telesrv.filedata.v1.GetFileResponse
	9,  // 25: telesrv.filedata.v1.FileDataService.GetFileHashes:output_type -> telesrv.filedata.v1.GetFileHashesResponse
	11, // 26: telesrv.filedata.v1.FileDataService.MaterializeUploadBlob:output_type -> telesrv.filedata.v1.MaterializeUploadBlobResponse
	13, // 27: telesrv.filedata.v1.FileDataService.PutBlob:output_type -> telesrv.filedata.v1.BlobObjectResponse
	15, // 28: telesrv.filedata.v1.FileDataService.GetBlobRange:output_type -> telesrv.filedata.v1.GetBlobRangeResponse
	17, // 29: telesrv.filedata.v1.FileDataService.PutUploadPart:output_type -> telesrv.filedata.v1.UploadPartObjectResponse
	19, // 30: telesrv.filedata.v1.FileDataService.GetUploadPart:output_type -> telesrv.filedata.v1.GetUploadPartResponse
	23, // 31: telesrv.filedata.v1.FileDataService.DeleteUploadPart:output_type -> telesrv.filedata.v1.ErrorResponse
	22, // 32: telesrv.filedata.v1.FileDataService.DeleteExpiredUploadParts:output_type -> telesrv.filedata.v1.DeleteExpiredUploadPartsResponse
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_filedata_filedatapb_filedata_proto_init() }
func file_internal_filedata_filedatapb_filedata_proto_init() {
	if File_internal_filedata_filedatapb_filedata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_filedata_filedatapb_filedata_proto_rawDesc), len(file_internal_filedata_filedatapb_filedata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_filedata_filedatapb_filedata_proto_goTypes,
		DependencyIndexes: file_internal_filedata_filedatapb_filedata_proto_depIdxs,
		EnumInfos:         file_internal_filedata_filedatapb_filedata_proto_enumTypes,
		MessageInfos:      file_internal_filedata_filedatapb_filedata_proto_msgTypes,
	}.Build()
	File_internal_filedata_filedatapb_filedata_proto = out.File
	file_internal_filedata_filedatapb_filedata_proto_goTypes = nil
	file_internal_filedata_filedatapb_filedata_proto_depIdxs = nil
}
