// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: internal/filedata/filedatapb/filedata.proto

package filedatapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileDataService_GetInfo_FullMethodName                  = "/telesrv.filedata.v1.FileDataService/GetInfo"
	FileDataService_SaveFilePart_FullMethodName             = "/telesrv.filedata.v1.FileDataService/SaveFilePart"
	FileDataService_GetFile_FullMethodName                  = "/telesrv.filedata.v1.FileDataService/GetFile"
	FileDataService_GetFileHashes_FullMethodName            = "/telesrv.filedata.v1.FileDataService/GetFileHashes"
	FileDataService_MaterializeUploadBlob_FullMethodName    = "/telesrv.filedata.v1.FileDataService/MaterializeUploadBlob"
	FileDataService_PutBlob_FullMethodName                  = "/telesrv.filedata.v1.FileDataService/PutBlob"
	FileDataService_GetBlobRange_FullMethodName             = "/telesrv.filedata.v1.FileDataService/GetBlobRange"
	FileDataService_PutUploadPart_FullMethodName            = "/telesrv.filedata.v1.FileDataService/PutUploadPart"
	FileDataService_GetUploadPart_FullMethodName            = "/telesrv.filedata.v1.FileDataService/GetUploadPart"
	FileDataService_DeleteUploadPart_FullMethodName         = "/telesrv.filedata.v1.FileDataService/DeleteUploadPart"
	FileDataService_DeleteExpiredUploadParts_FullMethodName = "/telesrv.filedata.v1.FileDataService/DeleteExpiredUploadParts"
)

// FileDataServiceClient is the client API for FileDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileDataServiceClient interface {
	GetInfo(ctx context.Context, in *FileDataInfoRequest, opts ...grpc.CallOption) (*FileDataInfoResponse, error)
	SaveFilePart(ctx context.Context, in *SaveFilePartRequest, opts ...grpc.CallOption) (*SaveFilePartResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	GetFileHashes(ctx context.Context, in *GetFileHashesRequest, opts ...grpc.CallOption) (*GetFileHashesResponse, error)
	MaterializeUploadBlob(ctx context.Context, in *MaterializeUploadBlobRequest, opts ...grpc.CallOption) (*MaterializeUploadBlobResponse, error)
	PutBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutBlobChunk, BlobObjectResponse], error)
	GetBlobRange(ctx context.Context, in *GetBlobRangeRequest, opts ...grpc.CallOption) (*GetBlobRangeResponse, error)
	PutUploadPart(ctx context.Context, in *PutUploadPartRequest, opts ...grpc.CallOption) (*UploadPartObjectResponse, error)
	GetUploadPart(ctx context.Context, in *GetUploadPartRequest, opts ...grpc.CallOption) (*GetUploadPartResponse, error)
	DeleteUploadPart(ctx context.Context, in *DeleteUploadPartRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	DeleteExpiredUploadParts(ctx context.Context, in *DeleteExpiredUploadPartsRequest, opts ...grpc.CallOption) (*DeleteExpiredUploadPartsResponse, error)
}

type fileDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileDataServiceClient(cc grpc.ClientConnInterface) FileDataServiceClient {
	return &fileDataServiceClient{cc}
}

func (c *fileDataServiceClient) GetInfo(ctx context.Context, in *FileDataInfoRequest, opts ...grpc.CallOption) (*FileDataInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileDataInfoResponse)
	err := c.cc.Invoke(ctx, FileDataService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileDataServiceClient) SaveFilePart(ctx context.Context, in *SaveFilePartRequest, opts ...grpc.CallOption) (*SaveFilePartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveFilePartResponse)
	err := c.cc.Invoke(ctx, FileDataService_SaveFilePart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileDataServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, FileDataService_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileDataServiceClient) GetFileHashes(ctx context.Context, in *GetFileHashesRequest, opts ...grpc.CallOption) (*GetFileHashesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileHashesResponse)
	err := c.cc.Invoke(ctx, FileDataService_GetFileHashes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileDataServiceClient) MaterializeUploadBlob(ctx context.Context, in *MaterializeUploadBlobRequest, opts ...grpc.CallOption) (*MaterializeUploadBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaterializeUploadBlobResponse)
	err := c.cc.Invoke(ctx, FileDataService_MaterializeUploadBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileDataServiceClient) PutBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutBlobChunk, BlobObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileDataService_ServiceDesc.Streams[0], FileDataService_PutBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutBlobChunk, BlobObjectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileDataService_PutBlobClient = grpc.ClientStreamingClient[PutBlobChunk, BlobObjectResponse]

func (c *fileDataServiceClient) GetBlobRange(ctx context.Context, in *GetBlobRangeRequest, opts ...grpc.CallOption) (*GetBlobRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlobRangeResponse)
	err := c.cc.Invoke(ctx, FileDataService_GetBlobRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileDataServiceClient) PutUploadPart(ctx context.Context, in *PutUploadPartRequest, opts ...grpc.CallOption) (*UploadPartObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPartObjectResponse)
	err := c.cc.Invoke(ctx, FileDataService_PutUploadPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileDataServiceClient) GetUploadPart(ctx context.Context, in *GetUploadPartRequest, opts ...grpc.CallOption) (*GetUploadPartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadPartResponse)
	err := c.cc.Invoke(ctx, FileDataService_GetUploadPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileDataServiceClient) DeleteUploadPart(ctx context.Context, in *DeleteUploadPartRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, FileDataService_DeleteUploadPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileDataServiceClient) DeleteExpiredUploadParts(ctx context.Context, in *DeleteExpiredUploadPartsRequest, opts ...grpc.CallOption) (*DeleteExpiredUploadPartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExpiredUploadPartsResponse)
	err := c.cc.Invoke(ctx, FileDataService_DeleteExpiredUploadParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileDataServiceServer is the server API for FileDataService service.
// All implementations must embed UnimplementedFileDataServiceServer
// for forward compatibility.
type FileDataServiceServer interface {
	GetInfo(context.Context, *FileDataInfoRequest) (*FileDataInfoResponse, error)
	SaveFilePart(context.Context, *SaveFilePartRequest) (*SaveFilePartResponse, error)
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	GetFileHashes(context.Context, *GetFileHashesRequest) (*GetFileHashesResponse, error)
	MaterializeUploadBlob(context.Context, *MaterializeUploadBlobRequest) (*MaterializeUploadBlobResponse, error)
	PutBlob(grpc.ClientStreamingServer[PutBlobChunk, BlobObjectResponse]) error
	GetBlobRange(context.Context, *GetBlobRangeRequest) (*GetBlobRangeResponse, error)
	PutUploadPart(context.Context, *PutUploadPartRequest) (*UploadPartObjectResponse, error)
	GetUploadPart(context.Context, *GetUploadPartRequest) (*GetUploadPartResponse, error)
	DeleteUploadPart(context.Context, *DeleteUploadPartRequest) (*ErrorResponse, error)
	DeleteExpiredUploadParts(context.Context, *DeleteExpiredUploadPartsRequest) (*DeleteExpiredUploadPartsResponse, error)
	mustEmbedUnimplementedFileDataServiceServer()
}

// UnimplementedFileDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileDataServiceServer struct{}

func (UnimplementedFileDataServiceServer) GetInfo(context.Context, *FileDataInfoRequest) (*FileDataInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedFileDataServiceServer) SaveFilePart(context.Context, *SaveFilePartRequest) (*SaveFilePartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFilePart not implemented")
}
func (UnimplementedFileDataServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedFileDataServiceServer) GetFileHashes(context.Context, *GetFileHashesRequest) (*GetFileHashesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileHashes not implemented")
}
func (UnimplementedFileDataServiceServer) MaterializeUploadBlob(context.Context, *MaterializeUploadBlobRequest) (*MaterializeUploadBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaterializeUploadBlob not implemented")
}
func (UnimplementedFileDataServiceServer) PutBlob(grpc.ClientStreamingServer[PutBlobChunk, BlobObjectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PutBlob not implemented")
}
func (UnimplementedFileDataServiceServer) GetBlobRange(context.Context, *GetBlobRangeRequest) (*GetBlobRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlobRange not implemented")
}
func (UnimplementedFileDataServiceServer) PutUploadPart(context.Context, *PutUploadPartRequest) (*UploadPartObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutUploadPart not implemented")
}
func (UnimplementedFileDataServiceServer) GetUploadPart(context.Context, *GetUploadPartRequest) (*GetUploadPartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadPart not implemented")
}
func (UnimplementedFileDataServiceServer) DeleteUploadPart(context.Context, *DeleteUploadPartRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUploadPart not implemented")
}
func (UnimplementedFileDataServiceServer) DeleteExpiredUploadParts(context.Context, *DeleteExpiredUploadPartsRequest) (*DeleteExpiredUploadPartsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExpiredUploadParts not implemented")
}
func (UnimplementedFileDataServiceServer) mustEmbedUnimplementedFileDataServiceServer() {}
func (UnimplementedFileDataServiceServer) testEmbeddedByValue()                         {}

// UnsafeFileDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileDataServiceServer will
// result in compilation errors.
type UnsafeFileDataServiceServer interface {
	mustEmbedUnimplementedFileDataServiceServer()
}

func RegisterFileDataServiceServer(s grpc.ServiceRegistrar, srv FileDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileDataService_ServiceDesc, srv)
}

func _FileDataService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileDataInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).GetInfo(ctx, req.(*FileDataInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileDataService_SaveFilePart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveFilePartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).SaveFilePart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_SaveFilePart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).SaveFilePart(ctx, req.(*SaveFilePartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileDataService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileDataService_GetFileHashes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileHashesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).GetFileHashes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_GetFileHashes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).GetFileHashes(ctx, req.(*GetFileHashesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileDataService_MaterializeUploadBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaterializeUploadBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).MaterializeUploadBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_MaterializeUploadBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).MaterializeUploadBlob(ctx, req.(*MaterializeUploadBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileDataService_PutBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileDataServiceServer).PutBlob(&grpc.GenericServerStream[PutBlobChunk, BlobObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileDataService_PutBlobServer = grpc.ClientStreamingServer[PutBlobChunk, BlobObjectResponse]

func _FileDataService_GetBlobRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).GetBlobRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_GetBlobRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).GetBlobRange(ctx, req.(*GetBlobRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileDataService_PutUploadPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutUploadPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).PutUploadPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_PutUploadPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).PutUploadPart(ctx, req.(*PutUploadPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileDataService_GetUploadPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).GetUploadPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_GetUploadPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).GetUploadPart(ctx, req.(*GetUploadPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileDataService_DeleteUploadPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUploadPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).DeleteUploadPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_DeleteUploadPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).DeleteUploadPart(ctx, req.(*DeleteUploadPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileDataService_DeleteExpiredUploadParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExpiredUploadPartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDataServiceServer).DeleteExpiredUploadParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDataService_DeleteExpiredUploadParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDataServiceServer).DeleteExpiredUploadParts(ctx, req.(*DeleteExpiredUploadPartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileDataService_ServiceDesc is the grpc.ServiceDesc for FileDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telesrv.filedata.v1.FileDataService",
	HandlerType: (*FileDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _FileDataService_GetInfo_Handler,
		},
		{
			MethodName: "SaveFilePart",
			Handler:    _FileDataService_SaveFilePart_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _FileDataService_GetFile_Handler,
		},
		{
			MethodName: "GetFileHashes",
			Handler:    _FileDataService_GetFileHashes_Handler,
		},
		{
			MethodName: "MaterializeUploadBlob",
			Handler:    _FileDataService_MaterializeUploadBlob_Handler,
		},
		{
			MethodName: "GetBlobRange",
			Handler:    _FileDataService_GetBlobRange_Handler,
		},
		{
			MethodName: "PutUploadPart",
			Handler:    _FileDataService_PutUploadPart_Handler,
		},
		{
			MethodName: "GetUploadPart",
			Handler:    _FileDataService_GetUploadPart_Handler,
		},
		{
			MethodName: "DeleteUploadPart",
			Handler:    _FileDataService_DeleteUploadPart_Handler,
		},
		{
			MethodName: "DeleteExpiredUploadParts",
			Handler:    _FileDataService_DeleteExpiredUploadParts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutBlob",
			Handler:       _FileDataService_PutBlob_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/filedata/filedatapb/filedata.proto",
}
